### ISSUE TITLE
Layout (UI)

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#1]
A big thing we need to figure out is the UI. What is the interface going to look like? Here are a few mockups, copy + pasted from the Scratch Forums.

![image](https://cloud.githubusercontent.com/assets/5458180/8759724/6f304048-2cc9-11e5-9437-3503105ab0b9.png)
<sup>^ The detail is much appreciated</sup>

![image](https://cloud.githubusercontent.com/assets/5458180/8759727/8897ee32-2cc9-11e5-961b-c82f7ce80819.png)

![image](https://cloud.githubusercontent.com/assets/5458180/8759729/8d255b1a-2cc9-11e5-9a21-670fb2ef1715.png)

![image](https://cloud.githubusercontent.com/assets/5458180/8759819/b7828d8a-2ccc-11e5-837c-9ecb8fd82ad3.png)

![image](https://cloud.githubusercontent.com/assets/5458180/8761638/18d2bdce-2d29-11e5-92ef-adc6955c1055.png)
^ Click to zoom

**Comment by PullJosh** [comment]
I definitely like having a large viewing area as shown in the third design (as well as the first, but... well... y'know...)

Viewing the page at a large scale will be far more vital in Elemental than it is in Scratch, because viewers of the page will see it on a relatively large monitor. (More precise resizing than Scratch will also be necessary.)

**Comment by towerofnix** [comment]
Gonna say you should definitely make it so there are folders otherwise it'll be very, very cluttered, like Scratch already is.

Also perhaps another category in the Resources area, "etc" or "misc"? To contain files it doesn't recognize, or archives, or whatever lol.

**Comment by PullJosh** [comment]
Yeah... I'd say let the user make folders and then put whatever stuff they want wherever they want. Don't, however, sort all their stuff into categories for them.

**Comment by PullJosh** [comment]
Just added my own mockup (the final one). Let me know what you guys think!

**Comment by quat1024** [comment]
Love that last one. Searchable blocks = genius !!!

**Comment by PullJosh** [comment]
I think we'll need that, given the massive amount of blocks we have. Also, we'll need to be able to search for what the blocks _do_, not just their names. (Ex. "link" should return an a tag as one of the results)

**Comment by towerofnix** [comment]
So would "link" return both `<link>` and `<a>`?

**Comment by matthewr6** [comment]
Yes.
Love the last mockup but I think that the display and code areas should be switched so the page dimensions are more correct for what you'd see normally.

**Comment by PullJosh** [comment]
The display width is totally adjustable (similar to the way Codepen does it when your code is on the left or the right), so there's no need to swap positions. :)

**Comment by matthewr6** [comment]
K, cool.

**Comment by BookOwl** [comment]
I like the last one.

**Comment by PullJosh** [comment]
Yay! I'm good at this! :3

**Comment by glacialcascade** [comment]
How about the page-viewing thingy allows you to switch between viewing and the resource stuff you made and we also adopt the first/second one.

**Comment by matthewr6** [comment]
Something like this would be nice:
http://prntscr.com/7ubhs2
So you can only have one actual "script" (html or whatever) per file, and anything not under there isn't parsed.

**Comment by glacialcascade** [comment]
Yeah, and also implement the search

**Comment by matthewr6** [comment]
Search is easy if we're using the DOM and including React.js - just give me the list of searchable items and I can implement it.

**Comment by glacialcascade** [comment]
+1

**Comment by quat1024** [comment]
All signs seem to be pointing towards drawing the blocks in the DOM, right?

The hard part about that is - I hope we don't need any of the pointy boolean blocks, because those are likely impossible to do in CSS alone xD (WAIT NO I forgot about clip-path)

**Comment by PullJosh** [comment]
@quat1024 We could always take the pixie approach and make loads of canvases. :P

**Comment by matthewr6** [comment]
ow no

**Comment by PullJosh** [comment]
Going to work on a bit of UI stuff.

**Comment by matthewr6** [comment]
Ok

**Comment by PullJosh** [comment]
**v0.0.1 of UI Finished**
I'm pretty happy with how this is coming along! It's not pretty - not by any stretch of the imagination. However, it's ever so slightly functional, and it uses minimal JS (entirely (S)CSS, aside from dragging to resize the editor/preview). The entire thing should be a good step forward. :grinning:

https://github.com/ElementalCode/Elemental/tree/ui/ui/v0.0.1

**Comment by matthewr6** [comment]
Tell me when you want me to incorporate it into the actual site.

**Comment by TheInitializer** [comment]
I like the last one.

**Comment by PullJosh** [comment]
last one?

**Comment by matthewr6** [comment]
Second-to-last combined with last.

**Comment by PullJosh** [comment]
**v0.0.2 of UI Finished**
Quite a few gradients involved... let me know what you think. For now, though, I think it's another step in the right direction (certainly prettier than 0.0.1).

https://github.com/ElementalCode/Elemental/tree/ui/ui/v0.0.2

**Comment by an-OK-squirrel** [comment]
KK

**Comment by an-OK-squirrel** [comment]
Busy atm tho

**Comment by matthewr6** [comment]
same, but I like it

**Comment by PullJosh** [comment]
That's fine. :)

**Comment by an-OK-squirrel** [comment]
I love it!

**Comment by PullJosh** [comment]
Awesome! :D

**Comment by PullJosh** [comment]
Does this look okay?

![UI Possibility](http://i.gyazo.com/62227a454d2120b51eadef9451b21530.png)

**Comment by PullJosh** [comment]
Somehow the phrase "fake blocks and flexbox" just rolls off the tongue nicely...
<sup><sub>I'm weird. :P</sub></sup>

**Comment by matthewr6** [comment]
flexbox is fun

**Comment by quat1024** [comment]
Looks sexy man.

OK it's feedback time! Part 1: stuff that's relevant now
- I don't like the scrollbar next to the categories, we'll prolly only have 8 anyways so I think you can get rid of it.
- If you don't want to remove it, well it only scrolls a couple pixels down, which is kinda strange, so you could shrink the categories
- The search bar looks out of place where it is, I'd give it the same amount of margin-right as the blocks area has & make it wider, or center it.
- The rounded corners on the search icon thing make me think it's a pulldown, actually, which doesn't sound good for usability
- Whole page seems to have a random black border on the left
- Search icon is off center, move it right 1-2px?
- gradients ahshdjhshahdgd. I think the category picker would look better with a little less box-shadow. Try straight corners instead of round ones in the picker too, just to see how they look.(me: Yah yah flat design blabbity blah :stuck_out_tongue: )
- I think the block area should have a different background than the pickers. Uh, how about a subtle grid pattern (like graph paper?)

Stuff that's relevant later / me just complaining about placeholders lol:
- When you add the page preview, it might make the category picker / block picker uncomfortably thin horizontally on non-widescreen displays (Sidenote: my monitor is 5:4 which is actually even less wide than 4:3. If it works on my monitor it'll work on anything :stuck_out_tongue: )
- Wordmark is super bland :stuck_out_tongue:
- Categories are too similar in color imo, might be hard to tell them apart when the blocks are assembled

Sorry I haven't been coding anything, busy busy

**Comment by PullJosh** [comment]
1) It is automatic, so if we go with only 8 categories, it will go away on its own
2) I'll just switch it to 8
3) You're right - I'll do that
4) It sort of is (but not exactly):
![image](http://i.gyazo.com/800d0f6d50dc5cd4924a337ef28cb0c7.gif)
5) I just dragged it over there. :P
![image](http://i.gyazo.com/9ffe9bb34cd99bc328e9c921bcb2346c.gif)
6) Will fix
7) lolno
![image](http://i.gyazo.com/8bd53d80c9302bfdc761f5c889a65e89.png)
8) Was on the to-do list

9) You saw what it looks like in number 5.
10) Wordmark? You mean the "Elemental" text in the top-left?
11) Yeah, having 10 makes that difficult. We can always change that later

**Comment by PullJosh** [comment]
Made a fun little pattern for the bottom area.
![image](https://cloud.githubusercontent.com/assets/5458180/8852013/cd5d55e2-3120-11e5-8155-5d46f72ba334.png)

Here it is in use, toned down a bit with some [nifty CSS](https://css-tricks.com/tinted-images-multiple-backgrounds/):
![image](http://i.gyazo.com/d10b3f4f02dfd4c5c6a042767882ceef.png)
(You might have to click the image to fully see what it looks like.)

What do you guys think?

**Comment by matthewr6** [comment]
css-tricks is awesome.
I still like it :)

**Comment by an-OK-squirrel** [comment]
Good!

**Comment by an-OK-squirrel** [comment]
Oh, and I got pip added to path finally thank gosh

**Comment by PullJosh** [comment]
Experimenting with the possibility of a flat design... Personally, I'm not a big fan, but I know @quat1024 wanted one. Perhaps there are just a few small tweaks that need to be made in order to make this look beatiful. A person can hope, I suppose...
![image](http://i.gyazo.com/de35dfea7db9623ccf49f8b07229119e.png)

**Comment by matthewr6** [comment]
I like that better, I think

**Comment by an-OK-squirrel** [comment]
I love it!

**Comment by quat1024** [comment]
:heart:

Dropdowns look funny on the background, I'd make the background of the drop down white. That's the thing with flat design, you start running out of colors :P

**Comment by PullJosh** [comment]
lol yeah

**Comment by PullJosh** [comment]
Hmm... just realized that, when the preview area is expanded, the dropdowns will appear above it. How do we plan to make them visible on any background?
![image](http://i.gyazo.com/bf20090b33c0c918efceea0ac6d6b0d2.png)

**Comment by matthewr6** [comment]
Gray?

**Comment by PullJosh** [comment]
And what's the plan when the user's website has a gray background?

**Comment by matthewr6** [comment]
rainbow neon seizure...

**Comment by PullJosh** [comment]
Much better.
![image](http://i.gyazo.com/0aee7c52a26de9c8159db49e7bc2b780.png)

**Comment by matthewr6** [comment]
Quite.

**Comment by PullJosh** [comment]
But seriously... Do we want a border on the thing?

**Comment by matthewr6** [comment]
why didn't we think of that earlier?

**Comment by PullJosh** [comment]
I did, but I figured it would look awful.

Also, putting a border around that top triangle will be tricky. :/

**Comment by matthewr6** [comment]
http://jsfiddle.net/joshnh/26Lww/
http://jhaurawachsman.com/2013/css-triangles-border-stroke/

**Comment by PullJosh** [comment]
Those solutions won't work - I've already used up my two alloted pseudo elements.

**Comment by matthewr6** [comment]
http://www.growingwiththeweb.com/2013/03/triangles-in-css.html
Modify your elements, then.

**Comment by PullJosh** [comment]
Eh... Work.

I'll do it eventually. :P

**Comment by quat1024** [comment]
Wait why 2 psuedoelements ? You could make ::before a square, rotate it 45 degrees with CSS transforms, and still have a border to spare :)

A box-shadow with no blurring could also work.

**Comment by PullJosh** [comment]
:OOO That square though.

(Other element is to extend hover area of element.)

**Comment by mrjacobbloom** [comment]
For the menus, you could try a border/shadow around the text and a semitransparent background. P.S. it's Nicky

edit: or just use the same stripe pattern with a different bg color

**Comment by PullJosh** [comment]
Okay, got a rotated square working:
![image](http://i.gyazo.com/d22e8ce105d5ea0799b1a9eebe57474a.png)
Now for making it look nice...

**Comment by an-OK-squirrel** [comment]
KK

**Comment by quat1024** [comment]
That flatness omg

**Comment by PullJosh** [comment]
@quat1024 Is it good or bad? :3

**Comment by matthewr6** [comment]
Much better

**Comment by PullJosh** [comment]
Good! Tweaking a few things and it should be perfect. :D

**Comment by an-OK-squirrel** [comment]
:D

**Comment by quat1024** [comment]
@pulljosh :heart:

**Comment by PullJosh** [comment]
Does this look good to upload as v0.0.3?
![image](http://i.gyazo.com/970b42ce9480a9bc6b31d11d4e8e5217.png)

**Comment by matthewr6** [comment]
Sure!

**Comment by PullJosh** [comment]
I feel like the "Advanced Mode" checkbox (top right) isn't aligned to any sort of grid...

@quat1024 Opinion?

**Comment by quat1024** [comment]
I'm not one for grids, but if these two distances match I think it'll look better:
- the distance from the left of the logo to the left side of the page
- the distance from the right of the checkbox to the right side of the page

Also pls commit!!!, I would love to mess with this. I have a fork of 0.0.1 that uses flexbox (sorta) on quat1024.github.io/Elemental

**Comment by PullJosh** [comment]
Okay, will do that and commit right after. ;)

**Comment by PullJosh** [comment]
Btw... wasn't working because I was trying to work out how to play that one ocean diving game you made. :P

**Comment by matthewr6** [comment]
lol

**Comment by quat1024** [comment]
Wow ok

**Comment by PullJosh** [comment]
**v0.0.3 of UI Finished**
With the move to flat design, the response seems quite a bit better. Continue to give me your feedback; it's much appreciated!

https://github.com/ElementalCode/Elemental/tree/ui/ui/v0.0.3

**Comment by an-OK-squirrel** [comment]
:D

**Comment by andrewjcole** [comment]
Light and dark options??

**Comment by PullJosh** [comment]
I've never been a fan of having multiple options for colors... Makes it feel like the developers couldn't make up their mind.

We have to stick to one color scheme.

**Comment by andrewjcole** [comment]
Alrighty then. It doesn't exactly mean that you couldn't stick to one decision, but that you like to give the user more options. Some users prefer darker colors to lighter colors.

I'll probably like this either way, so it doesn't really make a difference to me. And obviously from reading your discussions, you don't plan for this to be widely used.

**Comment by PullJosh** [comment]
I do! @Firedrake969 has far less optimistic hopes for the project.

My thinking is that we will be the only people on the planet to have something like this that's up and running - and it's such a good idea! As long as we make it well, why wouldn't people use it?

Plus, there are loads of people on the forums looking for a website maker (to which the ATers become increasing frustrated). If they knew there was one that tranistioned them from Scratch to making websites, who wouldn't give it a try?

As for multiple color schemes: We need to have a theme that defines us - a few colors that scream Elemental. Without that, it will be hard to stick the tool in people's memory. We need people to remember us, and recognise screenshots of the tool.

**Comment by PullJosh** [comment]
Additionally, I've been diliberately choosing a palette that will also work well for a website - I want to keep things consistant between the site's front-end and the programming UI.

The top bar of the tool is intended to look a bit like a navigation bar, allowing us to use that same style (and color) for the Elemental website. The dark colors will be able to give good contrast against white text, and will be great for showcasing a front-page screenshot of the tool.

(I've thought all this through more than some of you might realise. :P)

**Comment by matthewr6** [comment]
I'm not estimating more than 1000 users :P

**Comment by PullJosh** [comment]
Neither am I, but 1000 users is a lot. If I can effect the lives of 1000 people in a positive way, that's a worthwhile investment on my part. Imagine teaching 1000 people to code. Think about how much change you could create with one simple tool.

There's no reason to do things half-way. If you're prepping for failure, then there's no way you'll succeed.

**Comment by andrewjcole** [comment]
Your last point makes sense, @PullJosh. I guess it's probably best to focus on one color scheme at a time in early development, anyway,

**Comment by andrewjcole** [comment]
And I do understand that you have been thinking a lot about this when I saw that you had a whole color scheme and design guide written up. :P

**Comment by PullJosh** [comment]
That's only the tip of the iceberg!

I've also been considering the best way to give tutorials for the interface... It's going to be tricky.
Also, Advanced Mode is something to consider. I haven't given it as much thought as I should have.

**Comment by matthewr6** [comment]
I'm not prepping for failure as much as estimating general overhead (support, moderation, etc).  I completely agree with you though :)

**Comment by PullJosh** [comment]
A valid point.

**Comment by andrewjcole** [comment]
Welp, I'm going to use some word-to-mouth advertising if I end up liking this. I have a lot of friends who could use something like this.

**Comment by matthewr6** [comment]
Most of my friends build stuff like this :P
The more the merrier!

**Comment by an-OK-squirrel** [comment]
If we reach enough users, won't Firedrake have to update the plan?

**Comment by PullJosh** [comment]
We'll think of something.

**Comment by PullJosh** [comment]
If need be, I'd be happy to chip in a bit to keep the site going - if it ever becomes that big a deal, it will be well worth the few extra dollars to keep it hosted.

**Comment by an-OK-squirrel** [comment]
Yeah, okay.

**Comment by PullJosh** [comment]
Been trying out some things for the main Elemental website. I've got [this](http://codepen.io/PullJosh/pen/dogjOX) at the moment, and I think it looks sort of okay.

However, I'm concerned that there's too much centering going on. Every single element on the page is centered, currently, and I don't feel like that's healthy. I was considering adding some text to the right of the button to balance things out, but I'm not sure what to put there. Any ideas?

**Comment by matthewr6** [comment]
Is this for the gh-pages site or the site with the backend?

**Comment by PullJosh** [comment]
They'll become one site, won't they?

My thought was that this would be comparable to the Scratch homepage - a place that allows you to reach the editor, as well as login or sign up.

**Comment by matthewr6** [comment]
Yeah, basically.
I'd love a place for people to be able to login/go to the register page on the home page, then
Also could you check out my PR?  I've started writing some tests because it's just good practice if nothing else.

**Comment by mrjacobbloom** [comment]
I don't know if the blue button goes with the color scheme, but otherwise I like it. It feels very responsive and looks purdy.

**Comment by PullJosh** [comment]
@Firedrake969 PR? To me, that has always meant "Personal Record".

@Airhogs777 I agree - couldn't find any color that fit.

**Comment by PullJosh** [comment]
So it turns out Chrome has a super cool transition editor (in inspect element)!
![image](http://i.gyazo.com/f309cc1244da8bf564192ccb2808503a.png)

**Comment by matthewr6** [comment]
yeah, I've made stuff fade in and out and in and out and in and out and so on with that :P

**Comment by mrjacobbloom** [comment]
random thought: if c-blocks are collapsible, then they should definitely be collapsed in the palate to save spaec

**Comment by matthewr6** [comment]
http://t10.deviantart.net/YdCmfRnXIG0NZ-kQKQNHLzUGFoc=/300x200/filters:fixed_height(100,100):origin()/pre01/8be0/th/pre/f/2010/019/2/a/spaec_by_reality_for_you.png

**Comment by mrjacobbloom** [comment]
wai

**Comment by mrjacobbloom** [comment]
also PJ: why the gradient with 2 of the same color?

**Comment by PullJosh** [comment]
Artifact of the old layout that I never remembered to get rid of...
(I'll fix it in the next update.)

**Comment by PullJosh** [comment]
Unless you're talking about [this one really weird thing](https://github.com/ElementalCode/Elemental/blob/ui/ui/v0.0.3/resources/style.scss#L159) from CSS tricks...

**Comment by mrjacobbloom** [comment]
ohhhh that's stupid but makes sense

**Comment by PullJosh** [comment]
Thanks, man.

**Comment by matthewr6** [comment]
lol

**Comment by PullJosh** [comment]
What should I add to the UI next? The tabs on the bottom?

**Comment by an-OK-squirrel** [comment]
I want to work on the UI but I don't want to be terrible (which I am)

**Comment by TheInitializer** [comment]
I know you think it's a little unique/cool to have the block palette horizontal rather than vertical, but I think a vertical layout is more practical to store blocks in. Just giving advice.

**Comment by PullJosh** [comment]
I wasn't going for unique - I just did what felt better to me.

But you're probably right.

**Comment by andrewjcole** [comment]
I think horizontal looks nice. Just my opinion.

**Comment by PullJosh** [comment]
It doesn't seem to be a huge deal either way, and I don't really feel like changing it if it won't matter too much. :)

**Comment by an-OK-squirrel** [comment]
That was closed 1 month after it was opened

**Comment by matthewr6** [comment]
wow

**Comment by towerofnix** [comment]
necropost!11!!!!!1!!!

:P
