### ISSUE TITLE
CSS blocks

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#101]
A mockup at least would be nice so I have some basic stuff to start working w/.

**Comment by matthewr6** [comment]
Also, @PullJosh, two more things:
- you made the filter block system, right?  I have some stuff I need to coordinate w/you
- the file system CSS is weird when you have a long filename

**Comment by towerofnix** [comment]
Whoa did the GitHub notification icon change?

It's a bell now.

`</offtopic>`

I can start making mockup `[scratchblocks]`! :P

**Comment by an-OK-squirrel** [comment]
yeah it is :package:

**Comment by matthewr6** [comment]
I mean mockup as in with actual HTML and CSS, so if so yeah that'd be great

**Comment by PullJosh** [comment]
@Firedrake969
1) I'm up for anything. But tomorrow. Feeling tired/headachey (is a word) tonight.
2) I'll figure something out. But tomorrow.

**Comment by matthewr6** [comment]
Sure thing, but would Saturday work?  I'm in MST.
and ok

**Comment by PullJosh** [comment]
Feeling better now. :)

Saturday's fine. I'll figure out the filestystem long names thing soon.

**Comment by matthewr6** [comment]
Ok thanks

**Comment by PullJosh** [comment]
Checking out your context menu thing... Will merge if it looks good.

**Comment by matthewr6** [comment]
What time zone are you in?

**Comment by PullJosh** [comment]
It's just past 8 in the morning, whatever time zone that is.

**Comment by matthewr6** [comment]
So EST ok

**Comment by an-OK-squirrel** [comment]
what bout you, firedrake?

**Comment by matthewr6** [comment]
MST, you?

**Comment by an-OK-squirrel** [comment]
It's 7:19, whenever that is. forty minutes until school

**Comment by PullJosh** [comment]
Fire is earliest, squirrel is 1 hour later, i'm one hour later than that.

**Comment by PullJosh** [comment]
^ all the capitalize

**Comment by an-OK-squirrel** [comment]
Okay!

**Comment by matthewr6** [comment]
Let's coordinate a chat time for Saturday later today

**Comment by an-OK-squirrel** [comment]
I might be busy Saturday. I'll try though

**Comment by PullJosh** [comment]
Sounds good. How about we coordinate it 10 hours from now? (And 7 minutes)

**Comment by an-OK-squirrel** [comment]
which is when?

**Comment by PullJosh** [comment]
6:30 for me, 5:30 for you (PM)

**Comment by an-OK-squirrel** [comment]
I'm more of an early person though :P

**Comment by an-OK-squirrel** [comment]
Also, I'm assuming you mean Gitter?

**Comment by matthewr6** [comment]
I can't promise anything yet...
I know I'm busy up to 4 my time

**Comment by PullJosh** [comment]
@an-OK-squirrel Are you questioning whether your assumption is correct, or the more fundamental question of whether or not you are assuming anything at all?

**Comment by an-OK-squirrel** [comment]
-_- too early 4 m3

**Comment by matthewr6** [comment]
Not gitter, probably just in jsfiddle

**Comment by an-OK-squirrel** [comment]
I dun have a jsf account...

**Comment by PullJosh** [comment]
...

**Comment by an-OK-squirrel** [comment]
also, is this just for randomness or what are we talking about

**Comment by an-OK-squirrel** [comment]
I think it's anonomous, try setting one up

**Comment by an-OK-squirrel** [comment]
*anonymous

**Comment by PullJosh** [comment]
1) It's not
2) I feel like we sort of need to figure out exactly what's going on - each person is doing their own little part, but we haven't fully thought out how we want everything to work. But you'll have to talk to Fire to see what he was thinking as well.

**Comment by an-OK-squirrel** [comment]
Uh-huh, ok

**Comment by matthewr6** [comment]
Yeah just more organizing of our plans - alpha goals, jobs, etc

**Comment by an-OK-squirrel** [comment]
Wait a second, yes JSF is... http://jsfiddle.net/awv3s54h/#&togetherjs=VIc92h1mbe

**Comment by PullJosh** [comment]
Are you logged in?

**Comment by an-OK-squirrel** [comment]
nope, don't have an account

**Comment by an-OK-squirrel** [comment]
still works

**Comment by PullJosh** [comment]
Oh, weird...

Let me try starting one.

**Comment by robinp7720** [comment]
![css editor edea](https://cloud.githubusercontent.com/assets/10325589/9569001/6f594898-4f5c-11e5-9d3e-fbafdc1780e1.png)
Friendly suggestion/idea

An idea for an editor which describes content. Would work pretty well with css but, As Elemental is block based, probably wouldn't work.

Main feature is the ability to reuse styles and media queries. Though, it might look chaotic very quickly.

**Comment by an-OK-squirrel** [comment]
looks good, but not for Elemental :/

**Comment by TheInitializer** [comment]
[here's my mockup](http://scratchblocks.github.io/#tag%20[h1%20v]%20%3A%3Acontrol%20cstart%0A[font-family%20v]%20is%20[Lato]%3A%3Asound%0A[font-size%20v]%20is%20[15]%3A%3Asound%0Aend%0A%0Aid%20[thing]%20%3A%3Acontrol%20cstart%0A[background-color%20v]%20is%20[red]%20%3A%3Aoperators%20%2F%2Fdifferent%20categories%2Fcolours%20for%20different%20rule%20categories%0Aimportant%3A%3Ared%20cstart%20%2F%2Fare%20we%20going%20to%20do%20!important%3F%20it%20can%20be%20bad%20practice%0Aborder%20[left%20v]%20is%20[5][px%20v]%20[solid%20v]%20[red]%3A%3Amotion%20%2F%2F%20a%20more%20complex%20rule%20block%0Aend%0Aend%0A%0Aclass%20[thing]%3A%3Acontrol%20cstart%20%2F%2F%20nesting!%0Aclass%20[other%20thing]%3A%3Aevents%20cstart%2F%2Fmanual%20zebra%20colouring%20yay%0Aid%20[yet%20another%20thing]%3A%3Acontrol%20cstart%0Apadding%20[left%20v]%20is%20[5][px%20v]%3A%3Amotion%0Atag%20[h1%20v]%3A%3Aevents%20cstart%0A[font-family%20v]%20is%20[Comic%20Sans%20MS]%3A%3Asound%0Aend%0Aend%0Aend%0Aend%0A%0Aimport%20css%20from%20[http%3A%2F%2Fcss.com%2Fexample-stylesheet.css]%3A%3Aevents%0A%0Ayeah%3A%3Apen)

**Comment by matthewr6** [comment]
No nesting

**Comment by TheInitializer** [comment]
why not?

**Comment by matthewr6** [comment]
because we're just giving them the basics (CSS, not SASS/SCSS/LESS/whatever) and the library I'll be using doesn't give nesting support :package:

**Comment by matthewr6** [comment]
also I was hoping for a mockup like this
http://jsfiddle.net/Firedrake969/75d1ebrw/

**Comment by TheInitializer** [comment]
lol scratchblocks2's quicker

**Comment by matthewr6** [comment]
but it's not viable until we get an actual HTML/CSS thing working
@PullJosh where are you

**Comment by PullJosh** [comment]
Sorry... was off on a vacation within my summer vacation again (at my Grandma's cottage).

And yes, I'm still on Summer vacation. Michigan is weird.
As for CSS nesting... If you don't let them nest blocks, at least let them have a block in which they can type a custom selector (which could nest things).

**Comment by matthewr6** [comment]
Yeah that is plan I think

**Comment by an-OK-squirrel** [comment]
Heh, I better get going on the user page

**Comment by matthewr6** [comment]
yes

**Comment by glacialcascade** [comment]
[some mockup i made](http://scratchblocks.github.io/#tag%20%5Ba%20v%5D%20%3A%3Acontrol%20cstart%0Aset%20%5Bbackground-color%20v%5D%20to%20%5Bblue%5D%0Aset%20%5Bcolor%20v%5D%20to%20%5Bwhite%5D%0Aend%0Atag%20%5Ba%20v%5D%20pseudo-selector%20%5B%3Ahover%20v%5D%20%3A%3Acontrol%20cstart%0Aset%20%5Bcolor%20v%5D%20to%20%5Bgreen%5D%0Aend)
