### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#105]
What do we want for alpha?  (beta's too far away to talk about yet)

**Comment by an-OK-squirrel** [comment]
Why don't we set up a chat later today and talk about it?

**Comment by towerofnix** [comment]
cuddly bunnies and tasty cookies

**Comment by matthewr6** [comment]
This is why we're chatting tomorrow, @an-OK-squirrel :P 
I can chat at probably 3 PM my time (5 PJ's time, 4 your time)

**Comment by an-OK-squirrel** [comment]
Why not today? I'm not busy at all

**Comment by an-OK-squirrel** [comment]
Also, I eat around 4

**Comment by matthewr6** [comment]
but I have to go soon for around 2 hours

**Comment by an-OK-squirrel** [comment]
Maybe after 3 hours?

**Comment by matthewr6** [comment]
I can't do much today I think

**Comment by an-OK-squirrel** [comment]
:/

**Comment by matthewr6** [comment]
can we chat now?
is @PullJosh online?

**Comment by an-OK-squirrel** [comment]
I guess I'm fine with tomorrow, gives me time to work on Barnacle

**Comment by matthewr6** [comment]
Ok
What's Barnacle?

**Comment by an-OK-squirrel** [comment]
Yeah, @PullJosh make a Doc

**Comment by matthewr6** [comment]
I have to go in about 25 min I think

**Comment by an-OK-squirrel** [comment]
Barnacle is my nothing-yet project. It lets you sticky GH issues

**Comment by matthewr6** [comment]
that's cool

**Comment by matthewr6** [comment]
What time are you available tomorrow?  I can't before 2 your time

**Comment by an-OK-squirrel** [comment]
Hm....

I guess any time 5 or after my time.

**Comment by matthewr6** [comment]
Would 6 work for you, @PullJosh?

**Comment by an-OK-squirrel** [comment]
@Pulljosh spam

**Comment by matthewr6** [comment]
4 my time, 5 an-ok-squirrel's time, and 6 PJ's time looks pretty good right now, but I eat dinner at 6 my time so it might not work for him

**Comment by an-OK-squirrel** [comment]
K then!

**Comment by matthewr6** [comment]
@PullJosh Please leave a message ASAP if it doesn't work for you
Current agreement is chatting 6 PM your time.

**Comment by an-OK-squirrel** [comment]
Let's rename this issue to "chat" :p

**Comment by quat1024** [comment]
If you say his name 3 times in a mirror it's rumored he shows up.

@PullJosh @PullJosh @PullJosh 

Also we should use Gitter for chatting, or literally **anything** other than Github issues. It sends everyone an email whenever _anyone_ comments, whether it's a thoughtful comment or just an emoticon

**Comment by matthewr6** [comment]
Let's not because I actually do need this issue for some stuff
@quat1024 it doesn't send me an email... just configure it in your settings

**Comment by an-OK-squirrel** [comment]
We should use Gitter....

**Comment by matthewr6** [comment]
https://gitter.im/ElementalCode

**Comment by quat1024** [comment]
https://gitter.im/ElementalCode
https://gitter.im/ElementalCode
https://gitter.im/ElementalCode
https://gitter.im/ElementalCode
https://gitter.im/ElementalCode

**Comment by towerofnix** [comment]
halp

link me in

**Comment by matthewr6** [comment]
done

**Comment by towerofnix** [comment]
Whenever I go to Elemental it just brings me to a listing of the rooms there. Then, if I click view room, same thing..

**Comment by quat1024** [comment]
Try now?

**Comment by towerofnix** [comment]
Nope

**Comment by PullJosh** [comment]
> Also we should use Gitter for chatting, or literally anything other than Github issues. It sends everyone an email whenever anyone comments, whether it's a thoughtful comment or just an emoticon

O_o It does? I never get emails. :P Must have turned them off at some point.
