### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#11]
Planning to write it in Django, since I'm pretty familiar with it.

**Comment by PullJosh** [comment]
Whatever you say, boss.

**Comment by matthewr6** [comment]
Just push a tag when you want me to upload to the app.

**Comment by PullJosh** [comment]
wut

**Comment by matthewr6** [comment]
http://prntscr.com/7ubmys

**Comment by PullJosh** [comment]
Nice labeling skillz, @ev3commander.

**Comment by PullJosh** [comment]
@Firedrake969 Okay.

**Comment by matthewr6** [comment]
Should we need any databases?

**Comment by glacialcascade** [comment]
maybe

**Comment by PullJosh** [comment]
Are they free?

**Comment by matthewr6** [comment]
No, but I don't think we'll need them.

**Comment by PullJosh** [comment]
If they were free, we would need boatloads.

Since they cost money, I think we're all set. :P

**Comment by matthewr6** [comment]
ok xD

**Comment by matthewr6** [comment]
setting up some file system stuff

**Comment by Firedrake969** [comment]
Everyone read through https://devcenter.heroku.com/articles/getting-started-with-python#introduction if you want to run it on your local machine easily.

**Comment by PullJosh** [comment]
People on the forums are getting very angry that you're making a backend. :P

**Comment by glacialcascade** [comment]
@PullJosh why?

**Comment by PullJosh** [comment]
They must all be jealous. xD

**Comment by quat1024** [comment]
Probably because a backend's totally unnecessary, right? :stuck_out_tongue:

**Comment by PullJosh** [comment]
That too. :P

**Comment by matthewr6** [comment]
lol
I may be able to make a pretty easy user account system with saving projects, though... will have to see if my skills are up to scratch.

**Comment by TheInitializer** [comment]
um... how is a backend unnecessary? how else are you going to save your projects?

**Comment by matthewr6** [comment]
Exactly
