### ISSUE TITLE
turn off autocorrect for URL bars in links and such

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#111]
it must be possible...

**Comment by an-OK-squirrel** [comment]
http://davidwalsh.name/disable-autocorrect

**Comment by PullJosh** [comment]
Keep in mind that the inputs are actually editable spans. Your linked trick might work, but it might not...

**Comment by an-OK-squirrel** [comment]
... -_-

**Comment by PullJosh** [comment]
:package:

**Comment by matthewr6** [comment]
haha
gitter please

**Comment by an-OK-squirrel** [comment]
Yeah FireDrake check your gitter :package:

**Comment by matthewr6** [comment]
I saw

**Comment by an-OK-squirrel** [comment]
reply den

**Comment by matthewr6** [comment]
http://stackoverflow.com/questions/21163002/disable-autocorrect-autocompletion-in-content-editable-div

**Comment by an-OK-squirrel** [comment]
thanks

**Comment by matthewr6** [comment]
so is it working?

**Comment by an-OK-squirrel** [comment]
no clue

**Comment by an-OK-squirrel** [comment]
haven't done it yet.

**Comment by matthewr6** [comment]
Ok
feel free to :package:
