### ISSUE TITLE
C-blocks broken

### ISSUE THREAD

**Issue by TheInitializer** [ElementalCode/elemental#113]
![C-blocks broken?](http://i.imgur.com/edUwAw2.png)
Only happens when I drag them out of the pallette. They look that way in the pallette also.
Firefox 40 non-e10s

**Comment by matthewr6** [comment]
CSS issue, not JS issue, most likely.

**Comment by infinitytec** [comment]
Yeah. When you put a bock in it, it works.

**Comment by matthewr6** [comment]
EmentalCod - bock baed pogamming!
Inspect Element it?
fixed by init

**Comment by matthewr6** [comment]
....what
http://api.browsershots.org/png/original/a9/a903dd4157ab24b142e3855a98e3d21f.png
is going on here... someone screenshot the editor as soon as it loads?  (ie no right clicking, switching files, no interaction at all)

**Comment by matthewr6** [comment]
could someone put all our CSS rules through caniuse?

**Comment by matthewr6** [comment]
think I fixed...

**Comment by an-OK-squirrel** [comment]
Hey! I helped too

**Comment by matthewr6** [comment]
well I did show you how to... :P

**Comment by an-OK-squirrel** [comment]
I fixed it before you told me

**Comment by an-OK-squirrel** [comment]
_facepalm_

**Comment by matthewr6** [comment]
No you didn't, not according to our Gitter chat :P

**Comment by an-OK-squirrel** [comment]
what?

**Comment by an-OK-squirrel** [comment]
...

**Comment by an-OK-squirrel** [comment]
Isn't this fixed?

**Comment by matthewr6** [comment]
Yeah
