### ISSUE TITLE
Giant dump of Firefox glitches

### ISSUE THREAD

**Issue by TheInitializer** [ElementalCode/elemental#116]
- [x] Empty text inputs aren't there
- [x] You can't highlight
- [x] You can only place the cursor at the beginning of the text
- [x] Delete key only moves the cursor forward 1 space and doesn't delete anything

**Comment by matthewr6** [comment]
> Giant dump
> is empty

**Comment by TheInitializer** [comment]
@Firedrake969 lol I pressed enter on the title by accident, it's fixed now

**Comment by matthewr6** [comment]
why are checkboxes broken

**Comment by TheInitializer** [comment]
fixed them

**Comment by matthewr6** [comment]
oh k

**Comment by matthewr6** [comment]
I have no idea about the other three... @PullJosh any ideas?

**Comment by PullJosh** [comment]
I'll take a look, but I don't know anything off-hand.

**Comment by TheInitializer** [comment]
first issue is resolved w/ latest commit

**Comment by PullJosh** [comment]
Seems that Firefox has a lot of issues in their bug tracker regarding contenteditable...

Worried that we might have to use text inputs.

**Comment by matthewr6** [comment]
They won't be able to expand automatically unless we want to get really really inefficient.

**Comment by TheInitializer** [comment]
huh, it works in Firefox Nightly w/ e10s...

**Comment by PullJosh** [comment]
@Firedrake969 What if we run the inefficient expansion script in FF only?

**Comment by matthewr6** [comment]
But we'd have to switch between inputs and spans as well

**Comment by PullJosh** [comment]
Hmm...

**Comment by TheInitializer** [comment]
We just have to wait till Firefox Stable switches to e10s :P

**Comment by TheInitializer** [comment]
We just have to wait till Firefox Stable switches to e10s :P

**Comment by TheInitializer** [comment]
lol sorry for double post, my mouse has a weird glitch that makes it click twice
and I can't open it :P

**Comment by an-OK-squirrel** [comment]
first one isn't fixed yet for me...

**Comment by matthewr6** [comment]
screenshot and inspect element

**Comment by an-OK-squirrel** [comment]
http://prntscr.com/8hoz7m

http://prntscr.com/8hp011

**Comment by matthewr6** [comment]
Oh oops easy fix

**Comment by TheInitializer** [comment]
@Firedrake969 still not fixed

**Comment by an-OK-squirrel** [comment]
Try setting  min width.

**Comment by TheInitializer** [comment]
Everything's fixed now, closing
