### ISSUE TITLE
Better tracker

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#117]
Something like Trello, Pivotal, JIRA, or Waffle.io?  it's so much easier to track what we do with those things

**Comment by PullJosh** [comment]
Trello seems nice.

**Comment by matthewr6** [comment]
I'd prefer anything that integrates w/GitHub because it's hard to keep track of all my accounts :package:

**Comment by PullJosh** [comment]
Okay, that's fine.

**Comment by matthewr6** [comment]
oh that's cool

**Comment by an-OK-squirrel** [comment]
So waffle?

**Comment by matthewr6** [comment]
yes

**Comment by an-OK-squirrel** [comment]
getting an account

**Comment by an-OK-squirrel** [comment]
https://waffle.io/ElementalCode/Elemental

**Comment by an-OK-squirrel** [comment]
https://waffle.io/ElementalCode/Elemental/join
