### ISSUE TITLE
Specs for all pages?

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#119]
Otherwise, inconsistency

and that's bad

**Comment by TheInitializer** [comment]
What do you mean by specs?

**Comment by an-OK-squirrel** [comment]
Like, thumbnail size, fonts, colors

**Comment by an-OK-squirrel** [comment]
gtg

**Comment by TheInitializer** [comment]
well of course we put those on all pages :package:

**Comment by an-OK-squirrel** [comment]
Yeah, but it should be consistent. We have a bunch of developers doing the front-end. So maybe on a userpage colors are completely different than frontpage

**Comment by PullJosh** [comment]
Shoutout to me for doing (or at least starting) this ages ago.
https://github.com/ElementalCode/Elemental/wiki/Dev-Notes

**Comment by an-OK-squirrel** [comment]
doesn't have enough

**Comment by PullJosh** [comment]
No, but I would continue on there rather than starting yet another place we have to go to.

**Comment by an-OK-squirrel** [comment]
kk

**Comment by rumanti** [comment]
Continuing discussion, here's some specs to discuss and decide:
- Design style to follow (e.g. flat)
- Colors (background, content, text, header, et cetera) I know that the wiki already contain a colors section, but it's for the Elemental editor, not the site in general.
- Typography (please alert me if I'm missing something here, but as far as I know, we've not reached and agreement yet)

I am currently trying to get rid of [my inconsistencies](http://codepen.io/Rumanti/),  and specs are the best solution to this.

---

My input: 
- For the design, I think [Scratch's approach](http://codepen.io/Rumanti/pen/NGNOPy) works well. But in my opinion, it doesn't go well with a white background. Other than "Scratch's approach", there are also other alternatives, such as flat and [material design](http://opensprites.org) ( :package: )
- The colors are dependent of the design. The design should be agreed upon _first_. 
- For the typography - I love Raleway for headers and "big text", but I prefer Palanquin, Roboto or Open Sans for smaller text and content.

**Comment by PolyEdge** [comment]
:+1: for Roboto. Roboto Slab would look nice too :wink:

**Comment by PolyEdge** [comment]
And also the width of the userpage mockup panels should be the standard.

Except for studios

**Comment by rumanti** [comment]
Why except for studios? How is it supposed to look like anyway?

**Comment by matthewr6** [comment]
one thing at a time - if we get a working front page, I can work on putting studios in the backend :)

**Comment by PolyEdge** [comment]
Ok, I am on it.

By the way where do you want me to upload the userpage injection thing?

**Comment by matthewr6** [comment]
what do you mean by that?

**Comment by PolyEdge** [comment]
The userpage html compiler.

**Comment by matthewr6** [comment]
uh
we don't use "compilers" for pages - we just pass in various things (eg a user object, a list of their projects, etc) and have the HTML template interpret/display them

**Comment by PolyEdge** [comment]
kk then there are a lot of things to insert :package:

**Comment by matthewr6** [comment]
What exactly is needed?

**Comment by PolyEdge** [comment]
bio, name, user group, id -> icon, featured project name and id... more

**Comment by matthewr6** [comment]
Bio, name, group, id, icon, featured project data, and stuff are all going to be on the user model.
If you can give me a list I can categorize exactly what will come from what

**Comment by PolyEdge** [comment]
- name (user model)
- group (user model)
- bio (user model)
- projects `[['name', id], ['name', 'id']]` (user model)
- fav projects `[['name', id], ['name', 'id']]` (user model)
- featured project `{'name':'project', id:1234}` (user model)
- studios curate `[['name', id], ['name', 'id']]` (user model)
- studios following `[['name', id], ['name', 'id']]` (user model)
- following `['user', 'user1', 'user2']` (user model)
- followers `['user', 'user1', 'user2']` (user model)

**Comment by PolyEdge** [comment]
Ugh python2 idle is so bad. It crashed. And I lost things. Without warning.

I'll have it up in a bit.

**Comment by matthewr6** [comment]
_coughsublimecough_

**Comment by PolyEdge** [comment]
so do you want the userpage css? i'm too lazy to customize it to go into main.css without breaking things.

**Comment by matthewr6** [comment]
user.name
user.group
user.bio
user.project_set.all (or something like that)
    project.name, project.id
user.favorited_project_set.all (or something)
    (same as above)

basically the same for most of those... if you can do the HTML with placeholders I can have the data ready.

you have read most of django's docs right?

**Comment by matthewr6** [comment]
wait I thought @Rumanti finished the userpages

**Comment by matthewr6** [comment]
I want you to make a front page @Dylan5797

**Comment by PolyEdge** [comment]
wat

**Comment by matthewr6** [comment]
wat wat

**Comment by matthewr6** [comment]
yeah userpages are [done](http://codepen.io/Rumanti/pen/NGNOPy)

**Comment by matthewr6** [comment]
let's bring this to gitter actually

**Comment by PolyEdge** [comment]
but the js was broke and there were no dynamic tile sizes and following bars

**Comment by matthewr6** [comment]
to gitter please

**Comment by PolyEdge** [comment]
kk

**Comment by an-OK-squirrel** [comment]
what am i doing again

**Comment by ghost** [comment]
:shipit:

**Comment by PolyEdge** [comment]
wat

**Comment by PolyEdge** [comment]
> what am i doing again

apparently "no things"

**Comment by matthewr6** [comment]
can't remember rn :L
