### ISSUE TITLE
Reconciling backend and frontend

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#12]
First - please learn Django templating.  It'll make everyone's lives easier.
Second - put all your CSS/JS in the static folders.  Will explain later...

**Comment by matthewr6** [comment]
also, sorry I had to commit, but this should start scaffolding fairly well

**Comment by PullJosh** [comment]
Do you want folders within the static folders, such as "scripts, styles, etc,"?

**Comment by matthewr6** [comment]
yes please

**Comment by glacialcascade** [comment]
ok
