### ISSUE TITLE
Even more intuitive block deleting

### ISSUE THREAD

**Issue by towerofnix** [ElementalCode/elemental#127]
Basically to work like it does in KhanAcademy's (~~terrible~~ it's in alpha :package:) [block editor](https://www.khanacademy.org/computing/hour-of-code/hour-of-code-blocks/p/challenge-simple-snowman).

**Comment by matthewr6** [comment]
wait what KA has one? no offense, I love you KA, but ewwwwww

-ftfy

**Comment by matthewr6** [comment]
also @PullJosh or @an-OK-squirrel can do this

**Comment by an-OK-squirrel** [comment]
Whaaaaa?

**Comment by an-OK-squirrel** [comment]
because a trash can isn't obvious enough?

**Comment by matthewr6** [comment]
still not done

**Comment by towerofnix** [comment]
rip

**Comment by matthewr6** [comment]
rest in pepperoni

does anybody want to add this

if not I can but it's not on my priority list

**Comment by an-OK-squirrel** [comment]
rest in rip

**Comment by matthewr6** [comment]
@an-OK-squirrel blog things

**Comment by an-OK-squirrel** [comment]
k

**Comment by matthewr6** [comment]
still have yet to do this... @ElementalCode/programmers who wants to do this

**Comment by TheInitializer** [comment]
what exactly do we want to do?

**Comment by BookOwl** [comment]
I'll work on it.

**Comment by matthewr6** [comment]
Thanks

**Comment by matthewr6** [comment]
@BookOwl

**Comment by BookOwl** [comment]
@Firedrake969 what?

**Comment by matthewr6** [comment]
> I'll work on it.

How's it going?
(super bored rn so just going through like every issue)

**Comment by BookOwl** [comment]
Good. I got the server running, and I have a couple ideas on how to make it easier to know how to delete blocks. I just need the source of the trashcan images

**Comment by matthewr6** [comment]
oh yeah I just talked to you on another issue didn't I
e.e

**Comment by matthewr6** [comment]
https://github.com/ElementalCode/elemental/tree/master/apps/projects/static/img

**Comment by BookOwl** [comment]
@Firedrake969 I meant is there an SVG of the trashcan image?

**Comment by matthewr6** [comment]
nope

**Comment by matthewr6** [comment]
idk who made it

**Comment by matthewr6** [comment]
ohwait @PullJosh

**Comment by BookOwl** [comment]
Would you guys be ok putting some text up above the trash can saying "Drag block here to delete them"?

**Comment by matthewr6** [comment]
Sure!

**Comment by BookOwl** [comment]
@ElementalCode/programmers @ElementalCode/page-design What font are we using for the editor?

**Comment by PolyEdge** [comment]
> @ElementalCode/programmers ~~@ElementalCode/page-design~~ What font are we using for the editor?

idk, I'm not affiliated with editor design

**Comment by matthewr6** [comment]
idk, look in the CSS files

**Comment by iamunknown2** [comment]
Shouldn't intuitive-trash be forked from block-editor or gh-pages?

**Comment by matthewr6** [comment]
It's probably fine

**Comment by iamunknown2** [comment]
Wait - what's the point of

```
&:hover,
&.hovering
```

Couldn't you just rely on one? Isn't this redundant?

**Comment by matthewr6** [comment]
Whenever I'm asked that question, I always know that there is or used to be a reason.

I never know why, though :P  Probably something about cross-browser compatibility

**Comment by iamunknown2** [comment]
I've made my own branch: https://github.com/ElementalCode/elemental/tree/block-editor-intuitive-trash/resources/css

You may want to improve on the quality of the image.

**Comment by mrjacobbloom** [comment]
Resolved in #222
