### ISSUE TITLE
How readable is my code?

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#128]

**Comment by an-OK-squirrel** [comment]
on a scale from 1 to 10, I'd say around -910930219.

**Comment by an-OK-squirrel** [comment]
On a scale from 1 to 5, I'd say masfmkd'k

**Comment by PullJosh** [comment]
+masfmkd'k

**Comment by an-OK-squirrel** [comment]
Check gitter fd pj

**Comment by matthewr6** [comment]
k

**Comment by PolyEdge** [comment]
I'd say it's fine.
I think you have a different definition of readable code @an-OK-squirrel
