### ISSUE TITLE
Scss?

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#13]
SASS is amazing, and we should use it.
But it does require command-line skills... :P

**Comment by quat1024** [comment]
hey look at this https://github.com/medialize/sass.js/

**Comment by matthewr6** [comment]
but that'll be slower :L

**Comment by PullJosh** [comment]
That's fine, but I would require people to learn it - you already want all of us to use django.

Plus, standard CSS is still valid SCSS. So sure, if you want, we can use SCSS.

**Comment by matthewr6** [comment]
but scss's nesting is AMAZING!
Yeah, it'd be nice if we used scss just so those who are interested can use its features to do things that they like.

**Comment by matthewr6** [comment]
that probably will sound wrong in an hour or two

**Comment by glacialcascade** [comment]
Ok so what are we using now? CSS, SCSS, Heroku, or Django?

I'm going with plain css.

**Comment by PullJosh** [comment]
I'll use the basic features of SCSS, like nesting and _maybe_ a few variables.

**Comment by PullJosh** [comment]
Final decision: **SCSS will be used, but nobody will be required to learn it. All valid CSS is still valid SCSS, so only use the SCSS features if you feel comfortable with them.**

Reopen if you have any objections.

**Comment by matthewr6** [comment]
:)

**Comment by towerofnix** [comment]
Awesome!
