### ISSUE TITLE
Style Attribute Inputs

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#130]

**Comment by an-OK-squirrel** [comment]
Working on it, I just finished lunch

**Comment by matthewr6** [comment]
@PullJosh @an-OK-squirrel who's doing this and how's it going?

**Comment by an-OK-squirrel** [comment]
Not me

**Comment by PullJosh** [comment]
@Firedrake969 Was `attr-dropdown-styles` not what you wanted?

**Comment by matthewr6** [comment]
Yeah, it was - didn't see this when I posted.  The orange (on the background of the =) is kinda ugly IMO though, but probably not a huge deal
