### ISSUE TITLE
User Pages

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#131]

**Comment by an-OK-squirrel** [comment]
...

**Comment by matthewr6** [comment]
Are you done?

**Comment by an-OK-squirrel** [comment]
nope

**Comment by matthewr6** [comment]
Do

**Comment by an-OK-squirrel** [comment]
mayyyyybe

**Comment by an-OK-squirrel** [comment]
Let's go on gitter

**Comment by matthewr6** [comment]
Ok

**Comment by an-OK-squirrel** [comment]
v0.1 of user pages is done I guess...

**Comment by matthewr6** [comment]
now for v0.2 :P

**Comment by rumanti** [comment]
Other than:
- Rank
- Username
- Featured project (might be renamed)
- About me (might be renamed)
- Favorites carousels

...
What do we need? :package:

**Comment by matthewr6** [comment]
Projects carousel?  :P 
Make sure that the carousels (man that's hard to spell) work when empty, too

**Comment by rumanti** [comment]
Oh yeah. How can I forgot ;-;

**Comment by matthewr6** [comment]
It's fine; it's just one of the most important parts of the user page :P

**Comment by rumanti** [comment]
:stuck_out_tongue:

**Comment by rumanti** [comment]
This is done, right? :package:

**Comment by matthewr6** [comment]
Yeah
