### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#132]
What license do we want for the `master` branch?
I'm for just leaving a license out - it means other GitHub users can view and fork this repository, but we still retain all copyrights to our work.

**Comment by an-OK-squirrel** [comment]
Seems good to me.

**Comment by matthewr6** [comment]
This is a rather serious thing, so I'm going to keep track of votes...
**Leave out license:**  3
~~**Other:**  0~~

**Comment by an-OK-squirrel** [comment]
strawpoll?

**Comment by matthewr6** [comment]
nah because anyone can vote on that

**Comment by an-OK-squirrel** [comment]
darn

**Comment by matthewr6** [comment]
also we should trademark this... it has the potential to get really big.  we don't need to register it (yet :P)

**Comment by an-OK-squirrel** [comment]
> (yet :P)

**Comment by an-OK-squirrel** [comment]
Whoa...

Wait a second.

Did you actually say Elemental has potential? That it might have more than 50 users?

**_whooooooaaa**_

**Comment by matthewr6** [comment]
That's when we start begging for donations... xD
seriously though we should look into legal stuff as well so people can't steal this.  The current license (copyright) is what we should stay with IMO

**Comment by PullJosh** [comment]
Assuming that what you said is all correct (in a technical sense), I'd agree that leaving it out is best.

**Comment by matthewr6** [comment]
Ok, I guess we've decided :P
