### ISSUE TITLE
Thumbnail size?

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#133]

**Comment by matthewr6** [comment]
Um...  we're not doing user thumbnails because they worry me

**Comment by matthewr6** [comment]
don't want anyone uploading bad images

**Comment by an-OK-squirrel** [comment]
_facepalm_

no project previews?

**Comment by matthewr6** [comment]
Oh... No idea... Ask PullJosh

**Comment by matthewr6** [comment]
hm, something like this in mind?  http://html2canvas.hertzen.com/documentation.html

**Comment by an-OK-squirrel** [comment]
Seems good.

**Comment by PullJosh** [comment]
As of now, let's just use lorempixel.com in place of thumbnails and such. As things progress, we can pinpoint exactly what things we should allow to be shared.

**Comment by matthewr6** [comment]
Ok, what size though?

**Comment by TheInitializer** [comment]
640x480 seems appropriate. It's what scratch uses.

**Comment by matthewr6** [comment]
sure

**Comment by matthewr6** [comment]
gitter

**Comment by matthewr6** [comment]
Seem to be done.
