### ISSUE TITLE
should we make a slack or a trello or something?

### ISSUE THREAD

**Issue by quat1024** [ElementalCode/elemental#14]
Right now we're discussing things over comments in github issues, which is working, but I think it's kinda awkward.

Maybe we could use a Trello board or something like Slack.com to discuss things easier. Tell me which one you like. I'm leaning towards Trello.

**Comment by BookOwl** [comment]
I don't want to have to create another account....

**Comment by PullJosh** [comment]
Personally, I'm totally fine with github. However, if you feel it's really necessary, I'd be willing to sign up.

**Comment by matthewr6** [comment]
Something where our email addresses aren't visible (or we can hide them).

**Comment by glacialcascade** [comment]
I would use github

**Comment by quat1024** [comment]
Yeah on second thought github's working fine

**Comment by glacialcascade** [comment]
go github

**Comment by quat1024** [comment]
Oh btw I can't seem to find the "close issue" button, you had to close it for me. Hm

**Comment by PullJosh** [comment]
It's next to the "comment" button.

**Comment by PullJosh** [comment]
(on this issue it now says "reopen")

**Comment by quat1024** [comment]
[No it isn't](http://i.imgur.com/sMnQE9g.png)

**Comment by PullJosh** [comment]
[Weird.](http://i.gyazo.com/e55d0bb938339db5aa93704d7dc3d052.png)

**Comment by quat1024** [comment]
[Maybe this is why?](https://help.github.com/articles/permission-levels-for-an-organization-repository/)

Huh

**Comment by PullJosh** [comment]
Maybe. :/ The only level up from there is "Admin".

**Comment by quat1024** [comment]
Oh, the "programmers" group doesn't have write access to anything https://github.com/orgs/ElementalCode/teams/programmers (says "0 repositories" on the left)

**Comment by PullJosh** [comment]
[They seem to.](http://i.gyazo.com/c11ee7526b302066216cda37afb0800c.png) :/

**Comment by quat1024** [comment]
Removed myself from the Owners group because now Programmers has write access. Thanks!

**Comment by PullJosh** [comment]
np. ;)
