### ISSUE TITLE
TypeError: selected is null

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#141]
Happens when you click an arrow in the palette. Should be very easy to fix.

**Comment by matthewr6** [comment]
"should be"

**Comment by matthewr6** [comment]
what is v005 anyways

**Comment by an-OK-squirrel** [comment]
It was there. I think it's editor v005

**Comment by matthewr6** [comment]
idk what version we're on... we should do tags xD

**Comment by an-OK-squirrel** [comment]
haha yes

**Comment by matthewr6** [comment]
but idk what tag we're on... xD

**Comment by an-OK-squirrel** [comment]
gitter

**Comment by matthewr6** [comment]
k

**Comment by matthewr6** [comment]
done yet?

**Comment by an-OK-squirrel** [comment]
oh crap I totally forgot.

**Comment by an-OK-squirrel** [comment]
Hey, that commit's hash is a number! Derp

**Comment by an-OK-squirrel** [comment]
2497238
