### ISSUE TITLE
Private site code?

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#145]
Like Scratch - the editor is open source, but the site is closed source.  Probably more secure that way too.

**Comment by an-OK-squirrel** [comment]
agreed

**Comment by an-OK-squirrel** [comment]
But who wants to pay?

**Comment by matthewr6** [comment]
GitLab is free

**Comment by an-OK-squirrel** [comment]
Kk

**Comment by an-OK-squirrel** [comment]
Kk

**Comment by an-OK-squirrel** [comment]
making it..

**Comment by an-OK-squirrel** [comment]
You do it derp

**Comment by an-OK-squirrel** [comment]
What's your gitlab username?

**Comment by TheInitializer** [comment]
@PullJosh import the repo pls

**Comment by matthewr6** [comment]
Working on it

**Comment by matthewr6** [comment]
Ok, we'll have to start transitioning our deployment and stuff over there and only keep the editor here

**Comment by matthewr6** [comment]
The only thing is that I think we'll all have to learn to commit via Git

**Comment by an-OK-squirrel** [comment]
Invite me !

**Comment by an-OK-squirrel** [comment]
You are now [firedrake] an owner of https://gitlab.com/groups/ElementalCode/group_members

**Comment by matthewr6** [comment]
https://gitlab.com/groups/ElementalCodeBackend/

**Comment by matthewr6** [comment]
wait you made ElementalCode already? ...

**Comment by matthewr6** [comment]
ok this should work

**Comment by an-OK-squirrel** [comment]
you downgraded me to dev ;-; why

**Comment by an-OK-squirrel** [comment]
> learn to commit via Git

`git commit -m "blah"`

**Comment by matthewr6** [comment]
well...
@ElementalCode/programmers 
It seems like there's no good CI for GitLab... :/  Should we keep the source code on GitHub and make it public, or pitch in a little bit (like 7 a month IIRC) for a plan?  I wouldn't mind the latter if @PullJosh was willing to do some of it (I would match him of course)

**Comment by an-OK-squirrel** [comment]
I at the moment have no money...

But we could set up donations, or if you guys are smart enough mine some bitcoins

I have never done that though

**Comment by an-OK-squirrel** [comment]
Idea! https://www.patreon.com/signup

**Comment by an-OK-squirrel** [comment]
wait a second.

**Comment by an-OK-squirrel** [comment]
# Let's wait until we have a stable site.

Literally all our site is is a login, register, mystuff, and editor.

We're okay until we get to a working site with user pages, project pages, and possibly comments.

OK?

**Comment by matthewr6** [comment]
Did you read Gitter?  :P

**Comment by an-OK-squirrel** [comment]
yes
what about it

**Comment by an-OK-squirrel** [comment]
You were talking about tcodina for a few hours

**Comment by matthewr6** [comment]
I meant the important part lol

**Comment by an-OK-squirrel** [comment]
That were not using gl? Iknow

**Comment by matthewr6** [comment]
Nvm

**Comment by an-OK-squirrel** [comment]
You on gitter? 
I'm not.

**Comment by matthewr6** [comment]
Nope

**Comment by an-OK-squirrel** [comment]
XD I love being homeschooled when nobodies home.
