### ISSUE TITLE
sandboxing

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#154]
Codepen uses `sandbox="allow-scripts allow-pointer-lock allow-same-origin allow-popups allow-forms"`.  something like that?  must do more research

**Comment by an-OK-squirrel** [comment]
seems good.

**Comment by matthewr6** [comment]
you're supposed to do the research... we discussed :P

**Comment by an-OK-squirrel** [comment]
IK

**Comment by an-OK-squirrel** [comment]
`allow-same-origin` is cookies so we shouldn't use that. so now it's `sandbox="allow-scripts allow-pointer-lock allow-popups allow-forms"`

**Comment by matthewr6** [comment]
k

**Comment by an-OK-squirrel** [comment]
so forms should be fine

**Comment by matthewr6** [comment]
Yeah

**Comment by matthewr6** [comment]
Go ahead and add it to block-editor and I'll merge

**Comment by an-OK-squirrel** [comment]
Where?

**Comment by an-OK-squirrel** [comment]
in block-editor?

**Comment by matthewr6** [comment]
> Go ahead and add it to **_block-editor**_ and I'll merge

**Comment by an-OK-squirrel** [comment]
that wasn't anywhere

**Comment by an-OK-squirrel** [comment]
oh it was an edit I'll refresh

**Comment by an-OK-squirrel** [comment]
dun
