### ISSUE TITLE
TEST, PLEASE!

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#158]
Massive update to block-editor with CSS stuff.

**Comment by infinitytec** [comment]
Firefox bug is still a thing.

**Comment by matthewr6** [comment]
On Chrome, then.  The Firefox bug is due to some CSS rules that @an-OK-squirrel and I are trying to figure out.

**Comment by PullJosh** [comment]
It looks great! :D

**Comment by matthewr6** [comment]
Does it work?  (including having elements and styling those elements and downloading/reuploading files)

**Comment by PullJosh** [comment]
Didn't try downloading/uploading. Everything else worked perfectly.

**Comment by matthewr6** [comment]
Could someone try that?  It _should_ work but almost nothing works when it _should_ :P

**Comment by PullJosh** [comment]
> It _should_ work, but almost nothing works when it _should_. :P  

@Firedrake969, 2015

**Comment by matthewr6** [comment]
We need to immortalize that (or me.  I'm fine with just immortalizing myself, too)

**Comment by matthewr6** [comment]
done
