### ISSUE TITLE
My Stuff equivalent page

### ISSUE THREAD

**Issue by rumanti** [ElementalCode/elemental#161]
Someone please think of a better name.

**Comment by towerofnix** [comment]
(My) Creations / Projects?

**Comment by matthewr6** [comment]
My Pages?

**Comment by towerofnix** [comment]
Except that projects can have more than one page..

**Comment by matthewr6** [comment]
My Sites?

**Comment by towerofnix** [comment]
My Things

Muuuuch better than My Stuff

**Comment by matthewr6** [comment]
ALL THE THINGS

**Comment by towerofnix** [comment]
My swaggy hax0r dewdls

**Comment by rumanti** [comment]
My Awesomeness?

Sounds nice IMO :P

**Comment by matthewr6** [comment]
hahaha...
no

**Comment by rumanti** [comment]
Front-end is done
