### ISSUE TITLE
note to self

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#17]
remove projectownership and manytomany on user model
add user foreignkey to project model
use reverse lookup to query for projects

**Comment by BookOwl** [comment]
What?

**Comment by matthewr6** [comment]
talked with some people and that's what they suggested for django cleanliness rather than using a through model -
primarily efficiency

**Comment by PullJosh** [comment]
Not sure if this should be closed... Someone please close it if it can be.

(I'm on a cleaning spree at the moment.)

**Comment by matthewr6** [comment]
yeah, can be closed, sorry

**Comment by PullJosh** [comment]
That's fine - this is why I go on these closing sessions. ;)
