### ISSUE TITLE
Remove unused CSS rules

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#171]
Some of the rules aren't used at all.  Find and remove them.

**Comment by PolyEdge** [comment]
Where? In all the css stuff?

**Comment by matthewr6** [comment]
In `style.scss` (always in that file).  Make sure you compile and test it!

**Comment by matthewr6** [comment]
Do you use Gitter?  You probably should log on to it and check out our chatroom.

**Comment by PolyEdge** [comment]
Ok.

**Comment by PolyEdge** [comment]
Nobodys there.

**Comment by matthewr6** [comment]
I am...

**Comment by matthewr6** [comment]
I think @Dylan5797 has finished this, but reopen this if I'm wrong.
