### ISSUE TITLE
Logging in does not work locally

### ISSUE THREAD

**Issue by PolyEdge** [ElementalCode/elemental#172]
This is because the user table is stored on the Heroku servers. How can we bypass this? (I'm working on some user stuff)

**Comment by matthewr6** [comment]
It's because you don't have any users.  You have to make your own :P 
`python manage.py createsuperuser`
You should probably read the Django documentation ;)

**Comment by PolyEdge** [comment]
What is the username?

**Comment by PolyEdge** [comment]
Because I already did that

**Comment by matthewr6** [comment]
You make your own.

**Comment by PolyEdge** [comment]
(I wrote a batch file if that's relevant)

**Comment by matthewr6** [comment]
Nope, just use a normal command line/terminal.

**Comment by PolyEdge** [comment]
Oh ok

**Comment by Dylan5797** [comment]
Sorry I kept getting error 500 and couldn't comment

**Comment by Dylan5797** [comment]
:P

**Comment by PolyEdge** [comment]
Sorry for my noobiness
