### ISSUE TITLE
Naming of collections/galleries/studios?

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#173]
What should a collection of pages/sites be named?

**Comment by towerofnix** [comment]
Did we not discuss this years ago or something? :package:

**Comment by matthewr6** [comment]
idk

**Comment by towerofnix** [comment]
I think we agreed on [assemblage](http://dictionary.reference.com/browse/assemblage?s=t)

> a group of things gathered or collected

**Comment by matthewr6** [comment]
Votes?

**Comment by PolyEdge** [comment]
No assemblage! That would generate too much criticism!

I thought it would be nice to call them galleries, although we'd be copying scratch :P

**Comment by towerofnix** [comment]
Not if we pronounce it "gale (rolling r) iez!"

**Comment by rumanti** [comment]
Galleries are awesome.
:point_up: _that's my vote!_

**Comment by matthewr6** [comment]
galleries +1

**Comment by towerofnix** [comment]
galleries +1

**Comment by matthewr6** [comment]
Galleries it is?  No disagreement?
@ElementalCode/programmers

**Comment by TheInitializer** [comment]
Collections?

**Comment by matthewr6** [comment]
OpenSprites much
I think we're going to be going with galleries

**Comment by TheInitializer** [comment]
But I like collections

**Comment by matthewr6** [comment]
just committed `class Gallery(models.Model)` so oh well
majority rule

**Comment by rumanti** [comment]
Such OpenSprites :blue_heart:

**Comment by PolyEdge** [comment]
ok yes!

galleries is the best name
