### ISSUE TITLE
<head> and <style> tags?

### ISSUE THREAD

**Issue by Tymewalk** [ElementalCode/elemental#175]
I think it might be a good idea to have those tags for things like CSS styling.

**Comment by matthewr6** [comment]
Yeah, we already do that - have you looked through the codebase yet?

**Comment by Tymewalk** [comment]
@Firedrake969 Where? I wasn't able to find anything.
Also, as far as I can see, the only tag like those is `<body>`.
I'm checking here, by the way: http://elementalcode.github.io/elemental/

**Comment by matthewr6** [comment]
oh _facepalm_ thought you were talking about the actual pages in the site, not the editor
xD
First, please go through and try to understand as much of the editor code as possible - AFAIK, I'm the only one who understands it right now (SOMEBODY PLEASE CORRECT ME!) which means I've done most of it :L 
Once you do that feel free to add stuff

**Comment by Tymewalk** [comment]
@Firedrake969 OK. That's the stuff under the branch "block-editor", right? Or is that some experimental thing?

**Comment by matthewr6** [comment]
Yup, you're right.

**Comment by matthewr6** [comment]
also no jquery allowed

**Comment by matthewr6** [comment]
Oh btw we don't want `<style>` tags because we're trying to encourage separate CSS files

**Comment by towerofnix** [comment]
Perhaps make a little pop-up bubble the first time the user drags out a `style` block?

> Inline styles are discouraged and stylesheet links should be used in favor of them.

(or something along the lines of that)

**Comment by Tymewalk** [comment]
@Firedrake969 I see. I'll take a look and see how to link stylesheets, I've only ever done it in-line.
@liam4 That sounds good, although you may just want to skip the `<style>` tag entirely and leave a note saying that stylesheets should be used instead.

**Comment by towerofnix** [comment]
What about [`scoped` `<style>`sheets](https://developers.google.com/web/updates/2012/03/A-New-Experimental-Feature-style-scoped?hl=en)?

Then again, there's [this](http://stackoverflow.com/questions/17667874/limit-scope-of-external-css-to-only-a-specific-element).

Makes me wonder why you need to use a `<link>` when you should be able to use a `<style src='/path/to/sheet.css scoped>`...

Regardless scoped stylesheets are interesting so.. what are we going to do with them?

**Comment by Tymewalk** [comment]
@liam4 Can CSS style sheets be included in Elemental as of now? If they can't, we should start with that before anything else.
My guess as to how Elemental works is it takes the block-code and translates it to HTML/CSS, then displays that on the preview screen. AFAIK scoped style sheets are very new and may not be supported by many browsers.

**Comment by PolyEdge** [comment]
Yeah, we don't want it to break on Chrome, IE, Edge, Safari, and Opera :P

**Comment by towerofnix** [comment]
That's very true! :P

**Comment by PolyEdge** [comment]
How about something like 
`
<link href="data:text/css;base64,YSB7IGNvbG9yOiByZWQgfQ==">
`

**Comment by Tymewalk** [comment]
@Dylan5797 Why base64? You could easily use `<link href="stylesheet.css">` (stylesheet.css is also created in the project), which is human-readable.

**Comment by PolyEdge** [comment]
Yes, but then we have to update stylesheet.css on the server

**Comment by PolyEdge** [comment]
Anyways, JavaScript will be modifying the style in the iframe, so that would be easier than recreating a css applier in JavaScript :package:

**Comment by PolyEdge** [comment]
So, here's my perception of what's going on:

```
'<link href="data:text/css;base64,YSB7IG...">'  <-------------------------- |CSS Rule| <-------- |CSS Rule|
              |
              |
+--------------------------+
|  </>                     |
|  hello world             |         < --------------------------------- <html tag> <-------------- <html tag>
+--------------------------+
```

**Comment by Tymewalk** [comment]
@Dylan5797 Oh, you're talking about the server. I thought we were talking about the project editor and how to get these blocks in there. (That's what the issue's about.)

**Comment by PolyEdge** [comment]
That's what I'm talking about too :P

**Comment by Tymewalk** [comment]
@Dylan5797 OK. But why would you have to update `stylesheet.css` on the server if it's in a project?

Here's what I'm talking about:
- User makes a new Elemental project.
- User creates a file called `stylesheet.css`.
- User goes to `index.html` and uses `<link href="stylesheet.css">`.
- The stylesheet is linked, and applied to `index.html`.

**Comment by towerofnix** [comment]
I think the issue is that the browser will try to look for a stylesheet.css file on the server, and because it isn't there, it won't load the CSS.

Rather what I think we need to do is have the base 64 be generated by the stylesheet.css "file" in the project, and pass that to the generated `link`.

In the export feature we would export it with the stylesheet.css file because obviously you would be hosting that on a server.

**Comment by towerofnix** [comment]
(maybe also planning and major tags?)

**Comment by PolyEdge** [comment]
``` js
document.getElementsByClassName('previewBody')[0].contentDocument.head.appendChild(...)
```

**Comment by Tymewalk** [comment]
@liam4 But aren't the project files in a separate folder (i.e, `project/*`), and then the `a` block links to `project/<FILENAME>`?

**Comment by matthewr6** [comment]
um
stylesheets can be included right now if that's what you're trying to figure out

**Comment by matthewr6** [comment]
http://prntscr.com/a9wxta

**Comment by Tymewalk** [comment]
@Firedrake969 Thanks, that was what we were trying to figure out.
I see no point in the `<head>` tag other than JS. (Side note: you may want to be careful with what JS you allow users to put, you might accidentally allow them to mess up the server.)
As for the `<style>` tag, stylesheets have been proven to be better.
I'm not sure where to go from here, if there's any point in adding either or not, so I'll leave this open.

**Comment by matthewr6** [comment]
The iframe is sandboxed already so there's not much chance for the JS to mess anything up :)

**Comment by PolyEdge** [comment]
... Nvm
