### ISSUE TITLE
Empty equals sign looks unaligned

### ISSUE THREAD

**Issue by Tymewalk** [ElementalCode/elemental#176]
See here:
![the one on the left is lower than the other one](http://i.cubeupload.com/lRBrMq.png)
There's a clear difference in where those slots are positioned.
However, this fixes itself when you add stuff to it (see full equals sign).

I tested on [this link from README.md](http://elementalcode.github.io/elemental/), where I found this issue.

**Comment by PullJosh** [comment]
What browser are you using? It looks fine on chrome...

**Comment by Tymewalk** [comment]
@PullJosh Firefox.
It looks like it only fixes when something on the left side is entered:
![note that when the right side is full, it re-aligns](http://i.cubeupload.com/6O3l3v.png)

**Comment by Tymewalk** [comment]
The left side is always aligned, but the right side isn't.
The recent commits to try and fix it didn't work. I'm trying to fix it now.
Would someone mind telling me where the code for the right side is?

**Comment by PullJosh** [comment]
> Would someone mind telling me where the code for the right side is?

https://github.com/ElementalCode/elemental/blob/block-editor/resources/css/blocks.scss#L160

**Comment by Tymewalk** [comment]
@PullJosh Thanks. I've downloaded a separate copy of the block-editor branch and I'm going to see if I can fix it.

**Comment by Tymewalk** [comment]
> > Would someone mind telling me where the code for the right side is?
> 
> https://github.com/ElementalCode/elemental/blob/block-editor/resources/css/blocks.scss#L160

@PullJosh Hmm... when I edit that file it doesn't change index.html. I tried making the background of the block a bright red, but it stayed orange.
Do I have to do something else to the script?

**Comment by matthewr6** [comment]
https://teamtreehouse.com/library/css-to-sass/installing-sass-and-setting-up-the-project/the-watch-command

**Comment by Tymewalk** [comment]
@Firedrake969 How do I install that on Linux?

**Comment by matthewr6** [comment]
Install Ruby
`gem install sass`

**Comment by Tymewalk** [comment]
@Firedrake969 Thanks, I have it and it works.

**Comment by matthewr6** [comment]
@Tymewalk how goes it?

**Comment by matthewr6** [comment]
Is this an issue still?  @ElementalCode/programmers

**Comment by TheInitializer** [comment]
yes

**Comment by mrjacobbloom** [comment]
I don't believe this is still an issue. If it is we can open this back up
