### ISSUE TITLE
can't register, i get a 404 error

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#18]

**Comment by matthewr6** [comment]
Register with username "testguy1000" and password "supersecurepassword", then screenshot what you get, please.  It works for me.

unless you can't go to /register
?

**Comment by an-OK-squirrel** [comment]
KK!

**Comment by an-OK-squirrel** [comment]
I got it to work earlier, and now register just brings me back to the main page :/

**Comment by matthewr6** [comment]
http://elementalcode-dev.herokuapp.com/register should work...  Unless you're already logged in, in which case it redirects.  If you're logged in, go to /logout so you can register another account.

**Comment by an-OK-squirrel** [comment]
Okay!

**Comment by an-OK-squirrel** [comment]
KK, works now.

**Comment by matthewr6** [comment]
Close this once everything's figured out :)

**Comment by an-OK-squirrel** [comment]
Everythings figured out :P

**Comment by an-OK-squirrel** [comment]
Can you check out my idea on #2
