### ISSUE TITLE
New frontpage logo not showing in Firefox and Edge

### ISSUE THREAD

**Issue by PolyEdge** [ElementalCode/elemental#181]
Apparently Firefox wants the image part on `<img>` tags to be targeted with `:before`! 

Fixing... :P

**Comment by matthewr6** [comment]
wait what o.o

**Comment by PolyEdge** [comment]
The new-frontpage-fixes branch is for that. Right now I have it working on FF, but I have no idea why it doesn't work on MS Edge.

**Comment by matthewr6** [comment]
Ok.
MS browsers are dumb.

**Comment by TheInitializer** [comment]
Still doesn't work on FF

**Comment by matthewr6** [comment]
Chrome is best

**Comment by TheInitializer** [comment]
> Chrome is worst

IKR?

**Comment by matthewr6** [comment]
> > Chrome is worst
> 
> IKR?

Yeah!

**Comment by ghost** [comment]
Lol. This fixes all cross-browser compatibility issues. http://codepen.io/balticllama/pen/jqWbRW

**Comment by matthewr6** [comment]
Love it.  Let's do it.

**Comment by TheInitializer** [comment]
> Lol. This fixes all cross-browser compatibility issues. http://codepen.io/TheInitializer/pen/ONMMaX

Ok, let's do it :D

**Comment by matthewr6** [comment]
Lolno

**Comment by PolyEdge** [comment]
Yay u used coral

**Comment by matthewr6** [comment]
@Dylan5797 please move the images from your domain into the staticfiles

**Comment by PolyEdge** [comment]
but i did

**Comment by PolyEdge** [comment]
the fix was in the invisible menu fix branch that i pushed

**Comment by matthewr6** [comment]
ok the other images too

**Comment by PolyEdge** [comment]
wut other images?

**Comment by PolyEdge** [comment]
http://prntscr.com/aek2mi

**Comment by matthewr6** [comment]
http://prntscr.com/aekbzv

**Comment by matthewr6** [comment]
actually disregard that those should be fine

**Comment by PolyEdge** [comment]
We don't need that icon anyway, I copied that directly from CodePen so that's why.

**Comment by matthewr6** [comment]
Yeah I figured once I actually looked :P

**Comment by PolyEdge** [comment]
lel

**Comment by PolyEdge** [comment]
Offtopic: does this work for you? https://scratch.mit.edu/projects/92555937/

**Comment by matthewr6** [comment]
You could do the 404 page... want me to assign it to you?

**Comment by PolyEdge** [comment]
Ok, doing it.

**Comment by PolyEdge** [comment]
And I see the request you sent in my server log ^.^

**Comment by matthewr6** [comment]
Your project works for me

**Comment by PolyEdge** [comment]
Thanks for testing!

**Comment by matthewr6** [comment]
np

**Comment by PolyEdge** [comment]
Sorry, I might take a while (got a new laptop and have to install django, flat, ruby, sass, git, etc.)

**Comment by matthewr6** [comment]
Cool, what type?

**Comment by PolyEdge** [comment]
Asus
16GB RAM
Intel i7 6700HQ 3.50Ghz
1TB hard drive
Backlit keyboard
Windows 10
WiFi 802.11ac
Bluetooth 3.0
15.5 inch across screen

Perfect for mass data-crunching and wireless webapps (and lego mindstorms nxt)

Too bad Windows 10 wrecked the preinstalled drivers.

**Comment by matthewr6** [comment]
:fuelpump: 
jealous

have fun reinstalling everything though lol

**Comment by PolyEdge** [comment]
I had to pay for it myself

I'm broke :money_with_wings:

**Comment by matthewr6** [comment]
oh lol, how much did it cost?

**Comment by PolyEdge** [comment]
$1500

**Comment by PolyEdge** [comment]
tax+shipping included

**Comment by PolyEdge** [comment]
because of the low Canadian dollar

**Comment by PolyEdge** [comment]
`</offtopic>`
http://codepen.io/Dylan5797/pen/GZpyVN

**Comment by matthewr6** [comment]
I like it.  Center the header, and maybe add some sort of image?

**Comment by PolyEdge** [comment]
> Center the header

But it won't match the rest of the site.

> maybe add some sort of image

Tomorrow. I'm on mobile.

**Comment by matthewr6** [comment]
Or maybe make it bigger, idk
