### ISSUE TITLE
Profanity filter development.

### ISSUE THREAD

**Issue by PolyEdge** [ElementalCode/elemental#183]
This is for the development of a filter to block out all:
- Foul language
- Sexually explicit language
- Mean Referrals to other users/entities
- Basic spam

I have a lot coded, the code contains a lot of language itself, so consider yourself warned :P

I haven't put it on GitHub yet, I plan to sometime next week.

This contains a lot of regex, is that ok?

If you have a thought about this, feel free to comment and I'll work on it, or you can do it yourself when I upload it.

Here's what is decided at the moment for prevention of spam and obscene content:
- Captcha for signup
- User account and user generated content reporting
- Basic filter for the bad stuff
- New unconfirmed account rank with limited capabilities (no image uploading, cooldown between posting stuff)
- Allow only moderated image hosts, like scratch does (plus ATers' servers :P)
- Spam server blacklist
- IP-ban users who post obscene content.

That's about all.

**Comment by towerofnix** [comment]
Should this be added to the Public Alpha milestone because it needs to be implemented before we release this to the public?

**Comment by PolyEdge** [comment]
Yeah.

**Comment by matthewr6** [comment]
So.
Who wants to display their profanity knowledge?

**Comment by ghost** [comment]
I'm actually somewhat conflicted on this. I realize that this is generally geared toward younger people, but if you look at a lot of web apps that handle user input, they opt not to filter, but encourage users to report inappropriate content instead. Anyone who really wants to get inappropriate content in will do it - by using obscure unicode characters or just uploading it in images. I guess you can sensor, but the better you want it to be, the more complicated it gets for limited return. Thoughts?

**Comment by matthewr6** [comment]
Oh hey!
I guess a simple filter wouldn't hurt too much, and it probably would at least discourage people.  After all, people will always be able to get around a filter, but it might help guide them regarding what's appropriate.

I'm more interested in finding a free API or Python package, actually - if there isn't one, I think just having reports (and possibly manually allow people to share content) should be fine.

**Comment by ghost** [comment]
Haha, hey. I haven't been on in a while, but I have a lot of free time again now that school's winding down. 
Yeah, I think it's a good idea to keep it simple. Constantly running a lot of regex against so much input would be  cumbersome on a larger scale. Maybe provide the option to report inappropriate content and in the user agreement, mention account termination for inappropriate content (if you haven't already).

**Comment by matthewr6** [comment]
Yeah, I'm pretty sure it's in the ToS (which was pieced together from different examples...).  Could everyone (@ElementalCode/programmers) review it again?

**Comment by matthewr6** [comment]
If anybody wants it:  (super condensed sorry)

> By using ElementalCode (the "Service") and its hosting site elementalcode.herokuapp.com (the "Site"), you agree to the following terms.  ElementalCode reserves the right to block and/or terminate your account without notice from the Site if the end user violates any of the listed terms.  You may not use the Service for anything illegal under United States and European Union law, including hosting or sharing illegal or illegally obtained files.  You may not save anything that may be considered NSFW (such as, but not limited to, sexually explicit content and vulgar language).  You agree to defend, indemnify and hold harmless ElementalCode from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password; b) a breach of these Terms, or c) Content posted on the Service.  In no event shall ElementalCode be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.  Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.  ElementalCode does not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.  We reserve the right to update these Terms of Service at any time without notification.

**Comment by ghost** [comment]
Hahaha I already read it. Yeah you're covered there. Maybe just censor the basics like [this list](http://www.bannedwordlist.com/lists/swearWords.txt).

**Comment by PolyEdge** [comment]
Here, I made a list of bad words to filter in base64:
https://gist.github.com/Dylan5797/78a43038f1a87b38e1fa

**Comment by PolyEdge** [comment]
> I'm actually somewhat conflicted on this. I realize that this is generally geared toward younger people, >but if you look at a lot of web apps that handle user input, they opt not to filter, but encourage users to >report inappropriate content instead. Anyone who really wants to get inappropriate content in will do it >- by using obscure unicode characters or just uploading it in images. I guess you can sensor, but the >better you want it to be, the more complicated it gets for limited return. Thoughts?

That's ok, but then a spambot could go on every profile and spam bad content all over the site, and it would take forever to clean up and give elemental a bad reputation. We need a "new scratcher" status, where you can only submit content every minute and no image uploads. Anyways, someone could connect to a proxy, spam accounts, and put up bad content all over the site. We need a filter, even if it isn't huge, it'll filter out those people who join services just to act obscenely.

Elemental would be a mess without one...

**Comment by PolyEdge** [comment]
And also I have one that I have spent hours on... :P

**Comment by ghost** [comment]
Captchas are really easy to implement, so spambots aren't that much of a problem.

**Comment by PolyEdge** [comment]
But someone could make them manually... Speaking of this, we need a spam server blacklist...

**Comment by ghost** [comment]
Right, but if you implement captchas in your sign up form, and for posting content, you'll mitigate almost all spambotting. Then, just provide a feature to report content as well as a basic profanity filter and you're good.

**Comment by PolyEdge** [comment]
Ok then, how's this?
- Captcha for signup
- User account and user generated content reporting
- Basic filter for the bad stuff
- New unconfirmed account rank with limited capabilities (no image uploading, cooldown between posting stuff)
- Allow only moderated image hosts, like scratch does (plus ATers' servers :P)
- Spam server blacklist
- IP-ban users who post obscene content.

**Comment by towerofnix** [comment]
Sounds good to me!

**Comment by ghost** [comment]
Yeah, I like all of that - especially moderated image hosts. By unconfirmed account, do you mean an account w/unconfirmed email address?

**Comment by PolyEdge** [comment]
I mean like a new account rank, like New Scratcher.

**Comment by matthewr6** [comment]
We would probably manually confirm accounts (at first, at least)

**Comment by PolyEdge** [comment]
That's going to be some extreme migrations for all the accounts registered now :package:

**Comment by matthewr6** [comment]
It's pretty close already so it should be fine
