### ISSUE TITLE
Css y u no work

### ISSUE THREAD

**Issue by TheInitializer** [ElementalCode/elemental#184]
https://elementalcode.herokuapp.com/projects/project/8

**Comment by matthewr6** [comment]
share it please

**Comment by TheInitializer** [comment]
It is shared

**Comment by matthewr6** [comment]
http://prntscr.com/abyjo8

**Comment by matthewr6** [comment]
shared it from the admin

**Comment by matthewr6** [comment]
k you have to do `href` not `src` just like in real HTML

**Comment by TheInitializer** [comment]
Oh whoops I didn't see the href so I assumed it was src

**Comment by matthewr6** [comment]
idk why we have `rel` there lol
