### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by BookOwl** [ElementalCode/elemental#19]
Scratch user <a href=https://scratch.mit.edu/users/infinitytec/>infinitytec</a> made us a logo:
![image](https://cloud.githubusercontent.com/assets/13385064/8783879/a034fcae-2eec-11e5-964c-ff6aaed0b9f9.png)
What do you guys think?

**Comment by matthewr6** [comment]
I think we should wait for @an-OK-squirrel's improvement.

**Comment by quat1024** [comment]
It's _okay_, I don't really like it that much tbh. I think it's the color scheme.

I'll give it a shot when I get home

**Comment by matthewr6** [comment]
Color scheme, text alignment, corners, and flatness.

**Comment by an-OK-squirrel** [comment]
Oh yeah, I did say I would make one.

**Comment by PullJosh** [comment]
I'll give it a shot too.

**Comment by PullJosh** [comment]
Here's my attempt:
![image](https://cloud.githubusercontent.com/assets/5458180/8791470/4f758e90-2f29-11e5-8f29-98886c74cb52.png)

**Comment by BookOwl** [comment]
I like yours, @PullJosh

**Comment by an-OK-squirrel** [comment]
That's great! I officially give up on mine :P

**Comment by an-OK-squirrel** [comment]
What did you use to make that?

**Comment by PullJosh** [comment]
[Paint.NET](http://getpaint.net/)

**Comment by TheInitializer** [comment]
I love yours pulljosh :3

**Comment by PullJosh** [comment]
I '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''d'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''o'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''n''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''t''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''. :P
(ftfy -even bettererererererr)

**Comment by an-OK-squirrel** [comment]
:P

**Comment by PullJosh** [comment]
WHO BE EDITING MY COMMENT THERE BOI

(Although I really don't like my own design.)

**Comment by matthewr6** [comment]
We will use it.
No disagreements.
c:

**Comment by PullJosh** [comment]
Oka'y. :P

**Comment by an-OK-squirrel** [comment]
We should add a BETA thing tho. :P

**Comment by matthewr6** [comment]
yeah

**Comment by an-OK-squirrel** [comment]
oh and btw https://github.com/ElementalCode/Elemental/wiki/WSF-Format

**Comment by an-OK-squirrel** [comment]
Now infinitytec is mad :P

**Comment by matthewr6** [comment]
lol

**Comment by an-OK-squirrel** [comment]
If he looks at the insults we made here he's gonna be really mad :P

**Comment by matthewr6** [comment]
what insults?

um, nobody link this :P 
(jk it's fine)

**Comment by an-OK-squirrel** [comment]
"flat", etc... It's critisism, but you never know how scratchers take things :P

**Comment by TheInitializer** [comment]
I know we already have a logo, but I was playing around and I have to say this kinda turned out pretty well:
![Elemental logo concept](http://i.imgur.com/Qcxxn2d.png)

**Comment by an-OK-squirrel** [comment]
Will use for my siggy, I like it better :3

**Comment by TheInitializer** [comment]
That was a screenshot, haven't exported it yet. :package: 
Here's a signature concept:
![Elemental signature concept](http://i.imgur.com/l6MXOUV.png)

**Comment by TheInitializer** [comment]
Oh and I can give you a SVG if you want - it's vector :3

**Comment by matthewr6** [comment]
I like it but the < is off and the block thing is both wrong (it's upside-down) and misleading (we don't have tabs) :P

also too tall for its width imo

**Comment by TheInitializer** [comment]
Why don't we have tabs :package: 
Just so it can look like a block lol

**Comment by matthewr6** [comment]
We discussed it when you weren't here and decided it was much lower priority

**Comment by TheInitializer** [comment]
but
![bad elemental logo](http://i.imgur.com/ffxGkZp.png)
doesn't look as good

**Comment by matthewr6** [comment]
well yeah because the text isn't vertically centered

**Comment by TheInitializer** [comment]
![still bad elemental logo](http://i.imgur.com/XYmqJRL.png)
still doesn't look as good

**Comment by matthewr6** [comment]
also the &lt; thing isn't vertically centered either :P

**Comment by TheInitializer** [comment]
well that's how it is in the font :P

**Comment by matthewr6** [comment]
do a separate font

**Comment by TheInitializer** [comment]
![still really bad logo ALL BECAUSE OF YOU FIREDRAKE](http://i.imgur.com/2YV4m8d.png)
still
it looks better with the bumps

**Comment by matthewr6** [comment]
at least do bumps on the bottom, not on the top, and make it shorter

**Comment by TheInitializer** [comment]
![better logo](http://i.imgur.com/zItgVA4.png)
huh... I like that

**Comment by matthewr6** [comment]
facepalm
tabs above and below!
http://prntscr.com/867tmh

**Comment by TheInitializer** [comment]
what
it's on the bottom
and it's shorter
what do you want

**Comment by matthewr6** [comment]
also
WAT
http://prntscr.com/867u28

**Comment by TheInitializer** [comment]
lol that's the text underneath
my mouse glitched when I was screenshotting
![](http://i.imgur.com/4My5Uk9.png)

**Comment by matthewr6** [comment]
let's let PJ make images?  :P  no offense, but I really like his

**Comment by TheInitializer** [comment]
pj's has bumps too

**Comment by matthewr6** [comment]
As normally as possible
I like PJ's bumps more

**Comment by TheInitializer** [comment]
PJ, how did you make your bumps

**Comment by matthewr6** [comment]
show me PJ's mentioned bumps again?  not sure what you're refering to tbh

**Comment by TheInitializer** [comment]
scroll up?

**Comment by matthewr6** [comment]
oh, look at my forum signature

**Comment by TheInitializer** [comment]
![image](https://cloud.githubusercontent.com/assets/5458180/8791470/4f758e90-2f29-11e5-8f29-98886c74cb52.png)

**Comment by matthewr6** [comment]
gtg for now...

**Comment by TheInitializer** [comment]
yeah I saw that one

**Comment by TheInitializer** [comment]
![Final new elemental logo](http://i.imgur.com/kBgbO5v.png)
Anyone else?

**Comment by an-OK-squirrel** [comment]
I like the one with only one bump......

oh well

**Comment by PullJosh** [comment]
Personally, I'm not a big fan. But I generally dislike anything I didn't make, soooo.....

**Comment by matthewr6** [comment]
I vote PJ.

**Comment by quat1024** [comment]
Well _I_ think it's great, but it's a little too tall, right? Sigs are
limited to 150px tall iirc, then it gets cut off.

Just for giggles, try flipping the gradient thing horizontally so it looks
"more" like a block (but then it might get in the way of the L hmm). I
don't think it really matters tho

<Pedantic> Move the tagline to the right 5px it's not centered!!!!!</Pedantic>

**Comment by TheInitializer** [comment]
@quat1024 
1) The size can easily be adjusted
2) It's supposed to be fading from a tag into a block :package: 
3) You mean to the left, right?

**Comment by quat1024** [comment]
1) Ye
2) But blocks have the bumpy part on the left :stuck_out_tongue: 
3) This way :arrow_right: 

4) I see the :P - to - :package: disease has got you too !!! oh no
5) I'm making a quick edit right now just to test things out myself. Just a bitmap edit with gimp
6) Why is this even a numbered list

EDIT I tried putting the block part on the left and it looks weird so hmm

**Comment by an-OK-squirrel** [comment]
:package:

**Comment by PullJosh** [comment]
@an-OK-squirrel Do you even tounge face? :package:

**Comment by quat1024** [comment]
:package: :package: :package: :package: :package: :package: :package: :package: :package: :package: :package: Whoops, I dropped my shipment of :stuck_out_tongue: faces :package: :package: :package: :package: :package: :package: :package: :package: :package: :package: :package: :package: :package: :package:

**Comment by towerofnix** [comment]
:package:

**Comment by TheInitializer** [comment]
@quat but it's more to the left than the right

**Comment by Cats-United** [comment]
@TheInitializer - quat is an (inactive) user.

**Comment by PullJosh** [comment]
@Cats-United What do you mean? He's on here all the time.

**Comment by quat** [comment]
Hello. I'm quat. I'm not in your project.

**Comment by matthewr6** [comment]
Hello quat.  People need to stop summoning random users.

**Comment by rumanti** [comment]
In other words, be careful with the "@" symbol. :stuck_out_tongue_winking_eye: 
You're quite lucky so far, none of the "random users" took this seriously.

**Comment by PullJosh** [comment]
I had no idea it sent messages to people. :P

**Comment by an-OK-squirrel** [comment]
I never do it...

**Comment by TheInitializer** [comment]
lol whoops
sorry quat

**Comment by quat1024** [comment]
So this is the guy that stole my username, huh? Had to think of a number to
stick on the end of my name when I signed up.

Hehe ;)

**Comment by Cats-United** [comment]
@quat1024 - quat joined after you.

**Comment by TheInitializer** [comment]
@Cats-United  exactly.

**Comment by quat1024** [comment]
I signed up a long time ago, never used the account, and changed the name about a month ago. Just FYI.

**Comment by Cats-United** [comment]
Okay then, that makes sense.
