### ISSUE TITLE
Should 404.html and other error code pages be at the base directory

### ISSUE THREAD

**Issue by PolyEdge** [ElementalCode/elemental#191]
Should 404.html be at base server directory (not at repo dir, but like
https://elementalcode.herokuapp.com/404.html

or something like 
https://elementalcode.herokuapp.com/static/error-codes/404.html

Or should it go in templates?

**Comment by matthewr6** [comment]
Anywhere in a `/templates/` dir

**Comment by PolyEdge** [comment]
kay
