### ISSUE TITLE
Managing Properties in HTML

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#2]
How do we want to deal with properties of objects?

My thought was to have infinite inputs, like in the join block from [Snap!](http://snap.berkeley.edu/)
![image](https://cloud.githubusercontent.com/assets/5458180/8759765/e416f5f4-2cca-11e5-924e-9cc41e29739d.png)

Each of these inputs would be "property  inputs", which could contain "property blocks". Each property block would have two inputs, and look something like this:
![image](https://cloud.githubusercontent.com/assets/5458180/8759804/435b07fc-2ccc-11e5-97bf-966f8b0ffe3d.png)
(Images created with Snap! custom blocks and "save scripts pic" in rt. click menu)

The only difference, though, would be that the first input in the property block ~~_could_~~ **must** be a dropdown.

**Comment by quat1024** [comment]
It would be super super cool if there was a [dropdown menu](http://scratchblocks.github.io/#%5Bclass%20name%20v%5D%20%5Bpost-container%5D%20%3A%3A%20operators%20reporter%0A%0A%5Bid%20name%20v%5D%20%5Bheader%5D%20%3A%3A%20operators%20reporter%0A%0A%5Bsrc%20v%5D%20%5Bhttp%3A%2F%2Fi.imgur.com%2Fw38SOrK.jpg%5D%20%3A%3A%20operators%20reporter%0A%0A%5Bhref%20v%5D%20%5Bhttp%3A%2F%2Fscratch.mit.edu%5D%20%3A%3A%20operators%20reporter%0A%0A%5Blang%20v%5D%20%5Ben-us%5D%20%3A%3A%20operators%20reporter) on the left half of the block (class, id, etc), but because of the sheer number of html attributes, how do we make the menu not fill the whole screen? There's a [loooooooooooooot](http://www.w3.org/TR/html4/index/attributes.html) of attributes in html.

**Comment by PullJosh** [comment]
Hmm... how about a searchable dropdown, that only shows up to, say, 10 items at a time. You can scroll through it like the scratch key press block dropdown, or you can type to filter out attributes. :D

**Comment by quat1024** [comment]
Yeahhhh

It would be sorted in alphabetical order, starting from the second page. The most commonly used ones would be on the first page too for easier access. :smile:

**Comment by towerofnix** [comment]
Make it so that the input is a text-dropdown so that you can type in it, say, `data-line-id`.

**Comment by PullJosh** [comment]
Like the list blocks in scratch (item [EPIC DROPDOWN] of list [bleh dropdown]), but searchable.

**Comment by matthewr6** [comment]
I've made searchable dropdowns before in HTML (React.js is amazing), but do we plan to use canvas or the dom?

**Comment by quat1024** [comment]
^ Good question

**Comment by matthewr6** [comment]
What does pixie use?
IMO, dom would be easier.

I think.

But if we do DOM, I would suggest that everybody play with Riot.js and React.js because they're really good for components (blocks, in this case) - especially Riot, since it's easier.

**Comment by PullJosh** [comment]
I'm not sure what's best, in this case, but DOM seems to make a bit more sense...

I'll check out Riot.

**Comment by quat1024** [comment]
> What does pixie use?

Some quick Inspect-Elementing tells me that pixie uses a separate <canvas> for every block, and absolutely-positions them in the DOM. http://imgur.com/j5edLt5

**Comment by matthewr6** [comment]
I vote using the DOM.

**Comment by PullJosh** [comment]
@quat1024 Huh... That's pretty neat, actually. Surprised it's still fast.

Ohwait. This isn't Scratch. Everything is fast.

**Comment by matthewr6** [comment]
lol
until you do any sort of database query on thousands to tens of thousands of entries.

**Comment by an-OK-squirrel** [comment]
Here's an idea! (I would help with stuff once you get going :P) 
![hahaha](https://cloud.githubusercontent.com/assets/12722625/8763832/f491ff18-2d75-11e5-9e87-5dfee6684704.png)

**Comment by an-OK-squirrel** [comment]
(bad drawing lelz)

**Comment by glacialcascade** [comment]
I like drop down idea

**Comment by an-OK-squirrel** [comment]
I bet you would like mine if I drew it in more than a minute :P

**Comment by matthewr6** [comment]
I like both :P

**Comment by an-OK-squirrel** [comment]
I feel mine would feel cleaner.

**Comment by matthewr6** [comment]
It certainly doesn't based on the drawing xD

**Comment by an-OK-squirrel** [comment]
xD

**Comment by PullJosh** [comment]
Will do original suggestion, with searchable dropdown for first input.
