### ISSUE TITLE
Job List

### ISSUE THREAD

**Issue by BookOwl** [ElementalCode/elemental#20]
This is a (incomplete) list of jobs and who is filling them:
- Backend/Server: Firedrake969, TheInitializer
- UI: PullJosh
- Frontend (actual ElementalCode frontend app): PullJosh, Firedrake969
- Compiler: Firedrake969
- Drag & Drop Blocks: Firedrake969
- Documentation: Airhogs777
- Creating and maintaining the job list: BookOwl

If there is a job that isn't in the list that should be added, please post it and I will add it.
Post the job(s) you want to do.

**Comment by matthewr6** [comment]
added Primary functionality, but not a very descriptive name.

**Comment by BookOwl** [comment]
So what should I call it? A list of jobs and people who are doing them?

**Comment by matthewr6** [comment]
No, "primary functionality" isn't descriptive :P

**Comment by BookOwl** [comment]
Well then what is?

**Comment by matthewr6** [comment]
Good question, can't answer it now though

**Comment by BookOwl** [comment]
I'm confused. What do you want me to do?

**Comment by matthewr6** [comment]
nvm, all good

**Comment by quat1024** [comment]
Uh, I'll do front end and design as well. But PullJosh is also doing that so idk.

**Comment by matthewr6** [comment]
PJ said that he wanted to do it alone iirc (but please correct me if I'm wrong)

**Comment by BookOwl** [comment]
If  PullJosh, and Firedrake969 are doing the front-end app, and Firedrake969 is doing the back end, what will the rest of us do?

**Comment by matthewr6** [comment]
It takes more than two for the frontend :P 
If anyone knows Django really really well they're welcome to help.
This means everything including migrations, querying, models, through model relationships, listviews, create/update/deleteviews, rest views, etc.  (@TheInitializer)

**Comment by TheInitializer** [comment]
Sure, I know Django really really well :P

**Comment by quat1024** [comment]
(@TheInitializer, if you reply to Github from your email, try not to quote the original email because it makes a bunch of gunk show up in your comment. I erased it for ya, but, just so you know :))

**Comment by TheInitializer** [comment]
Kk :P

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by matthewr6** [comment]
@TheInitializer's first comment
seriously...  how well do you know Django's
- rest APIs
- models/model fields
- other complicated stuff (can't think of them atm xD)

**Comment by an-OK-squirrel** [comment]
Nice job trying to summon your :P

**Comment by an-OK-squirrel** [comment]
I'd like to make the compiler (workspace to html)

**Comment by matthewr6** [comment]
Sure

**Comment by an-OK-squirrel** [comment]
Of course, I don't really know what I'm doing with File IO. I'll go do research :P

**Comment by BookOwl** [comment]
I would like to work on the front end JS side (turning the blocks into something that can be read back as a project and turned into HTML by @an-OK-squirrel, for example) I also wouldn't mind helping with the server, but I will have to learn django first.

**Comment by matthewr6** [comment]
I'd suggest you focus on what you're best at.

**Comment by BookOwl** [comment]
Signed up for Frontend.

**Comment by TheInitializer** [comment]
@Firedrake969 I know all of that stuff, I've been working with Django for a long time. :P

**Comment by matthewr6** [comment]
What OS are you on?  I'm trying to figure out how to get my Heroku Django app running locally on Windows, but it's hard since I've been developing on OS X.  I need to be able to make migrations.

**Comment by TheInitializer** [comment]
I'm on windows 8.1 :P

**Comment by PullJosh** [comment]
You're not the only one... :3

**Comment by TheInitializer** [comment]
Should I add myself to the OP?

**Comment by matthewr6** [comment]
yes
that makes three of us, PJ and TI

**Comment by BookOwl** [comment]
What's the OP?

**Comment by matthewr6** [comment]
Original Post

**Comment by TheInitializer** [comment]
“**o**riginal **p**ost”

**Comment by matthewr6** [comment]
**O**riginal **P**ost
ftfy

**Comment by TheInitializer** [comment]
y u no work ~~markdown~~email
ftfy
-fire
but i edited it and it's still the same
-init
lol
-fire
Hi guys ~ quat
hi
-init

**Comment by robinp7720** [comment]
I can help with the front-end and a little on the back-end. I havent done much with python but you gotta start somewhere :) I have made a few programs with python so don't worry :p I'm not a newbie at python.

**Comment by matthewr6** [comment]
If you already have experience with front end its probably best that you do primarily front end

**Comment by robinp7720** [comment]
I have done alot of back-end stuff but not with python.
Anyways, I don't mind front-end development

**Comment by matthewr6** [comment]
Python with Django is very different and much more powerful than PHP alone is

**Comment by PullJosh** [comment]
Add @robinp7720 for drag & drop blocks.

**Comment by matthewr6** [comment]
edit it yourself :P

**Comment by PullJosh** [comment]
Too much work. :3

**Comment by matthewr6** [comment]
Same

**Comment by mrjacobbloom** [comment]
I've been working on the documentation

**Comment by PullJosh** [comment]
Added. ;)

**Comment by an-OK-squirrel** [comment]
What do you guys want me to do since a library that FD969 found put me out of compiling?

**Comment by matthewr6** [comment]
Figure out how to translate blocks into JSON

**Comment by BookOwl** [comment]
What do you guys want me to do?

**Comment by matthewr6** [comment]
Drag/drop blocks?
(try to do this without IDs for each block...)

**Comment by BookOwl** [comment]
Ok, I start working on that.

**Comment by an-OK-squirrel** [comment]
> Figure out how to translate blocks into JSON

oh crap really
no

**Comment by BookOwl** [comment]
I'll do it!!!

**Comment by an-OK-squirrel** [comment]
k den xD

**Comment by infinitytec** [comment]
So what am I to work on?

**Comment by infinitytec** [comment]
So what am I to work on?

**Comment by an-OK-squirrel** [comment]
Why don't you....

**Comment by an-OK-squirrel** [comment]
I have no idea xD

**Comment by matthewr6** [comment]
You can work on the site design with @PullJosh (he had a Pen somewhere w/the FP of the main site, but we need more than a front page :P)

**Comment by infinitytec** [comment]
OK! Sorry for the double post. I was using an outdated version of Chromium on my Raspberry Pi. :P

**Comment by matthewr6** [comment]
np, removed the extra one
here's the issue on site design: #57

**Comment by infinitytec** [comment]
I'm working on it right now! Should I upload it to another branch (like homepage)?

**Comment by matthewr6** [comment]
yeah, also feel free to do other pages :)

**Comment by an-OK-squirrel** [comment]
and now firedrake took my job _again_

**Comment by an-OK-squirrel** [comment]
nice going

**Comment by matthewr6** [comment]
Sorry I like doing things when I have nothing to do

**Comment by PullJosh** [comment]
You can steal my job. _wink_ _wink_ _nudge_ _nudge_

**Comment by matthewr6** [comment]
hahaha no

**Comment by PullJosh** [comment]
![image](https://cloud.githubusercontent.com/assets/5458180/9151163/35187c40-3dc7-11e5-81b6-505360bbbd28.png)
Wonder how many people understood my name.

Also, you would be better at the one JS thing (dragging blocks out of palette) than I would. So you should do it. :P

**Comment by matthewr6** [comment]
Still at least make the palette so I can do the dragging

**Comment by PullJosh** [comment]
I still don't understand what you mean when you say "make the palette".

Also, made a fancy color scheme and posted on forums. Seems nobody has responded. :/

**Comment by matthewr6** [comment]
palette as in switching between categories and searching.

**Comment by PullJosh** [comment]
Oh, okay.

**Comment by quat1024** [comment]
I feel kinda afraid to work on this because I don't want to use an outdated version of the code/work on it at the same time as someone else and make a huge headache for when it needs to be merged in :stuck_out_tongue: 

Pointers?

**Comment by matthewr6** [comment]
Make a new branch and make sure (1) everyone knows what you're working on, (2) you actually work on it (so I don't take over because I'm bored/impatiant :P) and (3) make sure nobody else is actively working on it

**Comment by BookOwl** [comment]
Now what should I do? (since Firedrake took my old job...)

**Comment by an-OK-squirrel** [comment]
maintain the job list.

Nah, here's the perfect strategy:
1. Find something doable in 5 minutes
2. Do it.

**Comment by matthewr6** [comment]
Because anything longer means that I'll decide to take over :P

**Comment by an-OK-squirrel** [comment]
IDEA

I can help with block editor stuff

**Comment by an-OK-squirrel** [comment]
I guess that means it's time to git clone onto my laptop :package:

**Comment by matthewr6** [comment]
Updated to reflect who's done what.

**Comment by quat1024** [comment]
Should this be on the wiki somewhere? :P

**Comment by matthewr6** [comment]
Probably...
