### ISSUE TITLE
Why have angle brackets around body but no other elements?

### ISSUE THREAD

**Issue by towerofnix** [ElementalCode/elemental#201]
Just wondering..

![<body>, h1, </body>](https://cloud.githubusercontent.com/assets/9948030/13732677/95d342d6-e966-11e5-8b15-7014f443313b.png)

@PullJosh ping.

**Comment by matthewr6** [comment]
I vote remove them

**Comment by BookOwl** [comment]
And remove them from the doctype, too.

**Comment by towerofnix** [comment]
> And remove them from the doctype, too.

Along with the exclamation point, i.e. `<!DOCTYPE html>` -> `DOCTYPE html`, maybe?

**Comment by an-OK-squirrel** [comment]
yeah, i'd say remove the !

**Comment by PullJosh** [comment]
For doctype declaration, I'd say just have it say `document`

**Comment by iamunknown2** [comment]
@PullJosh that would make things inconsistent, as the "document" element would be the only one whose name is the one used in HTML. To put it in another way:
- h1 element: also h1 in ElementalCode
- img element: also img in ElementalCode

BUT
- DOCTYPE HTML declaration: not DOCTYPE HTML in ElementalCode, is document instead

**Comment by iamunknown2** [comment]
We should really publish some design guidelines, especially on how similar ElementalCode should be to HTML without sacrificing too much user-friendliness.

**Comment by iamunknown2** [comment]
We should remove the bottom </body> label, because it doesn't show up anywhere else.

BTW, I'm forking and making a pull request soon...

Edit: Just did. [Here](https://github.com/ElementalCode/elemental/pull/207). What do you guys think?

**Comment by iamunknown2** [comment]
Since it's been fixed, I'll close this right now.
