### ISSUE TITLE
Quickly add text to empty c-blocks

### ISSUE THREAD

**Issue by mrjacobbloom** [ElementalCode/elemental#205]
Obviously not for all of them, but some c-blocks will rarely contain anything besides text, so we might as well give empty c-blocks a button inside them to quickly insert a text block

Alternatively, we could fill them with text from the get-go.

**Comment by mrjacobbloom** [comment]
Here's a mockup of what I'm imagining:

![mockup of text quick-insert button](http://i.cubeupload.com/cnBlwX.png)
I call it aAa

**Comment by towerofnix** [comment]
I like the look of that!

I'm not sure I really like "Aa" as the placeholder text there though.. hmm..

**Comment by Tymewalk** [comment]
@Airhogs777 @liam4 Maybe `T` or `<e>`?

**Comment by mrjacobbloom** [comment]
Or just plain ol "txt"?

**Comment by Tymewalk** [comment]
@Airhogs777 That sounds good, but it might be too big.

**Comment by mrjacobbloom** [comment]
I picked Aa initially because there's no better standard symbol for text. It could just be a + sign tho.

**Comment by Tymewalk** [comment]
@Airhogs777 Oh, OK. I think then I agree - Aa would be best for some pre-initialized text. `+` is a little too generic.
@liam4 what do you think?

**Comment by towerofnix** [comment]
`Text`? :P

**Comment by mrjacobbloom** [comment]
> `Text`? :P

I dunno, sounds pretty risky.

**Comment by towerofnix** [comment]
> I dunno, sounds pretty risky.

How is it "risky"?

**Comment by iamunknown2** [comment]
Why don't we just make a quick hack by adding a text block inside the block (e.g h1) after the block in the block menu is picked up?

**Comment by matthewr6** [comment]
But what if people don't want it?

**Comment by Tymewalk** [comment]
@Firedrake969 Now I'm confused. If people might not want it, why have a text bubble in the first place?
At this point if they do they can always just drag it themselves.

**Comment by towerofnix** [comment]
Frequently people will want to have just text content for their block, but there will be times when people won't. So we make clicking on the bubble a quick but optional way to insert a text block.

**Comment by matthewr6** [comment]
^

**Comment by Tymewalk** [comment]
@liam4 Ah, I see.

**Comment by BookOwl** [comment]
How about we just make the bubble say "txt"?

**Comment by matthewr6** [comment]
I like `Aa` the best

**Comment by towerofnix** [comment]
I feel so assigned. o_O

**Comment by joker314** [comment]
As a non-developer, I like the `Aa` since it is short but to me I understand that it means "Text" (I like how ATM it can be a circle because the text is so short). I think that as soon as something is placed inside the C-block the button should disappear (but should re-appear when you drag the blocks out again). 

Sorry to intrude on your project,
jbs1

**Comment by mrjacobbloom** [comment]
Is this still in the works? I'd be down to take a stab at it.

**Comment by mrjacobbloom** [comment]
closing since we merged this in
