### ISSUE TITLE
Rendering of page one step behind text input in block editor

### ISSUE THREAD

**Issue by iamunknown2** [ElementalCode/elemental#206]
This could prove irritating, as I do not want to hit space then backspace every time after I finish typing in what I wanted to type into the text block in the block editor.

**Comment by towerofnix** [comment]
Yeah, I do find this pretty annoying.

**Comment by matthewr6** [comment]
yeah I know there's a way to fix it I just can't remember how lol
I always get this problem when dealing w/JS and text inputs

**Comment by towerofnix** [comment]
onkeyup? onkeyup -> setTimeout? Something like that :P

**Comment by mrjacobbloom** [comment]
Try the oninput event, it seems to work better for me.

**Comment by matthewr6** [comment]
# not settimeout

**Comment by iamunknown2** [comment]
Can anyone direct me to the code which controls when the rendering of the page occurs?

It seems to be controlled by either onkeyup or onkeydown.

**Comment by matthewr6** [comment]
Look for where the `setFrameContent` function is called.

**Comment by iamunknown2** [comment]
Uh... Which one should I work on? block-editor or gh-pages?

**Comment by iamunknown2** [comment]
OK. It was just a tiny change. All I needed to do was to change "keydown" to "input" somewhere.

It did take me ~15 minutes of scouring though :package:

I'll fork, push and make a pull request later. It's getting late where I live.

**Comment by matthewr6** [comment]
block-editor

**Comment by iamunknown2** [comment]
I've pushed the branch, I think.

**Comment by mrjacobbloom** [comment]
this seems to be resolved on gh-pages, it's just not pushed to heroku
