### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#21]
For when you don't need a whole issue.

**Comment by an-OK-squirrel** [comment]
First off, who has access to the heroku account?

**Comment by matthewr6** [comment]
Me, and it's a personal account.

**Comment by an-OK-squirrel** [comment]
Okay!!

**Comment by an-OK-squirrel** [comment]
NO offense, but why personal?

**Comment by matthewr6** [comment]
Because it has to have an email, and backend requires lots and lots of pushes that I can't test locally on Windows.

**Comment by an-OK-squirrel** [comment]
Ah, okay! :D

**Comment by matthewr6** [comment]
Make different issues for each question, so it's cleaner.

**Comment by quat1024** [comment]
Hmm. One one hand, it's not like we have a finite number of issues. On the other hand, I think a discussion topic like this would be great for quick questions. Hmm. I'll add a tag instead

**Comment by an-OK-squirrel** [comment]
Okay!

**Comment by an-OK-squirrel** [comment]
We should keep issues for planning and bugs. Not questions. That's why I made this :P

**Comment by quat1024** [comment]
Oh yeh that makes sense. So the "closed issues" list doesn't get filled up with "what's my username again" and "what is 2+2", but is a list of... closed _issues_. :stuck_out_tongue:

**Comment by an-OK-squirrel** [comment]
Yep!

**Comment by matthewr6** [comment]
So this is more like a chat channel?  :P

**Comment by quat1024** [comment]
It is now :P

OH Firedrake pls add TheInitializer to the Programmers group

**Comment by matthewr6** [comment]
Ok, what'll he be doing?

**Comment by quat1024** [comment]
Idk, he showed interest in backend stuffz in #20, and people not in the Programmers group can't push stuff, tag/close issues, or do anything really.

**Comment by matthewr6** [comment]
Ok
@TheInitializer
Just don't push anything direclty to the dev/staging/master branch - pull request first.

**Comment by matthewr6** [comment]
Everyone's accounts are deleted due to some issues - please note this may occur frequently.

**Comment by TheInitializer** [comment]
Is "hello" the main site? If not then what is? And why is it called "hello"?
Edit: It looks like a hello world program? What's it doing in here?
Edit 2: Oh wait, it's the main site.

**Comment by TheInitializer** [comment]
I'm a github n00b, sorry. How do I make a pull request?

**Comment by PullJosh** [comment]
To make pull request:
1) Create branch and push your code
2) Visit the branch's home page
3) Under the dropdown that states the current branch, there's a light grey colored bar. On the left of that is a "Pull Request" button.
4) _Don't_ accept your own request, even if you can - have someone else review your code first.

**Comment by matthewr6** [comment]
@TheInitializer 
Do you know how to set up a Django app and run `migrate`/`makemigrations` on Windows?

**Comment by TheInitializer** [comment]
@Firedrake969 I'm familiar with syncdb, its predecessor. I assume they aren't very different?
And yeah, I know how to set up an app and models and stuff

**Comment by matthewr6** [comment]
I just meant get an app running on `localhost`, and somehow getting virtualenv or something to be able to makemigrations and migrate (basically however you ran syncdb before, but a slightly different command)

**Comment by TheInitializer** [comment]
Ok then I can do that

**Comment by matthewr6** [comment]
yeah, how?  detailed instructions please?

**Comment by TheInitializer** [comment]
`manage.py startapp appname` creates an app, and then once you've made the changes to the models you run the `migrate` and `makemigrations` commands. I've never done it in a virtualenv though, but I don't suspect that would make a big difference.

**Comment by matthewr6** [comment]
What pip packages do you have to have installed?
(or just pip freeze and post it here)

**Comment by matthewr6** [comment]
I already have apps created (check out the dev branch, `projects` is one such app) but running `migrate/makemigrations` fails.  Could you try it out?

**Comment by TheInitializer** [comment]
fyi the command isn't `migrate /makemigrations`, migrate and makemigrations are two separate commands.

and sure I'll try it

**Comment by matthewr6** [comment]
I know, I was just doing a slash but was too lazy to put the extra two backticks in xD
Also, could you tell me what prints when you do pip freeze?

**Comment by TheInitializer** [comment]
I'm getting a `ImportError: No module named dj-database-url`. Is this the same error you get?
Edit: syncdb gives me the same result.
Edit 2: pip took care of that for me :P 
Now I get a error saying that postgre isn't installed (which it isn't). I'll install that now. (I normally use MySQL)

**Comment by matthewr6** [comment]
Ok, keep me updated please :)
(can't test for myself atm)

**Comment by PullJosh** [comment]
**n00b JS question...**
If I have this HTML:

``` html
<label class="paletteOptionWrap" for="p1">
  <input type="radio" name="palette" value="p1" id="p1" />
  Palette 1<span class="paletteColorIndicator" data-color="#0f0"></span>
</label>
```

and this JS (w/ jquery):

``` js
function loadPaletteColors() {
  for(i=0;i<$( ".paletteColorIndicator" ).length; i++) {
    $(".paletteColorIndicator:nth-of-type(" + String(i + 1) + ")").css("background-color", $(this).attr("data-color"));
  }
}
```

Why doesn't it set the background color of the element based on its data attribute?
(I feel like the answer is really obvious.)

**Comment by matthewr6** [comment]
Why not just use CSS if you're doing an attribute anyways?

**Comment by PullJosh** [comment]
Eh... I suppose inline CSS could be tolerated...

**Comment by matthewr6** [comment]
ew no use a class

**Comment by PullJosh** [comment]
A different class for each color?

**Comment by matthewr6** [comment]
True, nvm
But inline CSS is better than using jQuery just to set inline css xD

**Comment by PullJosh** [comment]
lol I suppose

**Comment by TheInitializer** [comment]
I only use inline css when I’m inspect-elementing a page, when I’m feeling lazy, or when I’m using wordpress or something 

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by matthewr6** [comment]
So you'd rather use jQuery to set inline styles, making another ugly layer of uglyness?  :P

**Comment by PullJosh** [comment]
No.

I just forgot to be intelligent.

**Comment by an-OK-squirrel** [comment]
Stupid question:
How do I get a personal version of the sever on mah computer so I can fool around with how django works?

**Comment by matthewr6** [comment]
No clue yet if you're using Windows

**Comment by an-OK-squirrel** [comment]
If I have django with python 3.4, how do I use it?

**Comment by TheInitializer** [comment]
@an-OK-squirrel use python 2.7 pls

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by matthewr6** [comment]
use python 2.7
also, fairly sure it's `python manage.py runserver 0.0.0.0:port` but I'm probably wrong since I haven't tested

**Comment by an-OK-squirrel** [comment]
Why?

**Comment by an-OK-squirrel** [comment]
I hate py2 :/

**Comment by TheInitializer** [comment]
Because it’s better.

**Comment by an-OK-squirrel** [comment]
NEVA

**Comment by TheInitializer** [comment]
yes

**Comment by TheInitializer** [comment]
py2 is the best

**Comment by an-OK-squirrel** [comment]
Do I need it for this? :P

**Comment by matthewr6** [comment]
you need to use 2.7 or else it won't work.  Especially since init and I are the primary backend devs and we're using it :3

**Comment by TheInitializer** [comment]
and that's what we're using so deal with it

**Comment by an-OK-squirrel** [comment]
kay den. D:

**Comment by TheInitializer** [comment]
dang it ninja'd

**Comment by an-OK-squirrel** [comment]
HAHAA

**Comment by an-OK-squirrel** [comment]
Okay, now that I use 2.7, whaddo I do?

**Comment by TheInitializer** [comment]
screw this I'm turning off email notifications my inbox is pretty much full

**Comment by an-OK-squirrel** [comment]
Hahaha :P

**Comment by matthewr6** [comment]
lol
also nobody push directly to dev if it deals with models.

**Comment by an-OK-squirrel** [comment]
Ik :P

**Comment by TheInitializer** [comment]
Kk

**Comment by TheInitializer** [comment]
manage.py runserver [port]

refixed by init

**Comment by an-OK-squirrel** [comment]
Okay!

**Comment by an-OK-squirrel** [comment]
I'm getting errors with those. :/

**Comment by an-OK-squirrel** [comment]
Ohwait nvm

**Comment by an-OK-squirrel** [comment]
What modules do i need for this?

**Comment by an-OK-squirrel** [comment]
ImproperlyConfigured: 'django_postgrespool' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    u'base', u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
Error was: No module named django_postgrespool.base

**Comment by matthewr6** [comment]
Go to the line in settings.py and comment out `database['ENGINE'] = something_goes_here_but_i_can't_remember`

**Comment by an-OK-squirrel** [comment]
Thx!

**Comment by an-OK-squirrel** [comment]
`DATABASES['default']['ENGINE'] = 'django_postgrespool'`
this?

**Comment by an-OK-squirrel** [comment]
Nope.

**Comment by an-OK-squirrel** [comment]
Python closed too fast, but it said "unkown something:"

**Comment by matthewr6** [comment]
@an-OK-squirrel 
Yes
You need Django installed, and possibly everything else (pip install -r requirements.txt)

**Comment by an-OK-squirrel** [comment]
oh okay

**Comment by quat1024** [comment]
Where's the UI folder? I can't find it in either the dev branch or master.

commit f61c485f49814ab4d2c377907165e51e5b2cf234 seems to have removed the ui folder?

**Comment by robinp7720** [comment]
@quat1024 https://github.com/ElementalCode/Elemental/tree/dev/apps/projects/templates

**Comment by quat1024** [comment]
Ok wow I'm dumb

**Comment by matthewr6** [comment]
Think we can automatically let admins and moderators share projects?

**Comment by BookOwl** [comment]
Why not?

**Comment by PullJosh** [comment]
**_BUT WHAT IF WE DON'T TRUST OURSELVES**_

...

...

Yeah that'd be fine.

**Comment by matthewr6** [comment]
k working on it

**Comment by BookOwl** [comment]
I trust myself...most of the time anyway :P

**Comment by matthewr6** [comment]
uh oh
I'll have to ban you now

**Comment by BookOwl** [comment]
LOL... I hope...

**Comment by matthewr6** [comment]
Django admin IS SO MUCH BETTER THAN PHPMYADMIN

**Comment by TheInitializer** [comment]
ikr
also firedrake, why do you have to specify an ip? I just put the port (I use 80 so I don't have to type the port number every time lol)

**Comment by matthewr6** [comment]
wait really?
cool
but now localhost:3000 is stuck in my browser's memory xD

**Comment by TheInitializer** [comment]
Lol

**Comment by matthewr6** [comment]
also django 1.8 tests are really really fast

**Comment by PullJosh** [comment]
Hasn't been used in 29 days.
