### ISSUE TITLE
I accidentally showed my email and real name in git

### ISSUE THREAD

**Issue by iamunknown2** [ElementalCode/elemental#211]
I'll rewrite history. However, you guys will have to re-clone the repository.

Sorry!

**Comment by matthewr6** [comment]
uh, what branch?  I understand that's a pretty big issue, but I'd rather not have it break everything for everyone...

**Comment by iamunknown2** [comment]
@Firedrake969 I pushed to gh-pages and the derivative branches of block-editor (block-editor-fix-delay, block-editor-intuitive-trash) so I had to rewrite the Git history for that.

**Comment by matthewr6** [comment]
Well, you shouldn't be pushing straight to gh-pages anyways...

Just be careful from now on - I don't want this to happen again, as whoever's working with those branches will likely have some problems.
