### ISSUE TITLE
Low-res trash image

### ISSUE THREAD

**Issue by iamunknown2** [ElementalCode/elemental#214]
I've tried tracing it in Inkscape, but it came up with a series of lines like this:

```
|
 |
  |
```

Instead of a straight line. Could the creator of this image provide an svg/image with a higher resolution

**Comment by matthewr6** [comment]
@PullJosh

**Comment by PullJosh** [comment]
[Trash Can.zip](https://github.com/ElementalCode/elemental/files/181248/Trash.Can.zip)
(Had to be a zip because github doesn't allow svg uploads.)

**Comment by iamunknown2** [comment]
Thanks.

**Comment by PolyEdge** [comment]
> (Had to be a zip because github doesn't allow svg uploads.)

Really? Weird.
