### ISSUE TITLE
Blocks render below the pallet

### ISSUE THREAD

**Issue by towerofnix** [ElementalCode/elemental#216]
Kind of annoying.

**Comment by iamunknown2** [comment]
Could you elaborate? I don't really get what you're saying.

Edit: Are you talking about the loading of something whenever you move a block?

**Comment by BookOwl** [comment]
I think he means that the when you drag blocks they go under the pallete.

**Comment by matthewr6** [comment]
Yeah, BookOwl's right, someone wanna fix that CSS?

(there are three Matthews on this organization lol - bookowl me and quat)

**Comment by Tymewalk** [comment]
@Firedrake969 Where's the code that handles that stuff?

**Comment by towerofnix** [comment]
I think you'd need to change [this](https://github.com/ElementalCode/elemental/blob/b3a4105e02d68b7a0474f0a19bf4456b4ecda6c3/apps/projects/static/css/editor/style.scss#L346-L355), in the SCSS.

``` scss
.upperArea .allBlocks .blockArea {
  // ...
```

**Comment by Tymewalk** [comment]
@liam4 OK.
So to fix this all we need to do is make the blocks render above the palette. Shouldn't be too hard.

**Comment by matthewr6** [comment]
Guessing just a z-index somewhere

**Comment by Tymewalk** [comment]
@Firedrake969 OK then.
I'll go take a look at how to do that.
(Go back 9001 layers, anyone?)

**Comment by Tymewalk** [comment]
This may help, by the way: http://www.sitepoint.com/better-solution-managing-z-index-sass/
