### ISSUE TITLE
(Not a Real Issue) Possible way to join?

### ISSUE THREAD

**Issue by skistaddy** [ElementalCode/elemental#223]
Hey guys! Is there some way I could possibly join this group? Is there a Scratch forum topic or something? I was also thinking we could possibly collaborate, as I'm the owner of [Newawe](https://github.com/Newawe), a code sharing website. Please consider, and thanks for reading. (P.S. THIS IS THE COOLEST THING I'VE EVER SEEN!!!)

**Comment by matthewr6** [comment]
What languages are you competent in?  Any examples of work you've done?  (specifically you, not just a project you're managing - so far we've been fine in that regard)

**Comment by skistaddy** [comment]
@Firedrake969 I'm very fluent in HTML, CSS, JavaScript and Python. I know Node.js and SQL. And enough PHP to get me by. I made [`Trap.js`](https://github.com/bjskistad/trapjs), a JavaScriot function library. (With very few additions by other collaborators.) I'm making a Scratch favorite sensor, by myself. https://github.com/bjskistad/scratch_love_and_favorite_sensor

**Comment by towerofnix** [comment]
Isn't Trap.js just a big file with a bunch of aliases for various functions? Why use the aliases when I could just use the normal functions?

(Maybe I should open up an issue on the trap.js repo..)

**Comment by skistaddy** [comment]
We've added a bunch of new functions... Such as a cookie maker and some Ajax commands.

**Comment by matthewr6** [comment]
The cookie maker seems copied from [here](http://www.w3schools.com/js/js_cookies.asp) - might want to credit it if it is ;)

I think we're good for now, but feel free to make pull requests and ask what needs to be done.  If you make good contributions via PRs, we'll definitely consider asking you to join the organization.

**Comment by skistaddy** [comment]
Okay! Yeah, they look pretty similar. I do a lot to browsing on that site. I don't remember finding it there. XD But I will give credit.

What does need to be done?

**Comment by matthewr6** [comment]
@bjskistad #218

**Comment by towerofnix** [comment]
Anything in [/issues](https://github.com/ElementalCode/elemental/issues)? :P
