### ISSUE TITLE
Editor Text Block

### ISSUE THREAD

**Issue by skistaddy** [ElementalCode/elemental#224]
It is not updating to the current text.
![script](http://imagizer.imageshack.us/v2/252x198q90/921/L7AYMN.png)
Any idea on how to fix?

**Comment by towerofnix** [comment]
Works for me on https://elementalcode.herokuapp.com/projects/editor as well as on http://elementalcode.github.io/elemental/ -- anything appear in the console?

**Comment by skistaddy** [comment]
Hmm... It isn't updating the HTML viewer. I'll try again later. :P

**Comment by iamunknown2** [comment]
Not working for me (the guy who wrote the fix) as well. Hmm...

**Comment by matthewr6** [comment]
http://prntscr.com/aov0p9
Not quite sure why yours has angle brackets - are you using a local copy that's outdated?

**Comment by towerofnix** [comment]
What web browsers are you guys using? I'm on Firefox 48, and it works for me.

**Comment by matthewr6** [comment]
Chrome something

**Comment by towerofnix** [comment]
> Not quite sure why yours has angle brackets - are you using a local copy that's outdated?

Probably they're using https://elementalcode.herokuapp.com/ ?

**Comment by skistaddy** [comment]
Yeah, that URL that Liam said and I use chrome.

**Comment by towerofnix** [comment]
You should be using http://elementalcode.github.io/. Also, both editors work for me running Chrome 51.

**Comment by matthewr6** [comment]
Chrome (I assume 51) on Windows for me and OS X for liam... what OS are you using?

also 

> http://prntscr.com/aov0p9
> Not quite sure why yours has angle brackets - are you using a local copy that's outdated?

**Comment by towerofnix** [comment]
> also

They're using https://elementalcode.herokuapp.com/ which hasn't been updated yet.

**Comment by skistaddy** [comment]
I used your link and it didn't work. :/

**Comment by BookOwl** [comment]
@bjskistad which link?

**Comment by matthewr6** [comment]
@liam4 Oh ok I'll get around to updating that....
maybe....

**Comment by iamunknown2** [comment]
It doesn't work on Firefox...

**Comment by skistaddy** [comment]
@liam4 It updates when I click outside of the block on the workspace, but not when I'm typing.

**Comment by matthewr6** [comment]
Please give your chrome version.  Is this on the github pages site?

**Comment by skistaddy** [comment]
Yes it is on the GH pages.I believe this is my OS: ChromeOS 7834.70.0 The other one looks like my IP.

**Comment by skistaddy** [comment]
I'm using chrome: Chrome 49.0.2623.112

**Comment by matthewr6** [comment]
Works for me, exact same version of Chrome.  Are there any console errors?

**Comment by skistaddy** [comment]
Lemme check...

**Comment by skistaddy** [comment]
I got your guys' logo then this: `ncaught TypeError: Cannot read property 'addEventListener' of null`

**Comment by matthewr6** [comment]
What line?
A screenshot of the console would be nice

**Comment by skistaddy** [comment]
K.

**Comment by skistaddy** [comment]
http://imgur.com/qtdDLD8

**Comment by matthewr6** [comment]
Should be fixed - make sure to clear your cache

**Comment by skistaddy** [comment]
K.

**Comment by skistaddy** [comment]
Nope, wasn't fixed.

**Comment by matthewr6** [comment]
Please show your console again, then - that's more helpful than just "wasn't fixed"
I'm going to leave this closed until anybody but you can replicate it, though... because it seems to be a unique occurrence based on what others have said

**Comment by skistaddy** [comment]
Nothing wrong with it.

**Comment by matthewr6** [comment]
What do you mean?

**Comment by skistaddy** [comment]
No errors.

**Comment by matthewr6** [comment]
But... it still doesn't work?  @ElementalCode/programmers guys please confirm then

**Comment by TheInitializer** [comment]
By this I assume you mean updating the preview as you type? If so it works for me on both versions (Firefox Developer Edition 48.0a2 with e10s on windows 10 64-bit)

**Comment by skistaddy** [comment]
Yes. Doesn't work for me though.

**Comment by matthewr6** [comment]
It works for me on both versions too... Latest Chrome, and windows 10

**Comment by matthewr6** [comment]
@TheInitializer if only one person has reported it and it's not reproducible by anyone else I'm going to close it for now

**Comment by skistaddy** [comment]
Lucky...

**Comment by matthewr6** [comment]
Did you clear your cache?

**Comment by TheInitializer** [comment]
^^

**Comment by skistaddy** [comment]
YES I DID. I CLEARED MY WHOLE CACHE AND IT DIDN'T WORKED.

**Comment by matthewr6** [comment]
No need for all caps.

http://elementalcode.github.io/elemental/resources/js/blocks.js
Please do a search for `'keydown'` and see if there are any results in the file.

**Comment by towerofnix** [comment]
No results for me.

**Comment by TheInitializer** [comment]
nope
