### ISSUE TITLE
Tutorial Section

### ISSUE THREAD

**Issue by quat1024** [ElementalCode/elemental#23]
If the goal of Elemental is to be accessible to people who are interested in web design but know nothing about HTML, we're going to have to show them the ropes :smile:

We'll need a couple of simple example webpages, some more complex projects, and a step-by-step guide area (like Scratch's "help" pullout) at _least_.

Tell me what you think :)

**Comment by matthewr6** [comment]
Agreed, but we have to build the thing first ;)

**Comment by quat1024** [comment]
Yay for the "Planning" tag :heart:

**Comment by TheInitializer** [comment]
[We need Joyride!](http://foundation.zurb.com/docs/components/joyride.html)

**Comment by PullJosh** [comment]
That would be cool. :D

**Comment by PullJosh** [comment]
But it should be an optional thing - not something that's shoved down a user's throat (make it obvious that it's an option, but don't start the tutorial as soon as the open their first project.)

**Comment by matthewr6** [comment]
definitely :P

**Comment by rumanti** [comment]
Don't follow Tynker's path. :P

**Comment by TheInitializer** [comment]
lol you mean the $50 ripoff of scratch?

**Comment by matthewr6** [comment]
Yeah
And not joyride because jQuery

**Comment by an-OK-squirrel** [comment]
Sorry I haven't been doing anything, busy with ludum dare

**Comment by matthewr6** [comment]
user pages please

**Comment by an-OK-squirrel** [comment]
I'm done with LD becuase I gave up early so I'll do it :P

**Comment by PullJosh** [comment]
Here's an interesting site about first-time user experiences (essentially what we're trying to figure out here). Probably worth a read. ;)

http://firsttimeux.tumblr.com/

**Comment by infinitytec** [comment]
I can work on this (once we have more...).

**Comment by matthewr6** [comment]
I'd prefer we do pages first because there's a lot of stuff in the editor that's not stable at all

**Comment by PullJosh** [comment]
Of course! I just found the article and wanted to share it before it was lost. ;)

**Comment by matthewr6** [comment]
IK, that was meant for infinity because he asked what to do :P

**Comment by PullJosh** [comment]
Oh. :3

**Comment by TheInitializer** [comment]
remind me why we can't use jquery?

**Comment by PullJosh** [comment]
Slow page loads & spaghetti code.

**Comment by matthewr6** [comment]
http://lea.verou.me/2015/04/jquery-considered-harmful/

**Comment by towerofnix** [comment]
Honestly the only thing I use jQuery for is `$.ajax` which I should probably just be using promises and `XMLHTTPRequest`s..

**Comment by TheInitializer** [comment]
yeah [jquery's pretty overrated](http://needsmorejquery.com)... but everyone uses it for everything, that's the thing

**Comment by matthewr6** [comment]
"everyone"?  "everything"?

**Comment by TheInitializer** [comment]
we need https://github.com/usablica/intro.js

**Comment by matthewr6** [comment]
+1

**Comment by TheInitializer** [comment]
No jQuery in this one :dancer:

**Comment by TheInitializer** [comment]
Oh wow lol, I tried typing :D and it came out as :dancer: 
:dancer:  is the new :package: :P

**Comment by matthewr6** [comment]
what o.o

**Comment by PolyEdge** [comment]
Shift Semicolon D Return = :dancer:

**Comment by liam4** [comment]
o_O :dash:

**Comment by TheInitializer** [comment]
@Dylan5797 enter*

**Comment by matthewr6** [comment]
reentry
IN A GIANT BALL OF FIRE

**Comment by PolyEdge** [comment]
Boom

**Comment by matthewr6** [comment]
@Airhogs777 I think you volunteered to do this on the forum thread

**Comment by mrjacobbloom** [comment]
yes I did haha

**Comment by matthewr6** [comment]
so basically go crazy with it I guess

**Comment by TheInitializer** [comment]
usablica/intro.js

**Comment by mrjacobbloom** [comment]
live demo, lemme know if you have any feedback before I try to figure out pull requests: https://intro-airhogs777.c9users.io/elemental/index.html?tutorial=true

**Comment by towerofnix** [comment]
Looks pretty cool!

It glitches out if I've previously got the palette scrolled or if I press enter when I'm not supposed to. It'll also completely close the tutorial if I press escape - could it be possible to restore the tutorial maybe?

**Comment by mrjacobbloom** [comment]
Yes the scrolling issues are something I've been struggling with for hours :package: -- that's why I decided to give it its own URL where it runs immediately, it makes it harder for the user to screw it up haha. As for restoring the tutorial, it shouldn't be too hard to track your place in case you accidentally exit

**Comment by TheInitializer** [comment]
Looks great! Quick question: why is the default text still breadfish.gif?

**Comment by mrjacobbloom** [comment]
@liam4 I think I fixed the scroll issues and removed keyboard commands entirely (except enter, I can't figure out how to get rid of it, I think it's a tabindex thing that needs to be there for accessibility)

**Comment by mrjacobbloom** [comment]
oh wait, in the OP @Firedrake969 said we should have a bunch of 'em. I'll start working on a system to load tutorials more on-demand-like.

**Comment by matthewr6** [comment]
Because breadfish.gif is amazing

**Comment by mrjacobbloom** [comment]
> Because breadfish.gif is amazing

could it be the default img src? I feel like having a filename as the default text is confusing

**Comment by BookOwl** [comment]
Default text ideas:
- Hello, World!
- I <3 breadfish
- Hello, Elemental!
- Content goes here.

**Comment by matthewr6** [comment]
I don't even know why it's breadfish.gif right now lol

**Comment by towerofnix** [comment]
I think we should just use `Breadfish`. :P

**Comment by matthewr6** [comment]
K

**Comment by TheInitializer** [comment]
what is breadfish

**Comment by matthewr6** [comment]
Turn up your volume
http://www.breadfish.co.uk/

**Comment by mrjacobbloom** [comment]
I have no idea how to get my changes back to you guys, I'm pretty sure I accidentally forked the branch... can I just email one of you a zip of my repo :disappointed:

**Comment by matthewr6** [comment]
Forking the branch is a good thing!
Of course, that means you didn't (:P jk sorry I'm being mean) but do you even git?

Yeah go ahead and upload it somewhere or something

**Comment by mrjacobbloom** [comment]
NO I DON'T GIT :rage: (jkjk) C9 lets you clone repos but not SSH back into the master branch or whatever without a paid account.

https://drive.google.com/file/d/0BwLpMm1gMerELUVweWlJMmlGT2s/view?usp=sharing
the only existing file that needs to change is index.html, which needs the new line `<script src="resources/js/elemental-intro.js"></script>` in the head somewhere. The other new files are
- resources/css/intro.css
- resources/js/elemental-intro.js
- resources/js/intro.min.js
- resources/js/tutorials/1.js and 2.js

and adding `?tutorial=[tutorialnumber]` to the URL loads the tutorial.

**Comment by towerofnix** [comment]
> NO I DON'T GIT :rage: (jkjk) C9 lets you clone repos but not SSH back into the master branch or whatever without a paid account.

C9 as in [c9.io](https://c9.io/)?

Why you no `git`? :package:

**Comment by mrjacobbloom** [comment]
> Why you no git? :package:

mostly because new CLI's scare me until someone has explicitly walked me through everything I'll ever need to do, and git has a lot of things to do. And I can't use the github desktop app 'cause I'm on 10.8

**Comment by matthewr6** [comment]
There are only like 10-ish commands you need to know if you want me to write about the ones I use

**Comment by mrjacobbloom** [comment]
That would be cool

**Comment by iamunknown2** [comment]
Cloning repo to PC:

```
git clone (URL here)
```

Staging (including) your changes:

```
git add -A
```

Committing your changes (last step before uploading)

```
git commit -m "(insert description of changes)"
```

Uploading your changes:

```
git push origin (name of branch you want to push to)
```

Switching branches:

```
git checkout (name of branch)
```

Making new branch and switching to it:

```
git checkout -b (name of branch)
```

Getting log of changes (current branch only):

```
git log
```

**Comment by iamunknown2** [comment]
To elaborate...

```
UNSTAGED CHANGES >> git add -A >> UNCOMMITTED CHANGES >> git commit -m >> OFFLINE CHANGES >> git push origin (branch name)
```

For misc:

```
BRANCH1 >> git checkout -b BRANCH2 >> BRANCH2 (new branch)
BRANCH1 << git checkout BRANCH1 << BRANCH2

git branch:
BRANCH1 *
BRANCH2

* = You are here
```

**Comment by mrjacobbloom** [comment]
Has anyone merged those changes in yet? I don't see them anywhere and it's stressing me out... _please_ don't make me figure it out on my own :pray:

**Comment by mrjacobbloom** [comment]
I can git now. If y'all are still interested I can add this in myself

**Comment by matthewr6** [comment]
Ok, git on it

...I'm so funny right

**Comment by PullJosh** [comment]
> Ok, git on it
> 
> ...I'm so funny right  

Next New Years, you should commit to gitting a life. Your puns are so repolsive, I feel the need to push you to prove that I am the master. You better branch away from the bad jokes or I'll have to resolve this conflict myself.

**Comment by mrjacobbloom** [comment]
Ok #231

**Comment by towerofnix** [comment]
Well, it's been a year! Glad to see progress on this! :shipit:

**Comment by mrjacobbloom** [comment]
Tutorials have been implemented for a while now
