### ISSUE TITLE
Pasting Text

### ISSUE THREAD

**Issue by lholliger** [ElementalCode/elemental#235]
i pasted an image address from my website onto the src box for img, and the font was not the same, can you make the font the same for the project and ctrl-v?

**Comment by matthewr6** [comment]
The font in the input probably won't be the same - but it should be the same throughout all other block inputs.  Did the image work?

**Comment by mrjacobbloom** [comment]
Is there something we can do about that? Can you limit contenteditable to a certain font?

**Comment by matthewr6** [comment]
It should have a uniform font... @DatOneLefty Do you have screenshots?

**Comment by mrjacobbloom** [comment]
The way we designed the inputs allows for all sorts of formatting that we don't necessarily want. And it's hard to remove:

http://stackoverflow.com/questions/3553092/paste-only-plain-text-into-editable-div
http://stackoverflow.com/questions/7207291/is-it-possible-to-disable-or-control-commands-in-contenteditable-elements
http://stackoverflow.com/questions/6899659/remove-formatting-from-a-contenteditable-div

...it shouldn't break anything to have this kind of extra formatting, but it's visually inconsistent

**Comment by mrjacobbloom** [comment]
(the reason we used contenteditable is so the inputs expand as text is entered)

**Comment by joker314** [comment]
If you want inputs to expand would it not be possible to use a bit of JS to change the width when a key is pressed or the input changes or something?

**Comment by mrjacobbloom** [comment]
All the ways to do that are hacky and inconsistent. I feel like we looked at a bunch of ways to do expanding text boxes and decided this was the best option

**Comment by joker314** [comment]
Could you do an "on-key-up" for the input box and get some JS to strip HTML tags generated by the browser and uniform the fonts?

**Comment by mrjacobbloom** [comment]
Hm... we might be able to do something like that. I'll look into it when I get the chance

**Comment by matthewr6** [comment]
We looked into that, IIRC, but it turned into a number of listeners that would scale linearly with the number of inputs.  I'm not against it, but do we know how efficient that would be?

**Comment by joker314** [comment]
Perhaps using `onfocus` to add the event listener and `onblur` to remove it? Does that save memory?

**Comment by matthewr6** [comment]
Possibly

**Comment by matthewr6** [comment]
Ok, found it - this is how we do a single, global event listener.  https://github.com/ElementalCode/elemental/blob/gh-pages/resources/js/blocks.js#L313

**Comment by mrjacobbloom** [comment]
yeah that'll work. The `input` event seems to run on paste. I'll write a patch when I get home

**Comment by joker314** [comment]
Ok :)

**Comment by mrjacobbloom** [comment]
closing for now
