### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#24]
What browsers should we support? If we support Chrome, Firefox, Opera, Safari, and IE9, is that enough? Do we need to support versions of IE lower than 9? (I would hope that anyone making webpages wouldn't be using IE...)

**Comment by matthewr6** [comment]
IE 10 or 11+

**Comment by PullJosh** [comment]
11+

**Comment by quat1024** [comment]
We should start by supporting the easiest browsers (so probably Chrome and
FF) & branch out from there after we're done.

**Comment by matthewr6** [comment]
I once encountered a CSS bug that worked on Chrome and IE 11 but not Firefox, so...
xD

**Comment by PullJosh** [comment]
lolwut

**Comment by BookOwl** [comment]
I would say focus on chrome, firefox, and IE 10+

**Comment by TheInitializer** [comment]
I say focus on Firefox, Chrome, and Opera 15+ (based on Chromium), then branch out to Safari, IE11 and MS Edge, then if we feel like it go to IE9 and 10.

**Comment by PullJosh** [comment]
For now, I'll make things work on **Chrome, Firefox, Opera 15+, IE 10+, and Safari (newest version)**.

Mobile (responsiveness) shouldn't really be important for this project.

**Comment by matthewr6** [comment]
If we make things work for Chrome and IE, things should work in general, I think

**Comment by PullJosh** [comment]
Yeah.

**Comment by TheInitializer** [comment]
yeah, if it works on chrome it usually works on firefox too.

**Comment by PullJosh** [comment]
Except when you're applying an ios-style shake effect to text inputs using jquery when users do something wrong.

... Personal experience.

**Comment by amishshah** [comment]
Just ditch IE support altogether. Don't worry about IE, it's time to let it die.

**Comment by an-OK-squirrel** [comment]
Yes

**Comment by an-OK-squirrel** [comment]
We don't  want the people learning html to deal with support themselves

**Comment by matthewr6** [comment]
Still think at least IE 11+.  Then at least it'll make them learn to stop using IE :P 
Even so, as long as we build it, it should work unless we use some browser-specific stuff (which we shouldn't anyways...)

**Comment by alyssarosenzweig** [comment]
The only browser worth supporting is netcat.

Or, if you're feeling slightly less masochistic, maybe support lynx.

But seriously, I agree with @hydrabolt

**Comment by PullJosh** [comment]
Unfortunately, netcat doesn't appear to support flexbox, so that won't be an option. :(

**Comment by matthewr6** [comment]
Did you read what I said?
As long we don't use any super esoteric browser features, we'll be good

**Comment by alyssarosenzweig** [comment]
@Firedrake969 That's not a given really; [CSS3 animation](http://caniuse.com/#feat=css-animation) isn't really "esoteric".

**Comment by PullJosh** [comment]
It's just vendor prefixes and things - should we include microsoft filters and stuff?

**Comment by matthewr6** [comment]
So IE 11 or up doesn't support CSS animations?

**Comment by matthewr6** [comment]
Just do a mix in that auto prefixes for you

**Comment by PullJosh** [comment]
Okay, cool!

How about browser support for the code exported by Elemental?

**Comment by matthewr6** [comment]
Don't care - it's theirs, let them do what they want

**Comment by PullJosh** [comment]
But in terms of auto-prefixing and things.

Also, should we let them know what browsers their sites will work in?

**Comment by PullJosh** [comment]
(ex. If they make a gradient, should it be auto-prefixed? If so, which browsers?)

**Comment by matthewr6** [comment]
All prefixes?

**Comment by PullJosh** [comment]
And what about in terms of telling them if they're using experimental/unsupported features?

**Comment by matthewr6** [comment]
We should probably just leave those out.

**Comment by matthewr6** [comment]
Ok, added a mixin for vendor prefixes
