### ISSUE TITLE
Mention quicktext button in tutorial?

### ISSUE THREAD

**Issue by towerofnix** [ElementalCode/elemental#246]
I'm not sure what the best way to do this is, maybe in a second part of the tutorial (so users can get familiar with the text block)?

**Comment by towerofnix** [comment]
(Also idk if frontend is a good label or not)

**Comment by matthewr6** [comment]
@Airhogs777

**Comment by mrjacobbloom** [comment]
Yeah, I was planning on updating the tutorial once we got the quicktext button merged in. I'll do it eventually 📦

**Comment by matthewr6** [comment]
wait when did I assign you

**Comment by matthewr6** [comment]
odd

**Comment by mrjacobbloom** [comment]
It assigned me and added the label as soon as I mentioned it in a PR
