### ISSUE TITLE
Rework Blocks Code

### ISSUE THREAD

**Issue by mrjacobbloom** [ElementalCode/elemental#248]
I guess we're back at it! Copied from [forum](https://scratch.mit.edu/discuss/topic/247667/?page=1#post-2542522):

> Something I never loved about how Elemental was structured was that the code that makes blocks is kinda flimsy (no offense FD), like a block is just some HTML elements with some event listeners on them. Compare it to Blockly, which has gorgeous constructors and blocks are actual objects. I'd love to overhaul the blocks if we're picking this back up

> The issue was probably that the dragging was developed first and I made the dragging too tightly coupled to the actual parsing logic… I might be interested in refactoring it actually
>stream of consciousness stuff
>> have some data structure to keep track of blocks maybe a dict/hash map with md5 hashes correponding to block ids and then ondragcomplete on the block update the position and (if applicable) where it is in a given block stack, relative to a specific preceding id that way the dragging would just be a way to modify the internal structure instead of having the external structure be the defining data
somehow store block stacks in possibly another dict/hash map with keys of the id of the top block so that way we can combine stacks and stuff

**Comment by iamunknown2** [comment]
NP. Just don't get stuck in the Hurd loop:

![Good Code](https://imgs.xkcd.com/comics/good_code.png)

**Comment by iamunknown2** [comment]
Also, it's probably going to be a pretty annoying task, considering that we've even built a tutorial on top of Elemental already.

**Comment by mrjacobbloom** [comment]
I'll make an effort to keep the HTML working exactly the same way, then the tutorial should continue to function. And worst case I can rework them too

**Comment by mrjacobbloom** [comment]
I'm working on this

**Comment by benajaero** [comment]
Just a question:
Why not just use blockly?

**Comment by mrjacobbloom** [comment]
'cause I'm having too much fun doing it myself
also see #26

**Comment by BookOwl** [comment]
> also see #26

pls don't
i was so immature and ridiculous.

**Comment by mrjacobbloom** [comment]
lots of progress on this, it's still partially-done but I'm excited

**Comment by mrjacobbloom** [comment]
>> also see #26

> pls don't
 i was so immature and ridiculous.

😈

**Comment by BookOwl** [comment]
hey, I was 14. 'nuf said

**Comment by matthewr6** [comment]
What but you said you're 17 now

also I was also... different :P

**Comment by BookOwl** [comment]
it was a couple months before i turned 15

or I was 15 and I just can't count :P

**Comment by matthewr6** [comment]
To be 17 now you were 16 by 4/11/2016 and 15 by 4/11/2015 :P

**Comment by iamunknown2** [comment]
Srsly though, wouldn't it be much faster if we just used Blockly? They even have a [block-making web interface](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html)!
Edit: I've already made the h1 and text blocks in Blockly (took me about an hour to understand how Blockly works by going through docs and stuff, but development will be pretty quick after you go through the docs and get a brief understanding of how everything works). ~~Will push the code to GitHub later.~~ It's [here](https://github.com/iamunknown2/Elemental/tree/gh-pages). The page can be found [here](https://iamunknown2.github.io/Elemental/) (case sensitive, `/` needed at the end for some reason)

**Comment by matthewr6** [comment]
But it's *fun*

**Comment by BookOwl** [comment]
And Elemental's blocks look better.

**Comment by matthewr6** [comment]
Thanks to... @PullJosh I think

**Comment by iamunknown2** [comment]
Can't we reskin the Blockly blocks?

Seriously, I think Blockly is the way to go here.

**Comment by mrjacobbloom** [comment]
But I'm having fuuuuun and I'm most of the way done anyway

**Comment by iamunknown2** [comment]
I can probably finish most of the blocks very quickly (most of the blocks follow a similar template).

**Comment by matthewr6** [comment]
*fun* though

**Comment by iamunknown2** [comment]
> *fun*

We should do things the easiest and most standard way possible, not the most fun way possible.
Plus, aren't we sort of violating DRY (don't repeat yourself) when we re-invent the wheel when we could just *use* the wheel somebody has already invented?

**Comment by mrjacobbloom** [comment]
I already have all of the blocks working fully, right now I'm working on file i/o

**Comment by mrjacobbloom** [comment]
> We should do things the easiest and most standard way possible, not the most fun way possible.
Plus, aren't we sort of violating DRY (don't repeat yourself) when we re-invent the wheel when we could just use the wheel somebody has already invented?

I feel like one of the unstated goals of this project was to have fun building it, if we wanted to do everything the most efficient way we would've started with a website template and Blockly and we never would've attempted a backend, but I also would've abandoned the project far sooner because building something from the ground-up is a lot more fun

**Comment by iamunknown2** [comment]
> I feel like one of the unstated goals of this project was to have fun building it

![Citation needed](https://imgs.xkcd.com/comics/wikipedian_protester.png)

If our goals of the project were to have fun building it, maybe we should have built our own browser to implement our site in machine code from the ground up.

Also, do you have any specs for your implementation of the object system so we can all use it?

**Comment by PullJosh** [comment]
> have fun  
  
> machine code

**Comment by iamunknown2** [comment]
>>  have fun
>
>>  machine code

Hey, but your idea of fun is writing stuff from the ground up...

**Comment by mrjacobbloom** [comment]
Let's stop squabbling and take it to a vote:
React 👍 for Blockly
React 👎 for #249
React ❤️ to keep the current system

**Comment by matthewr6** [comment]
Go ahead and finish the PR before writing specs because there's probably still potential for change :P  (assuming #249 is what we go with)

Also I really don't want to keep the current system because that stream-of-consciousness post I made caused me to realize the flaws the current system has... which would pretty much require a rewrite

The vote will provide the citation you request so I guess that works

also blockly is ugly and I can't find how to restyle it

**Comment by TheInitializer** [comment]
I can't react because mobile but

Fun

**Comment by iamunknown2** [comment]
> also blockly is ugly and I can't find how to restyle it

It took some fiddling, but once I figured that the styling was put in `blockly/core/css.js` and the constants were put in `blockly/core/constants.js`, I put a white border around every block, changed the saturation and value of the CSV (which is hardcoded to keep things consistent, apparently) and changed up the background colors to create something like this:

![Elemental in Blockly](https://cloud.githubusercontent.com/assets/11188939/24999497/41db5ce4-2070-11e7-982f-eb1410da95fe.png)

The menu bar looks awful, but it's an improvement.

**Comment by BookOwl** [comment]
still looks ugly.
(no offense to you, but blockly is inherently ugly, and unless you do something like scratch-blocks we can't do much about it.)

**Comment by benajaero** [comment]
But you can style blockly anyway you want. Like scratch-blocks did

**Comment by BookOwl** [comment]
But if we have to go to all that trouble just to get OK looking blocks it would be easier to just keep what we already have.

**Comment by benajaero** [comment]
I understand it requires work but think about it.

Blockly gives you everything you need but only requires that you style it.
I personally think the benefits outweigh the cons.

**Comment by matthewr6** [comment]
> anyway [sic] you want

not as far as we've seen

we've pretty much decided to go with #249 based on the vote of past and current contributors

**Comment by TheInitializer** [comment]
Fun

**Comment by mrjacobbloom** [comment]
closing since #258 was merged
