### ISSUE TITLE
What are we going to have be blocks?

### ISSUE THREAD

**Issue by BookOwl** [ElementalCode/elemental#25]
I know we will have html be blocks, and I am pretty sure that CSS will be also, but what about Javascript? It seems that it would be quite complicated to represent JS as blocks...

**Comment by TheInitializer** [comment]
Why not? That part should be just like Scratch :P

**Comment by BookOwl** [comment]
Try giving me blocks for this:

```
var Elephant_ctor = function(name, type, color){
   this.name = name;
   this.type = type;
   this.color = color;
}
// Instance members for the Elephant class
var Elephant_iprops = {
   speak: function(line){
      console.log(this.name + ', the ' + this.color + ' ' + this.type + ' elephant says: ' + line)
   },
   act: function(action){
      console.log(this.name + ', the ' + this.color + ' ' + this.type + ' elephant ' + action + '!')
   }
}
// Static members for the Elephant class (null means none)
var Elephant_sprops = null;

// Create the class
//                          Constructor,   Instance Members,  Static Members
var Elephant = CLASS.create(Elephant_ctor, Elephant_iprops,   Elephant_sprops);

// Create an instance
var ellie = new Elephant('Ellie', 'baby', 'white');
ellie.speak('Hello');
ellie.act('cries');

```

**Comment by TheInitializer** [comment]
ugh i hate how people use lambdas for everything in js... can't we just skip the lambdas? :P 

jk

**Comment by BookOwl** [comment]
Well then that isn't full JS

**Comment by PullJosh** [comment]
HTML & CSS - full support
JS - Include basic JS support, as well as a block that allows you to write custom JS. That way, we can focus our efforts on HTML/CSS, while still allowing full JS functionality
Other text-based files (other typed languages, .txt files, .md files, etc.) - open in a simple text-editor
Images - Just show a preview of the image, don't allow editing
Videos - Show preview of video
Sounds - Allow users to play sound, but no editing
Other things - Display text that says "No preview available"

**Comment by TheInitializer** [comment]
_looks closer at code_ WTH is that? This is why I hate JS

**Comment by matthewr6** [comment]
That wasn't JS, that was @BookOwl's try to "simplify" it :P

**Comment by BookOwl** [comment]
What do you mean, "try", it is simpler...maybe...Ok, you guys win, it's not really any simpler! But it gave me experience writing JS modules, solidified in my mind how JavaScript objects work, and gave let me learn how to set up a GitHub repo/wiki, so it wasn't a total bust...

**Comment by matthewr6** [comment]
Yup :)

**Comment by PullJosh** [comment]
Closing to keep things clean. As of now, [this](https://github.com/ElementalCode/Elemental/issues/25#issuecomment-123473227) will be our answer.

If there are any objections, just reopen the issue.
