### ISSUE TITLE
Tutorial broken even without scrolling

### ISSUE THREAD

**Issue by iamunknown2** [ElementalCode/elemental#254]
I just discovered that the glitch (topBar is pushed up when tutorial focuses on the `rightSide` of the block editor) happens even when `overflow: visible;` is applied to `.scriptingArea`.

**Comment by iamunknown2** [comment]
OK, it seems that an offset of 20px at the top solves the issue, but that hack-ish workaround is might prove a pain in the neck later on.

Also, using 20px as an offset seems to be a motif in intro.js. Hmm...

Edit: Ah whatever, I'm just going to do it the quick way for now.

**Comment by mrjacobbloom** [comment]
Oh wow, I didn't even notice that. Nice catch!

**Comment by mrjacobbloom** [comment]
I bet intro.js is setting itself to the size of the workspace, which is the height of the window, plus its border or padding, which grows everything else. It probably needs a box-sizing:border-box somewhere

**Comment by iamunknown2** [comment]
OK, made a fix which creates another more minor bug.

**Comment by matthewr6** [comment]
> a fix which creates another more minor bug.

yay programming

**Comment by PullJosh** [comment]
> > a fix which creates another more minor bug.
>
>yay programming

![image](https://cloud.githubusercontent.com/assets/5458180/25208929/cbb02038-2545-11e7-8d80-14cbbaa1d444.png)
