### ISSUE TITLE
Workspace Source Format

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#27]
I figure we should set this up so that I don't hate everyone else's syntax and they don't hate mine. JSON, please?

**Comment by matthewr6** [comment]
Of course.

**Comment by BookOwl** [comment]
Definitely

**Comment by PullJosh** [comment]
**Defiantly**: Rebelliously: in a rebellious manner; "he rejected her words rebelliously"

Perhaps you meant "definitely"?

**Comment by BookOwl** [comment]
Yes, that is what I meant! (Darn auto-correct)

**Comment by PullJosh** [comment]
![image](https://cloud.githubusercontent.com/assets/5458180/8815951/4b1bb0b6-2fee-11e5-9686-57d31c988d7e.png)

**Comment by BookOwl** [comment]
Hardy har har.

**Comment by PullJosh** [comment]
![image](https://cloud.githubusercontent.com/assets/5458180/8816367/06c094d0-2ff4-11e5-8eba-1e6dec108a36.png)

**Comment by matthewr6** [comment]
YESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
MIGRATIONSSJDIDIJDSDG
WORKDSLFJ:SDKFSD:L
SO
SDKFLJ:SDJKFSDF
HAPPY

**Comment by an-OK-squirrel** [comment]
Should we add a  wiki?

**Comment by matthewr6** [comment]
yes

**Comment by an-OK-squirrel** [comment]
KK! I'll work on it later.

**Comment by matthewr6** [comment]
And we WILL USE JSON.  No questions, end of discussion :3

**Comment by an-OK-squirrel** [comment]
KK!

**Comment by quat1024** [comment]
Json is so perfect for this. Supports nesting/attributes, js libraries exist for it, kinda human readable, simple :)

**Comment by an-OK-squirrel** [comment]
Yep!

**Comment by an-OK-squirrel** [comment]
Check the wiki!
