### ISSUE TITLE
Theme Colors

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#28]
If the frontend is powerful, I'm fairly sure I can get this to be a clone of Scratch but teaching HTML/CSS :P (eg users, projects, loves/faves, etc) given enough time (even forums).
Anyways.
What are our theme color(s)?  I'm interested in something with green.

Current contenders:
- #2ecc72 and #9b59b6
- #99FF66 and

**Comment by PullJosh** [comment]
Hmm... how about #2ecc71 and #27ae60?
(Got those from [flatuicolors.com](http://flatuicolors.com)

**Comment by Firedrake969** [comment]
Screenshot by each other? (Can't look now for some reasons)

**Comment by matthewr6** [comment]
Read as flatulance colors... lol

**Comment by matthewr6** [comment]
I like #2ecc72 and #9b59b6

**Comment by an-OK-squirrel** [comment]
Off-Black and green!

**Comment by matthewr6** [comment]
Hex codes for those?

**Comment by an-OK-squirrel** [comment]
I dunno, still finding good ones. :P

**Comment by an-OK-squirrel** [comment]
WAITWAITWAIT
How about we let the user pick the theme?

**Comment by matthewr6** [comment]
We should have a selection of a few (like I had in http://firedrake969.github.io/old at the very bottom)

**Comment by an-OK-squirrel** [comment]
#99FF66 and....

**Comment by matthewr6** [comment]
and?

**Comment by an-OK-squirrel** [comment]
I dunno. I'm doing these manually, so they look baddish :P

**Comment by matthewr6** [comment]
lol

**Comment by an-OK-squirrel** [comment]
I've always been bad at finding colors that involve black :P

**Comment by matthewr6** [comment]
#000000

**Comment by matthewr6** [comment]
What you have in mind?
#34495e for black
#27ae60 for green

**Comment by PullJosh** [comment]
I _hate_ sites with multiple themes.

**Comment by PullJosh** [comment]
Don't allow options.

**Comment by matthewr6** [comment]
So do we want green/black or green/purple?  IDC either way.

**Comment by PullJosh** [comment]
Green/light grey?

**Comment by PullJosh** [comment]
![image](https://cloud.githubusercontent.com/assets/5458180/8830205/fdaa576c-3068-11e5-867f-1265d1c8be3b.png)

**Comment by matthewr6** [comment]
barf
I like Sublime's background gray
#1D1E1A
Maybe combine it with that green?

**Comment by PullJosh** [comment]
lol

yeah

**Comment by PullJosh** [comment]
I don't mind the top bar, but couldn't get everything else anywhere near right.

**Comment by matthewr6** [comment]
What are palettes for?

**Comment by PullJosh** [comment]
Those are the block palettes. In scratch, they're "Motion", "Control", "Looks", etc.

**Comment by PullJosh** [comment]
The "palette [num]" text is just a placeholder.

**Comment by matthewr6** [comment]
Ah, ok

**Comment by PullJosh** [comment]
Obvioulsy, red color would be replaced with different colors for that specific palette.

**Comment by matthewr6** [comment]
Yeah

**Comment by matthewr6** [comment]
What features of Scratch do we want in Elemental?  I'm fairly sure I can do most of them.

**Comment by PullJosh** [comment]
That question deserves a new issue.

**Comment by matthewr6** [comment]
Yeah

**Comment by BookOwl** [comment]
![image](https://cloud.githubusercontent.com/assets/13385064/8830853/8e9402de-306c-11e5-9949-3cb0dc1d613b.png)
I like this.

**Comment by matthewr6** [comment]
Probably doing a green/black mix.

**Comment by PullJosh** [comment]
Gamemaker studio style?

**Comment by matthewr6** [comment]
Yeah but keep the green bar at the top.
Basically replace that ugly green around the palettes with the black hex I mentioned

**Comment by PullJosh** [comment]
Okay!

**Comment by PullJosh** [comment]
Oooh, it looks good. :)

**Comment by matthewr6** [comment]
Pic?

**Comment by PullJosh** [comment]
Also, (unrelated), I've "splurged" and used jquery. Is that okay?

**Comment by matthewr6** [comment]
Fine...

**Comment by PullJosh** [comment]
I hate it too, but it'll only be for the editor.

**Comment by matthewr6** [comment]
Ok
Picture of editor mockup?

**Comment by PullJosh** [comment]
Actually... I might not need it. We'll see.

(Pic soon)

**Comment by PullJosh** [comment]
![image](https://cloud.githubusercontent.com/assets/5458180/8831116/34750e7c-306e-11e5-8d28-9d257fa13d82.png)

**Comment by PullJosh** [comment]
Ignore the fact that there's only one red palette color indicator. :P

**Comment by BookOwl** [comment]
![](https://cloud.githubusercontent.com/assets/5458180/8831116/34750e7c-306e-11e5-8d28-9d257fa13d82.png)
Ugh... I like the gray

**Comment by matthewr6** [comment]
A bit lighter gray might be better

**Comment by PullJosh** [comment]
I'll play around with different shades.

**Comment by PullJosh** [comment]
![image](https://cloud.githubusercontent.com/assets/5458180/8831307/7bd6c37c-306f-11e5-9b44-3f41b1e4562e.png)

**Comment by matthewr6** [comment]
I love it.
But the arrow is slightly off.

**Comment by PullJosh** [comment]
You mean on the dropdown?

**Comment by matthewr6** [comment]
Yes

**Comment by PullJosh** [comment]
Is it too far left? I can't even tell...

**Comment by matthewr6** [comment]
too far right

**Comment by PullJosh** [comment]
I currently have it set at a fixed amount left of the right side of the menu name (if that made sense). I don't know the exact number, but (as an example), let's say it was 10px.

On the file menu, the tip of the arrow will be 10px right of the left side of the "F". On the about menu, it will be 10px left of the right side of the "A".

Unfortunately, I don't know how to center the tip of the arrow with CSS (or JS, for that matter). :/

**Comment by TheInitializer** [comment]
the gradient looks too barry

**Comment by matthewr6** [comment]
barry?

**Comment by quat1024** [comment]
Muh flat design D:

**Comment by PullJosh** [comment]
See [Dev Notes](https://github.com/ElementalCode/Elemental/wiki/Dev-Notes) for current colors.
