### ISSUE TITLE
Features from Scratch?

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#29]
eg forums, loves, favorites, comments, etc
Just because we can doesn't mean we should, though.

**Comment by PullJosh** [comment]
Is it worth even including any sort of project sharing? It makes malicious projects a _much_ bigger issue. :/

**Comment by matthewr6** [comment]
True, but I'm sure I can recruit people to be mods
Also, if they saved anything malicious, we could get in trouble anyways for hosting it although it's not on purpose

**Comment by PullJosh** [comment]
And that's when things start to get messy.
In your own words, "Just because we can doesn't mean we should."

**Comment by matthewr6** [comment]
Exactly.  Should we even allow project saving on the server?

**Comment by PullJosh** [comment]
Yeah. I would allow that.

Do what Snap! does.

**Comment by matthewr6** [comment]
What does Snap! do?  I've never used it.

**Comment by PullJosh** [comment]
Make an account, then you can save your projects online, but it's private to you.

**Comment by matthewr6** [comment]
Sounds good, though I'm still worried about bad uploads...  :L

**Comment by PullJosh** [comment]
What do you mean by that?

**Comment by matthewr6** [comment]
Stuff I probably shouldn't mention, and it's better if you don't know about :/
I guess it's fine as long as the ToS covers our butts.

**Comment by PullJosh** [comment]
Hmm... I might know what you mean. :3

Implement banning of users/IPs.

**Comment by matthewr6** [comment]
It's not something you should be going ":3" about...
I can do bans pretty easily.

**Comment by PullJosh** [comment]
1) Then I probably don't know.

2) Awesome!

**Comment by BookOwl** [comment]
I would say that we should implement a simple forum.

**Comment by matthewr6** [comment]
1)  And it's good that you don't.  Trust me.
2)  :D 

@BookOwl DjangoBB shouldn't be too hard to set up (I think)

**Comment by BookOwl** [comment]
Good

**Comment by quat1024** [comment]
I really really don't think we should handle this ourselves. How about some kind of "Share to CodePen" button, and let them handle the community aspects / moderation / etc. They have an api.

That way people can get feedback from an existing and active community of professional front-end designers as well.

https://blog.codepen.io/documentation/api/prefill/

**Comment by PullJosh** [comment]
Oh, that's cool! Didn't know that existed.

**Comment by quat1024** [comment]
Me neither until I decided to google "codepen api" :stuck_out_tongue_winking_eye:

**Comment by PullJosh** [comment]
GG.
_<sup>Good guess</sup>_

**Comment by matthewr6** [comment]
Should we let them log in to accounts still?  They can link their account to a Codepen account.
Also - isn't CodePen for only SPAs?  Not multiple pages?

**Comment by PullJosh** [comment]
Ah, true... One page only. :/

**Comment by quat1024** [comment]
Upload each page as an individual codpen? Links work across pens I think

Will require some url-fudging though on links and I'm not sure I like that (plus it might be impossible)

Huh

**Comment by PullJosh** [comment]
Not a fan of that method, though I can't say I have a better one.

**Comment by quat1024** [comment]
Yeah actually no, it's impossible. If page A links to page B and vice versa, they both need to know each other's urls.

Other options = faking links with JS, just plain disabling the codepen button on multi-page sites, not having an online community at all (lol), doing our own online community (and then get it hacked, heh), or providing basic anonymous-only sharing so there's no personal information we're being trusted with.

If we do our own community we'll need an anti-phishing feature prolly. I like how CodePen puts a little bar at the bottom in full-page view so they know it's a Pen and not a "real" website (random pen from the front page example http://codepen.io/russted/full/pJOPxO/ )

Ed: Sorry to be a debbie downer about all this community stuff, I'm just super paranoid

**Comment by matthewr6** [comment]
I don't think it'll get hacked that easily (django's pretty good), but I'm worried about uploads.

**Comment by PullJosh** [comment]
You don't _think_. And you're probably right.

But you might be wrong, and that would **really** suck.

**Comment by matthewr6** [comment]
Django's security is already built-in, unlike PHP in Gwiddle or x10 where you have to make your own security.

**Comment by quat1024** [comment]
As long as there's 0% chance any typed code by a user can be executed on the server we're good right ?

**Comment by matthewr6** [comment]
Yup - Django cleans its queries, and I will never execute raw SQL.
Social engineering isn't something anybody can stop, though.

**Comment by an-OK-squirrel** [comment]
If it's inapropriate images, how about only running images that are links to trusted img-sharing sources (dunno which ones)

**Comment by matthewr6** [comment]
tinypic and cubeupload only?
Or are there any others?

**Comment by an-OK-squirrel** [comment]
https://www.youtube.com/watch?v=WzKKjJuujSs

**Comment by matthewr6** [comment]
tinypic and cubeupload it is.

**Comment by an-OK-squirrel** [comment]
Kk!

**Comment by an-OK-squirrel** [comment]
Swear filtering would have to be hashed so people from Scratch who might look at the code don't see a list :P

**Comment by matthewr6** [comment]
oh yeah dang it
who knows the most swear words?
xD

we should probably just find a pip package for it - I don't think we care if they make their own site unshared with whatever they want, but it should be filtered before sharing.

**Comment by an-OK-squirrel** [comment]
I dunno. I know a few, but I have a family computer and I don't know if it's keylogged soooo

**Comment by an-OK-squirrel** [comment]
there's probably a library that'll do that for us :P

**Comment by matthewr6** [comment]
I hope so.

**Comment by an-OK-squirrel** [comment]
Yep!

**Comment by an-OK-squirrel** [comment]
Moderation is why I haven't made a website :P

**Comment by PullJosh** [comment]
"Is it worth even including any sort of project sharing? It makes malicious projects a much bigger issue. :/" - Me, four hours ago

**Comment by matthewr6** [comment]
"Make an account, then you can save your projects online, but it's private to you."
- You, four hours ago

We could manually approve users to share projects...

**Comment by an-OK-squirrel** [comment]
Uh-huh! I think some other sites do that. (pj, check your scratch messages!)

**Comment by PullJosh** [comment]
@Firedrake969 I forgot about that... Man, I have really good ideas.

**Comment by matthewr6** [comment]
xD

**Comment by alyssarosenzweig** [comment]
If you embed each page of the site within a script element (of type "text/html"), then it's pretty natural to do some JavaScript fiddling to fit a site on one codepen link...

Probably ugly tho

**Comment by matthewr6** [comment]
Ew.

**Comment by PullJosh** [comment]
Probably?

**Comment by matthewr6** [comment]
I'm interested in it...
But doesn't mean it's probably going to be hard to implement and ugly :P

**Comment by alyssarosenzweig** [comment]
haha
