### ISSUE TITLE
Django secret key

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#31]
For hashing and stuff - how should we keep it private?

**Comment by an-OK-squirrel** [comment]
No clue

**Comment by an-OK-squirrel** [comment]
Also, I have a problem with the wiki page you made...

**Comment by matthewr6** [comment]
I'm going to make a secret_settings page where only I know the key, and I'll add it to the .gitignore.

What's the problem?

**Comment by matthewr6** [comment]
http://fearofcode.github.io/blog/2013/01/15/how-to-scrub-sensitive-information-from-django-settings-dot-py-files/

**Comment by an-OK-squirrel** [comment]
How do I run  the other programs while the first command (runserver) is running? :P

**Comment by matthewr6** [comment]
New tab (I'd suggest using http://gooseberrycreative.com/cmder/ for Windows, or iTerm2 for OS X)

**Comment by an-OK-squirrel** [comment]
Oh kk

**Comment by an-OK-squirrel** [comment]
That's not what I meant.

**Comment by an-OK-squirrel** [comment]
I meant should I ctrl+break so I can create superuser and that stuff

**Comment by matthewr6** [comment]
No, open up a new terminal so you can do that stuffl.

**Comment by an-OK-squirrel** [comment]
ohhh :P
