### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#32]
For _our_ code (the code used to make elemental, not the code generated by it) can we all agree on a style guide?

My thought was to use [Google's HTML/CSS one](http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml).

Does anyone have any problems with that?

**Comment by an-OK-squirrel** [comment]
Sure!

**Comment by an-OK-squirrel** [comment]
What about js?

**Comment by PullJosh** [comment]
http://google.github.io/styleguide/javascriptguide.xml

**Comment by an-OK-squirrel** [comment]
Okay!

**Comment by quat1024** [comment]
As long as the curly brace is on the same line as the declaration I'm in. Oh, good, it is.

Alright.

**Comment by PullJosh** [comment]
xD Yeah.

**Comment by an-OK-squirrel** [comment]
Haha, yep.

**Comment by BookOwl** [comment]
Let's use it!

**Comment by an-OK-squirrel** [comment]
Kk
