### ISSUE TITLE
Dev Notes

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#33]
Just created a Wiki page titled [Dev Notes](https://github.com/ElementalCode/Elemental/wiki/Dev-Notes) and wanted to let you guys know about it. Be sure to read through the entire thing, and let me know if there's anything that should be added or changed!

**Comment by matthewr6** [comment]
I like it.
Why does jTron hate backend lol

**Comment by PullJosh** [comment]
Awesome! Anything that should be added?

**Comment by matthewr6** [comment]
Can't think of any right now
