### ISSUE TITLE
Cool stuff we're using

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#35]
Or stuff we might want to use/learn how to use.
- Django
- SCSS
- CLI
- ReactJS
- RiotJS

**Comment by PullJosh** [comment]
You expect me to learn all that?

I can do SCSS. The rest of it I either never heard of or saw and decided it was too hard so I left.

**Comment by an-OK-squirrel** [comment]
^

**Comment by an-OK-squirrel** [comment]
Ohwait. CLI? Command line interface? SURE!

**Comment by matthewr6** [comment]
Lol yeah

**Comment by matthewr6** [comment]
PullJosh - just might be worth checking out

**Comment by an-OK-squirrel** [comment]
I'm not learning riot or react. Seriously, I have a life!

**Comment by matthewr6** [comment]
Wait
Programming isn't your life?

**Comment by PullJosh** [comment]
Nope! We all have lives to live. Not every moment can be spent coding.

If you can set it up so that the rest of us don't have to use these things, but you still can, then that would be awesome! However, if we would all be forced to learn it, we'll have to say no to using them.

**Comment by matthewr6** [comment]
I was joking...
These are just suggestions, because they'll probably make your life a lot easier after the first bit of learning.  Also because web components are awesome.  Your choice, though.

**Comment by matthewr6** [comment]
I know we shouldn't use jQuery, but for block snapping - http://jqueryui.com/draggable/#snap-to

**Comment by an-OK-squirrel** [comment]
Yeah, programming isn't my life.
I play video games too.

**Comment by an-OK-squirrel** [comment]
Yes, hail jQuery!

**Comment by TheInitializer** [comment]
Just wondering, are we using any frontend framework thingies like Foundation? Because those are pretty cool. P:

**Comment by matthewr6** [comment]
Not for the editor.

**Comment by TheInitializer** [comment]
Yeah obvs not from the editor but for the main site it would be cool

**Comment by matthewr6** [comment]
I don't really like frameworks, but I love little (haha) libraries like ReactJS and RiotJS for component things (which I've worked a lot in as well)

also ew jQuery so definitely no
once you use jQuery once you start using it everywhere
