### ISSUE TITLE
remove backend

### ISSUE THREAD

**Issue by quat1024** [ElementalCode/elemental#36]
Backend isn't doing anything right now besides make it super hard for people to actually run and test the thing.

Flat html/js/css files for now, add backend later / in a seperate branch (not the master branch, ugh)

**Comment by matthewr6** [comment]
How is it "super hard"?  I'll clarify the instructions if need be.  Just work on the frontend if you don't like backend, and I or **init** will merge it to the actual site.

**Comment by quat1024** [comment]
well, where is the frontend? not in `master` that's for sure

I thought we weren't pushing to `master` but it's filled with backend crap and python

**Comment by PullJosh** [comment]
If I can't double-click the file and open it in my browser, it's too hard.

If I can't run it with WAMPserver, it may as well be rocket science.

**Comment by PullJosh** [comment]
@Firedrake969 I'm sure it's easy for you - that doesn't make it easy for me. I think that calling people using an iPhone is easy. My great grandma just got an iPhone. Calling people is still hard. (true story)

For you, installing python and django and crap is easy. For me, that's really really hard! I've never gotten pip to work in my _life_, and the most complicated local server I've set up is WAMP, which comes with a windows installer. (Double-click the icon and rapidly press next without reading anything...)

**Comment by PullJosh** [comment]
You don't have to remove the backend - just put it somewhere that will allow the rest of us to do our thing without being interrupted.

**Comment by BookOwl** [comment]
+1 everything @PullJosh said

**Comment by an-OK-squirrel** [comment]
+1 above

**Comment by matthewr6** [comment]
Accept my PR and I'll format things so we can both work how we need to.

**Comment by towerofnix** [comment]
+1 @PullJosh

Also merged.

**Comment by an-OK-squirrel** [comment]
+1 @pulljosh again, because pip sucks :/

**Comment by matthewr6** [comment]
How so?

**Comment by PullJosh** [comment]
Well, it doesn't work, so...

**Comment by matthewr6** [comment]
Pip doesn't work?  The command, or using pip install?
http://www.anthonydebarros.com/2014/02/16/setting-up-python-in-windows-8-1/

**Comment by PullJosh** [comment]
I don't know... I've just never gotten it to work. It gives cryptic error messages, but I've never cared enough to spend hours of my life figuring it out.

**Comment by matthewr6** [comment]
What are the error messages?
I like messing around with my Windows computer to try to make it as *NIX-like as possible :P

**Comment by PullJosh** [comment]
IDK

**Comment by quat1024** [comment]
Going to close this because of the shiny new gh-pages branch!:)
