### ISSUE TITLE
CircleCI

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#37]
Adding integration for our tests.

**Comment by an-OK-squirrel** [comment]
So now there's another thing to blow my brain out? Thanks!

**Comment by BookOwl** [comment]
What tests?

**Comment by matthewr6** [comment]
This isn't even relevant yet so don't pay attention yet :P

**Comment by PullJosh** [comment]
Going to close for now to keep things clean. It seems that it might be needed later. If it is, just re-open then.

(I'm a clean freak, but for some reason only with github issues.)
