### ISSUE TITLE
Separate  back-end and front-end

### ISSUE THREAD

**Issue by robinp7720** [ElementalCode/elemental#38]
Seperate the two ends and use a rest api to send data between the two

**Comment by BookOwl** [comment]
good idea

**Comment by an-OK-squirrel** [comment]
+9001

**Comment by matthewr6** [comment]
Please.
I already said how we can do this, and plan to act on it later today.  Be patient.

**Comment by an-OK-squirrel** [comment]
Ok! -9001

**Comment by matthewr6** [comment]
Finished.

**Comment by BookOwl** [comment]
Great!
