### ISSUE TITLE
SCSS compiling

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#39]
I know nothing about it so the question here will be stupid.
Anyways, we store SCSS in the workspace.
But when you export it, does it compile it into css or keep it as a scss file?

**Comment by robinp7720** [comment]
if your using webStorm here is a very nice guide: https://www.jetbrains.com/webstorm/help/transpiling-sass-less-and-scss-to-css.html#d216313e166

It also just shows you how to setup scss compiling so even if you don't have webStorm, its still a nice guide

**Comment by an-OK-squirrel** [comment]
Thanks!

**Comment by PullJosh** [comment]
There's also a Sass (and SCSS) extension for [Brackets](http://brackets.io/), which is quite handy. That's what I'm using. ;)

**Comment by quat1024** [comment]
Forgot about brackets hehe. Thanks for reminding me.

Anyway, here's how to get started with the SCSS extension:
- Install Brackets from http://brackets.io
- Open it
- Press the extensions button, on the right-side bar (it looks like a lego)
- Search for "scss"
- I think it's the second one.

Now, my question is, why isn't it working? If I add

```
* {
  background-color: pink !important;
}
```

to the end of style.scss, it should make a ...noticeable change... but it doesn't seem to be doing anything

**Comment by quat1024** [comment]
Ok figured it out, I had to - get this - install SASS :sleeping:

**Comment by matthewr6** [comment]
Good job :laughing:

**Comment by quat1024** [comment]
And then it still wasn't working... so I had to... run Sass! :smile:

**Comment by matthewr6** [comment]
:O  Amazing!

**Comment by robinp7720** [comment]
The amount of web editors today is insane! But I see absolutely no block editor for html!

**Comment by an-OK-squirrel** [comment]
I'm still confused :P

**Comment by robinp7720** [comment]
Yes its all so confusing, isn't it? :p 
Install ruby here: http://rubyinstaller.org/downloads/
Follow these instructions to get gem working: https://gist.github.com/luislavena/f064211759ee0f806c88
then to gem install scss

then to compile a scss to css do C:\RailsInstaller\Ruby2.1.0\bin\scss.bat --no-cache --update $FileName$:$FileNameWithoutExtension$.css

if your using webStorm, I have added a watched to the project to automatically do this (in my fork).

**Comment by robinp7720** [comment]
if scss.bat cant find ruby.exe then you'll either have to setup a path variable for ruby (Recommened)
or do what I did and modify scss.bat to this:

``` batch
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"C:\RailsInstaller\Ruby2.1.0\bin\ruby.exe" "C:/Users/xmr/Desktop/railsinstaller-windows/stage/Ruby2.1.0/bin/scss" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"C:\RailsInstaller\Ruby2.1.0\bin\ruby.exe" "%~dpn0" %*
```

**Comment by an-OK-squirrel** [comment]
You guys don't get my question. I _know_ how to install ruby.
What I asked was, should we give the user the CSS compiled code or the SCSS code for them to compile? I'd say both.

**Comment by robinp7720** [comment]
Include both. Its one less entry in the git ignore list

**Comment by PullJosh** [comment]
@an-OK-squirrel I still don't understand what you mean. Are you talking about the exported code created by Elemental?

**Comment by an-OK-squirrel** [comment]
yes

**Comment by PullJosh** [comment]
Why would the users ever need to write SCSS?

**Comment by matthewr6** [comment]
robin... you're overcomplicating things...
the command is simply
sass --watch sassfile.scss:cssfile.css

**Comment by robinp7720** [comment]
1. That's copy and pasted from webStorm :p
2. I had a gem ssl error when I used the ruby installer
3. The ruby path wasnt set on my computer on install

So yea..

**Comment by matthewr6** [comment]
then webStorm is being horribly inefficient.
I can show you how to put Ruby's bin files on your path if you want me to...

**Comment by robinp7720** [comment]
I know how to :p

**Comment by matthewr6** [comment]
Try not to tell people overcomplicated things, then :P

**Comment by PullJosh** [comment]
Says Mr. Backend...

**Comment by an-OK-squirrel** [comment]
xd

**Comment by matthewr6** [comment]
I'll rephrase...
Overcomplicated things that can be made a lot simpler but do the exact same thing.

**Comment by an-OK-squirrel** [comment]
xP

**Comment by quat1024** [comment]
Hehe. Here's how I did it on a 64-bit Windows 7 install:
1. Install Ruby 2.1.6 from http://rubyinstaller.org (the 32-bit version)
2. Open the Start Menu -> All Programs -> Ruby 2.1.6-p336 -> Start Command
   Prompt with Ruby
3. Enter "gem install sass" in the command prompt
4. Wait, it looks like it does nothing but  just wait it out :grinning:
5. Enter "sass --watch "path/to/scss/file" into the command prompt (in my
   case, it was "E:\Stuff\git\Elemental\css")
6. Minimize the command prompt and forget I even had it running in the
   first place :)

**Comment by an-OK-squirrel** [comment]
You guys don't get my problem, I have ruby installed. But most likely the people using elemental won't :P

**Comment by quat1024** [comment]
SCSS compiles to CSS and the page uses the CSS file, nobody needs to install Ruby to use it

**Comment by an-OK-squirrel** [comment]
Yeah, but PJ said earlier that with Elemental you were going to be able to write in scss

**Comment by matthewr6** [comment]
no we're using scss for elemental

**Comment by quat1024** [comment]
If we ever incorporate SCSS into Elemental (and I don't think it's on the roadmap), we'll use something like sass.js for client-side compilation https://github.com/medialize/sass.js/

But I think elemental's going to support just plain css

**Comment by an-OK-squirrel** [comment]
You also said.... oh whatever

**Comment by PullJosh** [comment]
> Yeah, but PJ said earlier that with Elemental you were going to be able to write in scss  

I guess I did a bad job explaining... SCSS is what we will use to _make_ Elemental, not what will be able to be created _with_ Elemental.
Sorry for a poor explanation.

**Comment by an-OK-squirrel** [comment]
xD okay
