### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by quat1024** [ElementalCode/elemental#4]
What are the design goals of ~~Elephantal~~ Elemental?

It's about easing people familiar with Scratch into HTML, of course, but what else. Should it have basic features suitable for "Hello world! My first webpage :pizza: ", or should it share the same design principle as Scratch with the whole [low floor, wide walls, high ceiling](https://scratch.mit.edu/discuss/topic/245/) thing? Maybe it'll be helpful to type this up somewhere idk.

Pros to "easy mode" - well, it's much easier to implement, and how the blocks are laid out don't need to be as flexible.

Pros to "wide walls mode" - lets people design professional webpages almost as easily as making a Scratch project.

...meh, meh, I should go to bed before my rambling gets incoherent again :stuck_out_tongue:

**Comment by PullJosh** [comment]
Hmm... Low floor is obviously at the forefront of this project, and will receive the most attention and decision-making merit. However, a high ceiling would be awesome as well.

We _could_ have two different settings, one to turn on/off "advanced mode", where blocks display exactly as they do in html (`<html> %c </html>` rather than `html %c`)\* The second to turn on/off "more blocks", which contains less often-used blocks and uncommon features.

*Please excuse me if %c isn't the c-block input area

**Comment by matthewr6** [comment]
So like http://prntscr.com/7u5e0l ?
Yeah, sounds good (and fairly easy)

HTML is the priority, followed by CSS and then JS.  As I said in the forum thread - should we allow loading of external JS scripts?

**Comment by PullJosh** [comment]
Yes and yes.

But we need a way to sandbox things so that nobody does anything malicious (because everyone knows JS is so dangerous and lets you do whatever you want with no restrictions ever.)

**Comment by matthewr6** [comment]
http://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/

**Comment by matthewr6** [comment]
Because JSFiddle (I think) uses an `iframe` or something similar to be able to render the stuff - this means we will need a backend, actually, I think...

**Comment by PullJosh** [comment]
Let's assume we had a one-page site. The only page on said site is the editor. We don't sandbox their code at all.

Is it possible to do anything malicious in that scenario?

**Comment by matthewr6** [comment]
Depends... can they save it? (probably yes)
If so, can they share it with others?

**Comment by PullJosh** [comment]
I think our best bet is to save to a zip file containing everything they made - their assets, code, and such. Basically, when you save, it will just export the final result. Then, we can find a way to read HTML, CSS, and JS and convert it into blocks (obviously we would need a "custom code" block for each language as well). That way, any page they've already found or created with typed code can be opened in the visual editor.

**Comment by towerofnix** [comment]
Like tosh? :P

Basically @blob8108 basically wants to make sure that you can export tosh code into a Scratch project, and import a Scratch project to tosh.

It's all backward compatible! :P

**Comment by PullJosh** [comment]
Pretty much, yeah.

**Comment by matthewr6** [comment]
If they can't share the project on a site, I don't think there's any point to sandboxing it (although we probably should for safety anyways so people don't break it by accident)

Also, it might be easier to find something that can create json files for the CSS and HTML (and possibly JS).
CSS: https://github.com/aramk/CSSJSON
HTML: https://www.npmjs.com/package/htmlparser2 and https://www.npmjs.com/package/htmlparser-to-html

The HTML one is on npm, which is nice.

What we could do is download the json objects as well as the html/css/js, but then they couldn't edit the real files in actual html/css/js and upload it back to continue working.

**Comment by PullJosh** [comment]
That would be easier, but I feel like it would be less adaptable - harder to use, and not as close to the actual source. Perhaps saving should give a zip file containing all their code, but also a folder titled "_elem" that contains json and stuff. That way, they could just save as a zip and go - everything already exported and ready, but it could still be read by the visual editor.

**Comment by matthewr6** [comment]
That's basically what I meant :P

we tend to say similar things but then think we're saying different things

**Comment by PullJosh** [comment]
Yeah. It's really weird, a lot of times we have the same ideas but say them in different ways.

**Comment by matthewr6** [comment]
Like minds think alike.

Probably a tautology, but I never say "great minds think alike" in any case.

**Comment by PullJosh** [comment]
Similar minds think similarly.

It's probably a bit redundant, but I don't much like the phrase "great minds think alike".

**Comment by matthewr6** [comment]
again, that's what I just said xD

**Comment by PullJosh** [comment]
Just added a little thing to the readme. Sort of kind of forgot to talk to anybody beforehand, but I think it's pretty good.

**Comment by matthewr6** [comment]
ok

**Comment by glacialcascade** [comment]
Yeah we should have an advanced mode on-off.

**Comment by glacialcascade** [comment]
"The goal of Elemental is to act as a bridge between [Scratch](scratch.mit.edu) and front-end web technology. Any and all design decisions will focus on being easy to pick up, while still retaining all of the major aspects of text-based code, thus creating what might be thought of as 'a highly accessible bridge that leads to the perfect ending location'."

**Comment by PullJosh** [comment]
Thanks for quoting the readme. :P

**Comment by glacialcascade** [comment]
And pulljosh y u make so many spell mistakez

**Comment by PullJosh** [comment]
I blame spell check.

**Comment by an-OK-squirrel** [comment]
Well, if you used HTML, you'd have to parse it. :/

**Comment by PullJosh** [comment]
That's true, but being able to open a typed page in Elemental would be awesome, because there are [plenty](http://tympanus.net/codrops/) [of](http://freebiesbug.com/) [online](http://pixelbuddha.net/) [resources](http://codyhouse.co/) for free design things, and it would be great to be able to use and modify them with Elemental!

**Comment by an-OK-squirrel** [comment]
Well, exporting the blocks should be easy, it's the importing back I'm worrying about. Imagine this like Photoshop. You can make a photoshop pic with tons of layers. Then you can export it to a png, gif, etc. But you can't generate a photoshop file from a gif.

**Comment by PullJosh** [comment]
What about HTML would be able to be created as Elemental blocks? If there's anything that can't be done, we're doing something majorly wrong.

**Comment by matthewr6** [comment]
I'm tired

**Comment by an-OK-squirrel** [comment]
Huh?

**Comment by an-OK-squirrel** [comment]
@firedrake969 :P

**Comment by matthewr6** [comment]
working on making a staging app as well as production app

**Comment by glacialcascade** [comment]
@PullJosh +10^9007199254740992
