### ISSUE TITLE
Hey, everyone calm down:

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#40]
You can open it locally without needing to do anything "complicated" :)
Also, you can work on the editor in the `dev` branch now so I deleted the `ui` branch.

**Comment by matthewr6** [comment]
Leave this up for at least 48 hours so everyone sees.

**Comment by PullJosh** [comment]
Just so everyone knows, I reopened UI just to keep things more seperated - helps me keep track of my own things. :)

**Comment by matthewr6** [comment]
Ok - I'll just be copying and pasting from there, then

**Comment by PullJosh** [comment]
Sounds good! :)
