### ISSUE TITLE
Please use CDNs for libraries

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#42]
such as cdnjs.org

**Comment by BookOwl** [comment]
What's a CDNS?

**Comment by matthewr6** [comment]
Content delivery system iirc
Basically so we don't have to store any files we don't need to on our repos

**Comment by quat1024** [comment]
A CDN = content delivery network. Examples include cdnjs.org, Google WebFonts, and Amazon AWS (i think lol)

Basically the idea is that really really common Javascript libraries, like JQuery, are served from a different server online, to:
- decrease the load on the main server
- decreases clutter and increases available disk space in the repo, like Fire said up there
- allow the web browser to cache files for much faster load times

TL;DR all sortsa good stuff

**Comment by matthewr6** [comment]
Sorry I'm tired
System does not start with an N

**Comment by quat1024** [comment]
Not with that attitude it doesn't.

Nsystem

**Comment by matthewr6** [comment]
what
