### ISSUE TITLE
Available Blocks

### ISSUE THREAD

**Issue by robinp7720** [ElementalCode/elemental#44]
So, we have discussed how we should implement blocks and how they should approximately look but not what type and the function of each. Yes I know, this already has been done in the forums but I have another Idea which in my opinion is easier and cleaner to implement.

So, I have to ideas for blocks:
# First option

We have two main blocks, a container block and a text entry block.
The container block would be a c block with a drop down of all available tags, then a byob expandable list where another type of block would go into, this block would be an attribute block (more on this later). The colour of the C block should change according to what tag has been selected.

The next entry block would be a very simple block with a textbox inside. This is to allow text to be entered. for example, you could have a paragraph tag as the C block and then inside of that C block, you would have a multi-line text entry block.

The third type is like an operator block inside of scratch, but they would only fit inside of C tag blocks. They would have a drop down of all possible attributes and a textbox for the attribute value. We could implement a separate class block but this would complicate things.

On another tab somewhere in the editor we could have a create a block and create an attribute button. Similar to creating a variable in scratch. They new attribute or tag would become available in the drop down in the respected area.

This would look somthing like this:

```
---------------------------------------------
|   [dropdown]  ( [Attribtute]='      ') +|
|   |-----------------------------------------
|   |
|   |
|   |
|   |-----------------------------------------
|   Automagicly insert end tag here |
---------------------------------------------
```

Instead of having a drop down, you can have a tag block. This would fit into the first slot of the C block where the drop down would be. The tag blocks would then be sorted in the palettes. When we do this, you would need to choose which category a tag belongs to when creating it.

Using scratch blocks: https://scratch.mit.edu/discuss/topic/134554/?page=17#post-1242024
# Second option

The other option would be to have one block per tag. and have the same attribute creation system. This would fill up the block selection thing much quicker though and it would be much simpler to just have a smaller  `(<div>)` block instead of having

```
---------------------------------------------
| <div>                                             |
|   |-----------------------------------------
|   |
|   |
|   |
|   |-----------------------------------------
| </div>                                             |
---------------------------------------------
```

for every single block.

As we are going to be saving the files as json anyways, Id also recommend custom blocks. These would allow users to create snippets they use often and use those as custom blocks instead of having to create the same part over and over again

I think I should get a reward for making these beautiful ascii art c blocks!  :D

**Comment by an-OK-squirrel** [comment]
```
         .---------------------------.
        /_   _   _         __  __   /|
       // \ / \ / \ |_/ | |_  (_   / |
      / \_  \_/ \_/ | \ | |__ ,_/ /  |
     :.__________________________/   /
     |  .--. .--.   .--.   .--.  |  /
     | (    )    ) (    ) (    ) | /
     |  '--' '--'   '--'   '--'  |/
  jgs'---------------------------' 
```

**Comment by quat1024** [comment]
@robinp7720 [I'm a Scratchblocks2 ninja so is this what you mean?](http://scratchblocks.github.io/#Option%20A%20%3A%3Ahat%0A%0A%5Bdiv%20v%5D%20%E2%97%80%20%E2%96%B6%20%3A%3Acontrol%20cstart%0A%20%20.%20.%20.%0A%3A%3Acend%0A%0A%5Bspan%20v%5D%20%28%29%20%E2%97%80%20%E2%96%B6%20%3A%3Acontrol%20cstart%0A%20%20.%20.%20.%0A%3A%3Acend%0A%0A%5Bdiv%20v%5D%20%28%5Bclass%20v%5D%20%5Bcontainer%5D%20%3A%3Aoperators%29%20%E2%97%80%20%E2%96%B6%20%3A%3Acontrol%20cstart%0A%20%20.%20.%20.%0A%3A%3Acend%0A%0A%5Bdiv%20v%5D%20%28%5Bclass%20v%5D%20%5Bcontainer%5D%20%3A%3Aoperators%29%20%28%5Bid%20v%5D%20%5Basdf%5D%20%3A%3Aoperators%29%E2%97%80%20%E2%96%B6%20%3A%3Acontrol%20cstart%0A%20%20.%20.%20.%0A%3A%3Acend%0A%0AOption%20B%20%3A%3A%20hat%0A%0A%2F%2FNote%20that%20angle%20brackets%20have%20been%20removed%20from%20the%20blocks%20in%20this%20example.%0A%2F%2FIt%20causes%20issues%20with%20the%20scratchblocks2%20formatter.%0A%2F%2FThe%20%22real%20blocks%22%20will%20likely%20have%20angle%20brackets%2C%0A%2F%2Fif%20only%20in%20%22advanced%20mode%22.%0A%0Adiv%20%E2%97%80%20%E2%96%B6%20%3A%3Acontrol%20cstart%0A%0A%2Fdiv%20%3A%3Acend%0A%0Aspan%20%E2%97%80%20%E2%96%B6%20%3A%3Acontrol%20cstart%0A%0A%2Fspan%20%3A%3Acend)

**Comment by robinp7720** [comment]
@quat1024 Yep! 
In the second part of the first method I said the dropdowns could become very long, so I recommend catogorized tag blocks like this: http://scratchblocks.github.io/#html%20%3A%3A%20hat%20events%0A(header)%20Attributes%3A%20()%2B%20%3A%3A%20cstart%20control%0A%2F%2F%20stuff%0A%2Fheader%20%3A%3Acend%0A(body)%20Attributes%3A%20(%5Blang%20v%5D%3D%5Ben%5D)%20%2B%3A%3A%20cstart%20control%0A%2F%2F%20stuff%0A%2Fbody%20%3A%3Acend

though the head and body should be <head> and <body>.

And I'd recommend removing the advanced mode as it will just confuse everyone

**Comment by PullJosh** [comment]
I much prefer the option @quat1024 has given.

Additionally, I believe we had already decided on the one he presented.

**Comment by matthewr6** [comment]
@robinp7720 I repeat - please read **all** the issues before suggesting something - often, it's already been suggested (and decided upon)

**Comment by robinp7720** [comment]
@PullJosh I'm just stating instead of having a dropdown having categorized tag blocks instead.

**Comment by robinp7720** [comment]
@Firedrake969 No one has suggested categorized tag blocks?

**Comment by PullJosh** [comment]
That's a fantastic suggestion! However, it should go in the issue that has already been made, rather than starting a new one. It makes things messy. ;)

**Comment by quat1024** [comment]
@robinp7720 THe main argument against having dropdowns is their length. Which is why we won't be using dropdowns, but fancy dropdowns instead! :smile:

So we'll have the 10 most commonly used attributes on the first "page". THe rest of the pages will be filled with all the attributes in alphabetical order. There will also be a fuzzy search bar, where you can type the name of an attribute and it'll autocomplete them

**Comment by robinp7720** [comment]
@quat1024 Thats why I suggested categorized tag blocks

**Comment by matthewr6** [comment]
Which is what we're already doing...

**Comment by robinp7720** [comment]
@Firedrake969  I dont mean a c block for every tag but instead one c block and blocks like these:

```
(<div>)
```

**Comment by matthewr6** [comment]
we went over this already, can't find the issue though

**Comment by robinp7720** [comment]
@Firedrake969  thats why I made this. And because Josh locked the other issue, json is an object description language. Not a markup languauge. The object has to describe the scripts. Not the html
I think thats where your getting confused. When saving the project they should be saved as An Elemental file types, which should be a zip and the json files.

When exporting to html, we can write a parser which will convert my json save file into html. This is fairly easy to do.

Yes we can add a combined head and body block but it should still be possible to have two headers or two bodies. Yes this shouldn't be done but it is a block based frontend web ide. We shouldn't be limiting ourselves.

The problem with the library you suggested is not that it doesnt convert html to json and json to html but that it wont save Elemental block projects. We need to be able to save the position of every block and script in a file and not convert json to html.

**Comment by PullJosh** [comment]
The other one is open again. Feel free to continue discussing (in a calm and productive manner).

**Comment by robinp7720** [comment]
@an-OK-squirrel Thanks :)

**Comment by an-OK-squirrel** [comment]
No problem. Feel free to discuss the issue more on my Scratch profile (woohooboy)

**Comment by matthewr6** [comment]
@PullJosh and I have made an executive decision about it.

**Comment by an-OK-squirrel** [comment]
I know...

**Comment by an-OK-squirrel** [comment]
Also, can we do the chat on something other than jsfiddle? It's ugly for collaboration.

**Comment by matthewr6** [comment]
It's amazing for code collaboration

**Comment by matthewr6** [comment]
Unless we all agree to use gitter

**Comment by matthewr6** [comment]
Which I for one don't want to

**Comment by an-OK-squirrel** [comment]
But I thought we were using it to plan out stuf?

How about an IRC and JsF when we need to code something

**Comment by PullJosh** [comment]
Google docs is surprisingly good for chat & planning. Make a doc and use the chat feature to discuss things, and when you make a decision, add it to the doc.

**Comment by an-OK-squirrel** [comment]
I no have Google account

**Comment by matthewr6** [comment]
I need to remain anonymous (email wise) but iirc you can edit w/o signing in right

**Comment by PullJosh** [comment]
It can be set up that way, yes.

**Comment by an-OK-squirrel** [comment]
Same here. My gmail is personal...
