### ISSUE TITLE
Please people make the guy writing the WSF's life easier

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#45]
And post your ideas for the WSF here. Some of the ideas going on here are going to be impossible to do, which sucks for me.

**Comment by an-OK-squirrel** [comment]
Also, view the current WSF here: https://github.com/ElementalCode/Elemental/wiki/WSF-Format

**Comment by robinp7720** [comment]
I'd recommend something like this to avoid cluttered block categories and because your forgetting the fact you can drag blocks and scripts:

http://scratchblocks.github.io/#html%20%3A%3A%20hat%20events%0A(header)%20Attributes%3A%20()%2B%20%3A%3A%20cstart%20control%0A%2F%2F%20stuff%0A%3A%3Acend%0A(body)%20Attributes%3A%20(%5Blang%20v%5D%3D%5Ben%5D)%20%2B%3A%3A%20cstart%20control%0A%2F%2F%20stuff%0A%3A%3Acend

``` json
[
    {
        scriptType: "html",
        position: {
            x: 100,
            y: 100
        },
        scriptContent: [
            {
                type: "c-container",
                data: {
                    values: {
                        tag: "header",
                        attr: {}
                    }
                },
                content: {

                }
            },
            {
                type: "c-container",
                data: {
                    values: {
                        tag: "body",
                        attr: {
                            "lang": "en"
                        }
                    }
                },
                content: {

                }
            }
        ]
    }
]
```

This would be much more expandable and flexible.
The final save file doesnt have to be human readable, just easy for a computer to understand

**Comment by matthewr6** [comment]
As long as you can compile the HTML and CSS blocks to this -
https://github.com/ElementalCode/Elemental/issues/4#issuecomment-122586378
we should be good.  No need to make our own json format.

**Comment by matthewr6** [comment]
https://github.com/ElementalCode/Elemental/issues/27

**Comment by an-OK-squirrel** [comment]
:/

**Comment by matthewr6** [comment]
Seemed basically the same.

**Comment by an-OK-squirrel** [comment]
I'll use something like robin's.

**Comment by matthewr6** [comment]
Could you at least check out and mess around with the npm links I gave?  It'd be a lot easier to write compilers that way.

**Comment by an-OK-squirrel** [comment]
That's not block-based tho

**Comment by matthewr6** [comment]
Yeah, I mean compile the blocks into that JSON format

**Comment by robinp7720** [comment]
We can easly write out own parser.
If need be, I'll make it.
But my json format will allow multiple scripts and moving scripts and data values while keeping the original save state. Your method would require having a block for every thing tag and not supporting moving scripts and not even mutiple scripts

**Comment by an-OK-squirrel** [comment]
What I don't like it you have body and head as seperate blocks. You can't have more than one body, so there's no point!

**Comment by matthewr6** [comment]
I vote the npm packages and GH repo, but let's wait for some other people's input.
@an-OK-squirrel are you talking about my links or robin's suggestion?

**Comment by an-OK-squirrel** [comment]
robin's

**Comment by an-OK-squirrel** [comment]
I vote robin's

**Comment by robinp7720** [comment]
@Firedrake969 You'd be having to recompile the project every time when you load it and saving would loose you so much data.

@an-OK-squirrel my idea litterly has 2 blocks and the rest are data types such as attribute blocks and tag blocks.

having seperate blocks of head and body would over complicate things and make saving a little more complicated

**Comment by an-OK-squirrel** [comment]
What I'm saying is that I like head and body being combined into one block.

**Comment by matthewr6** [comment]
lose*
Any JSON-based saving requires recompiling based on the JSON, lol, not sure what you mean

also, for CSS - 
https://github.com/aramk/CSSJSON

**Comment by quat1024** [comment]
http://scratchblocks.github.io/#html%20%3A%3A%20hat%20events%0Ahead%20%3A%3Acstart%20control%0A%20%20...%0Abody%20%3A%3Acelse%0A%20%20...%0A%3A%3Acend%20cap

**Comment by matthewr6** [comment]
btw PJ and I did talk about this earlier...
https://github.com/ElementalCode/Elemental/issues/4#issuecomment-122597350

**Comment by an-OK-squirrel** [comment]
Yes, what quat said. Like that :P

**Comment by matthewr6** [comment]
Yeah, I know

**Comment by matthewr6** [comment]
http://prntscr.com/7wv270

**Comment by robinp7720** [comment]
If we we're to combine it, there would be multiple c blocks with and without the tag selectors and it would just be alot more complicated to save.

**Comment by an-OK-squirrel** [comment]
What?

**Comment by an-OK-squirrel** [comment]
It would be easier in the long run.

**Comment by matthewr6** [comment]
It's not complicated at all to save given that it's just another JS library.  The complications would arise from using our own, less proven library.  As long as we can parse the blocks, it's fine.

**Comment by robinp7720** [comment]
These apis wont work. We are saving a block based project. We're not converting css and html to json.
We are converting a block project to json.

**Comment by matthewr6** [comment]
...
You don't understand.
We convert the blocks to JSON **AND CONVERT THE JSON TO HTML AND CSS**.

**Comment by an-OK-squirrel** [comment]
I still don't like it

**Comment by robinp7720** [comment]
but your api doesnt support the blocks part. What else do you not get about this api?

**Comment by an-OK-squirrel** [comment]
Oh and I thought you were doing the backend :P

**Comment by robinp7720** [comment]
can we just tick to my idea without the combined header and body first?

**Comment by matthewr6** [comment]
1.  It's not an API
2.  Yeah, we write the parser
3.  I have experience frontend and backend :P
4.  No, we can't just "stick to an idea" without everyone's input.

**Comment by an-OK-squirrel** [comment]
I'll modify it a bit, but sure.

**Comment by quat1024** [comment]
> can we just tick to my idea without the combined header and body first?

There's \* **no reason** \* to have a split head and body. With them split you can do weird crap like this http://scratchblocks.github.io/#html%20%3A%3Ahat%20events%0Ahead%20%3A%3Acstart%20control%0A%3A%3Acend%0Ahead%20%3A%3Acstart%20control%0A%3A%3Acend%0Ahead%20%3A%3Acstart%20control%0A%3A%3Acend%0Abody%20%3A%3Acstart%20control%0A%3A%3Acend%0Ahead%20%3A%3Acstart%20control%0A%3A%3Acend%0Abody%20%3A%3Acstart%20control%0A%3A%3Acend%0Abody%20%3A%3Acstart%20control%0A%3A%3Acend

**Comment by an-OK-squirrel** [comment]
That's what I've been saying the entire freaking time :P

**Comment by matthewr6** [comment]
There's a reason I'm suggesting the use of the HTML/JSON parsers!  Using them, we can actually parse the JSON into HTML so the end user is able to download and open their project.

No idea where the head/body thing is coming from, though :P

**Comment by an-OK-squirrel** [comment]
We can do that ourselves!

**Comment by robinp7720** [comment]
You can do the same with html
I could do

``` html
<html>
<head><head><head>

</head></head></head>
</html>
```

**Comment by an-OK-squirrel** [comment]
Yeah, but it's stupid and we don't want people to misuse it. :P

**Comment by robinp7720** [comment]
I'd rather have one block less to worry about when saving projects. We could however just convert your dual block into my example on save. And when it the edtor sees the two blocks after each otherm it'll just combine them

**Comment by PullJosh** [comment]
The goal of elemental is to teach people how to write good code - not to be as extensive as HTML. There's no point letting people do stupid things. They might think that what they are doing is correct, and thus learn the wrong way.

**Comment by an-OK-squirrel** [comment]
> The goal of elemental is to teach people how to write good code - not to be as extensive as HTML. There's no point letting people do stupid things. They might think that what they are doing is correct, and thus learn the wrong way.

**Comment by matthewr6** [comment]
Yup.
What do you think about my HTML/JSON linked libraries?
Also the CSS/JSON one (which we're probably going to use)

**Comment by robinp7720** [comment]
This should be an easy to use block ide. You can do stupid things with scratch. It they were carefull about it, alot of blocks wouldnt exist within scratch

**Comment by an-OK-squirrel** [comment]
Doing that will make us use their format, and not one made better for Elemental.

**Comment by robinp7720** [comment]
@Firedrake969  Basicly everyone agreed to not using your libraries. The css one is also useless. We need to save BLOCK data

**Comment by an-OK-squirrel** [comment]
And quoting you..

> No, we can't just "stick to an idea" without everyone's input.

**Comment by matthewr6** [comment]
@robinp7720 I have no clue what you're trying to say.
@an-OK-squirrel The best format is a format easy to convert to and from HTML
@robinp7720 Where does PJ say that?  What about quat1024?

Trying to have you guys understand where I'm coming from, and how tested, currently usable stuff is almost always better than stuff we write on our own to do the same thing.

**Comment by an-OK-squirrel** [comment]
This is pretty much turning into a flame war tho :P

**Comment by robinp7720** [comment]
an-ok-Squirrel said:I vote robin's, We can do that ourselves!

We dont need to convert from json to html. Just from out save format to html and css

**Comment by quat1024** [comment]
> This should be an easy to use block ide.

Which is why we shouldn't allow people to get confused, and do stupid stuff like nest multiple `head`s.

**Comment by an-OK-squirrel** [comment]
So combined head and body it is! :P

**Comment by robinp7720** [comment]
@quat1024  I said we could use my save format and just display it in a combined.way

**Comment by matthewr6** [comment]
robin..
WE ARE NOT CONVERTING HTML TO JSON.  For the last time.
We save as JSON for the editor to read, and let the JSON be converted to HTML so the user can display their site once downloaded

**Comment by an-OK-squirrel** [comment]
@robinp7720 That would be hecka hard to compile.

**Comment by matthewr6** [comment]
@an-OK-squirrel which is why I suggested those libraries xD

**Comment by an-OK-squirrel** [comment]
Yes, but we should design the JSON format, not some other person who doesn't know what we need.

**Comment by matthewr6** [comment]
The JSON is based off of HTML.  That's all we need - basing things off of HTML.  That's the whole point of this project.

I shall now summon PullJosh for his input...
@PullJosh

**Comment by robinp7720** [comment]
@an-OK-squirrel No it wouldnt, it would only display it on the editor combined. Notthing would change to my save method.

@Firedrake969 I believe to read my message incrorect. We dont need to convert from html to json. Only from my save method to html

**Comment by PullJosh** [comment]
====== Everybody calm down =======

I have no idea what you guys are trying to say, but it makes no sense.

I'm going to close this for 5 minutes and I want everyone who was arguing to read through all the posts and consider what the other people were trying to say - really consider it. Think about their perspective and what they might have meant. In five minutes, I'll reopen, and you all can carry on discussing.

**Comment by matthewr6** [comment]
Sorry, it's kind of hard to understand what you're trying to say sometimes... (meant for robin)
But I believe you're saying exactly what I've been saying.

**Comment by Firedrake969** [comment]
ninja'd dang it

**Comment by an-OK-squirrel** [comment]
Good. I have to east :P

**Comment by quat1024** [comment]
:fire: :fire: :fire: :fire: :fire: :fire: :fire: Dis flame war doe

**Comment by an-OK-squirrel** [comment]
I've considered what people say the entire time. I genuinely believe that combined head/body is better :P

**Comment by Firedrake969** [comment]
this is nothing close, imo.
that given, we don't want to get in a real one.
I have no idea what you mean, @an-OK-squirrel, since neither suggestion had anything to do with it?

**Comment by PullJosh** [comment]
===== Can you people not read? ====

**Comment by an-OK-squirrel** [comment]
Lol :P

**Comment by an-OK-squirrel** [comment]
No, I can't!

**Comment by an-OK-squirrel** [comment]
What I'm saying is that instead of having a head block and a body block, have them both combined.

**Comment by PullJosh** [comment]
Please don't comment until I unlock the issue.

**Comment by an-OK-squirrel** [comment]
Okay, but I won't be on for a few hours.

**Comment by matthewr6** [comment]
I need to reply to this - I just realized we're all just really confused.
@an-OK-squirrel That's exactly what we're doing!  We just write the JSON based on the blocks.  The blocks only need to allow one head and one body - the user will never be able to have one, even thought JSON has the _capability_.

**Comment by PullJosh** [comment]
Ended up being six minutes. :3

Feel free to continue discussion, but _keep it constructive_. There's no reason to argue when, instead, we can have meaningful conversations.

**Comment by quat1024** [comment]
Pulljosh for president, best moderator 2k15

**Comment by PullJosh** [comment]
xD

**Comment by PullJosh** [comment]
I'm probably younger than most of you guys too. :P

**Comment by robinp7720** [comment]
Json is an object description language. Not a markup languauge. The object has to describe the scripts, not the html.
I think thats where your getting confused. When saving the project they should be saved as An Elemental file type, which should be a zip which contains json files.

When exporting to html, we can write a parser which will convert my json save file into html. This is fairly easy to do.

Yes we can add a combined head and body block but it should still be possible to have two headers or two bodies. Yes this shouldn't be done but it is a block based frontend web ide. We shouldn't be limiting ourselves.

The problem with the library you suggested is not that it doesnt convert html to json and json to html but that it wont save Elemental block projects. We need to be able to save the position of every block and script in a file and not convert json to html.

Really @PullJosh ? I'm 14 :p

**Comment by an-OK-squirrel** [comment]
I'm probably the youngest here, bu don't tell anyone :p

**Comment by an-OK-squirrel** [comment]
@robinp7720 I remember that PJ said that we shouldn't support bad practices. So if we do that we're doing blink and marquee too :P

**Comment by quat1024** [comment]
14yo club represent B)

OK! As a continued discussion from issue 1:

> Yes we can add a combined head and body block but it should still be possible to have two headers or two bodies. Yes this shouldn't be done but it is a block based frontend web ide. We shouldn't be limiting ourselves.

Well, because it is technically syntactically-valid doesn't mean that it should be possible. Remember that this is a tool for _beginners_, who have likely never seen HTML before. Since every (sane) HTML page includes one `<html>` tag containing one `<head>` and one `<body>` tag, it makes sense to me to just have all that ready for the user when they create a new html file, and to make it impossible for them to accidentally create another `<body>` tag.

Kinda like in Scratch, where it's impossible to add a `move <touching color [red]> steps` block (except through JSON hacking). Pretend the `touching color` block does fit in a `move (10) steps` block - that doesn't mean it makes sense.

**Comment by an-OK-squirrel** [comment]
@quat1024 Exactly!

**Comment by PullJosh** [comment]
Quite unrelated, but I'm 13, for those who are wondering.
<sup><sub>And a half.</sub></sup>

**Comment by an-OK-squirrel** [comment]
I'm younger :P

**Comment by quat1024** [comment]
Does this mean we can say Elemental is created by kids, for kids? :^)

**Comment by an-OK-squirrel** [comment]
Haha, yep!

**Comment by PullJosh** [comment]
Sure! We count as kids!

(Though I'm not sure if that would boost our perceived intelligence or not. :P)

**Comment by an-OK-squirrel** [comment]
Lol

**Comment by an-OK-squirrel** [comment]
I know this is unrelated, but why do people say 2k15? It's still 4 characters :P

**Comment by PullJosh** [comment]
2 c0nfuse the n00bs m8

**Comment by an-OK-squirrel** [comment]
K m80

**Comment by an-OK-squirrel** [comment]
Anyways, I'm going to write a draft of the WSF based on all the ideas here.

**Comment by PullJosh** [comment]
Okay! I'll do a temporary close so that people won't keep adding ideas. Will reopen once you're finished.
(Closing should make your life easier.)

**Comment by an-OK-squirrel** [comment]
Thanks m8! Beware, might take a while.

**Comment by PullJosh** [comment]
k m80 ill w8

**Comment by an-OK-squirrel** [comment]
Oh yes, one thing?
Can't there be a better place than the wiki for this?

**Comment by PullJosh** [comment]
Sure! Feel free to make one. :)

**Comment by an-OK-squirrel** [comment]
How about a commented json?

**Comment by an-OK-squirrel** [comment]
![pjmod](https://cloud.githubusercontent.com/assets/12722625/8890333/8ab8b9da-32c3-11e5-874e-cba38cf05359.png)

**Comment by quat1024** [comment]
:heart:

**Comment by PullJosh** [comment]
[That's one of my favorites](http://pulljosh.x10.mx/blog/online-presence/), too.

**Comment by PullJosh** [comment]
Though you did just imply that I can fly, which is cool.

I like flying.

**Comment by an-OK-squirrel** [comment]
I know it is, I found it on your site xD

**Comment by PullJosh** [comment]
:P

**Comment by an-OK-squirrel** [comment]
I'm looking at some of the programming comics instead of working.

**Comment by PullJosh** [comment]
Just realised this is still closed. :P

**Comment by robinp7720** [comment]
I still think that we should allow html tags inside of the c block as it would limit advanced users. There is no harm in doing so

**Comment by quat1024** [comment]
> I still think that we should allow html tags inside of the c block as it would limit advanced users. There is no harm in doing so

Do you mean, like, typing in custom html tags?

If we have every html tag in the dropdown, we don't need to allow typing. But something like a dropdown that also lets you type in stuff into it yeah nice

**Comment by an-OK-squirrel** [comment]
Yeah, I'm going to go back to working now. Seeya :P

**Comment by an-OK-squirrel** [comment]
Basically what that means is that I'm not listening to any  of the suggestions from now to when I finish it.

**Comment by PullJosh** [comment]
Which was why I closed this. (Looking at you, @quat1024. :3)

**Comment by an-OK-squirrel** [comment]
gosh I really have to stop looking at programming comics

**Comment by PullJosh** [comment]
Just want to give everyone a quick heads-up: I updated the project goal in the `readme` to better explain what we're trying to do with Elemental. Please read it, and keep the goal in mind when making design decisions.

> The goal of Elemental is to act as a bridge between Scratch and front-end web technology. Any and all design decisions will focus on teaching how to write clean, easy-to-read, valid front-end code. There should be as little opportunity for error as possible, thus bridging the syntax gap. Users of Elemental should not be expected to continue using Elemental once they become advanced users. Instead, they should be encouraged to convert to text-based code, for a quicker, more powerful, and more extensible coding experience.

**Comment by an-OK-squirrel** [comment]
Yes! Closing this and working now.

**Comment by matthewr6** [comment]
Robin, you're misunderstanding me and getting confused.
I keep saying that we already decided to have the zip with the actual HTML/CSS and then the json for the project editor.  The library is NOT meant to convert the blocks - it's just for HTML/JSON parsing.  What part do you not understand?  :/  You're trying to say mostly what we've already said, making it seem like you haven't read through any of the previous issue at all, though I may be wrong.

You keep mentioning "your" format - what makes you think we're using it?  We're just trying to persuade each other here xD

Anyways.  Hope you guys all see what I'm getting at - purely the back-and-forth conversion of HTML/JSON so the user can open up their project in a browser after someone writes the block parser to the JSON format.

about age - I won't disclose my age, but you should be able to get a good idea if you've read my Scratch stuff before (About Me/What I'm Working On) and have seen my other accounts on the Internet.

**Comment by robinp7720** [comment]
@Firedrake969 Of course we would be using a zip to save the exported files.but we cant use it for what you want to use it. We need to save block positions within the project.

**Comment by matthewr6** [comment]
Not really given that there's only one overarching position per page, and that's the HTML/head/body one.
Of course you're saying that we're using a zip - we already decided!

**Comment by robinp7720** [comment]
@quat1024 No I was relating to another suggestion I made about categorized tag blocks/operators.
So instead of a hard to find tag inside of a list, we would be using the block category pane to sort tag blocks/operators.

**Comment by matthewr6** [comment]
Actually, know what we should do?
Drop this.  Come back to it later once we get the actual blocks working, since that part is _kind of_ important to the editor...

**Comment by robinp7720** [comment]
@Firedrake969 Yes for now we could do it your way but honestly, may way would support every way of creating a certain layout. Your way doesnt really care about the position of the blocks thus the saved project isn't the project you wanted to save.

While your method is easier for humans to read, my method is easier for compiling and viewing within the block editor.

**Comment by matthewr6** [comment]
There is only one position - where the head/body tag grouping is.  Anything else is superfluous.  It's like putting HTML tags before the DOCTYPE declaration or after the closing html tag.

Also, we can just add X and Y coordinates to the JSON object if we really really want the precise position.  "My" and "your" methods have nothing to do with readability since humans should never need to see the JSON unless they're the developers, lol

anyways I'm going to lock this because I think it's a waste of time until we can actually get blocks working, and it'd be better for everyone to spend their time elswhere for now

**Comment by robinp7720** [comment]
@Firedrake969 ! I fully agree :) We dont need to save projects until we actualy have the editor complete. Then You (or me) will see if your or my way is better :)

I have started create a simple outline in my fork of the way we could handle blocks. Its not final though

**Comment by an-OK-squirrel** [comment]
guys, I closed the issue for a reason

**Comment by matthewr6** [comment]
I'm locking it too :P

**Comment by an-OK-squirrel** [comment]
I don't want a lock.

**Comment by matthewr6** [comment]
Leave it.

**Comment by an-OK-squirrel** [comment]
:/

**Comment by an-OK-squirrel** [comment]
Whatever, it's  not a big deal. I just feel that it doesn't do anything since we're all collaborators.

**Comment by matthewr6** [comment]
It was mainly robin arguing with me, so I was just shutting it down.

**Comment by an-OK-squirrel** [comment]
kk, also check out #46

**Comment by an-OK-squirrel** [comment]
GUYS. STOP ADDING TO THE WIKI, PLEASE

**Comment by PullJosh** [comment]
You mean to just your page, right?

We can add to all the other wiki pages, if need be?

**Comment by an-OK-squirrel** [comment]
Just to the the format page and block page.
