### ISSUE TITLE
Seperate tabs for HTML, CSS, JS

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#46]
Kinda like there's seperate tabs for scripts, costumes, and sounds. It'll make stuff a lot easier.

**Comment by matthewr6** [comment]
Yeah, CSS and JS should always be external files.  It'll teach users more effectively imo

**Comment by an-OK-squirrel** [comment]
YESYESYES

**Comment by an-OK-squirrel** [comment]
So, for wsf, html.json, css.json, etc...

**Comment by matthewr6** [comment]
Yup.  `js.json`?
also why does iheartradio keep playing Bad Blood?

**Comment by an-OK-squirrel** [comment]
I dunno, I'm listening to an album on bandcamp xD

**Comment by an-OK-squirrel** [comment]
Yes, js.json xD

**Comment by matthewr6** [comment]
hmmm
we could turn it into base64 encoding

**Comment by an-OK-squirrel** [comment]
No.

**Comment by an-OK-squirrel** [comment]
Seperate JSON files :P

**Comment by matthewr6** [comment]
I mean for JavaScript, I'm not sure how you'd parse JSON into JS and vice versa xD

**Comment by an-OK-squirrel** [comment]
Oh XD

**Comment by an-OK-squirrel** [comment]
Yeah, why the heck not.

**Comment by matthewr6** [comment]
k cool

**Comment by an-OK-squirrel** [comment]
That's for later, tho

**Comment by matthewr6** [comment]
yeah

**Comment by an-OK-squirrel** [comment]
Oh, what text editor do you use?

**Comment by matthewr6** [comment]
Sublime Text 3, you?
And why?

**Comment by an-OK-squirrel** [comment]
Oh but it's too expensive
Atom iz bezt

**Comment by an-OK-squirrel** [comment]
Oh wait, 3 is free isn't it

**Comment by matthewr6** [comment]
It's not expensive if you don't buy it.
it's not technically free

**Comment by an-OK-squirrel** [comment]
So you use the trial?

**Comment by matthewr6** [comment]
The unlimited trial.

**Comment by an-OK-squirrel** [comment]
What there's one of those

**Comment by BookOwl** [comment]
Didn't we already say that we were doing this a few days ago?

**Comment by an-OK-squirrel** [comment]
no ;p

**Comment by matthewr6** [comment]
Yeah, thought we did
@an-OK-squirrel yes it's unlimited free use until you're done with your trial

**Comment by an-OK-squirrel** [comment]
Oh wow, that's cool

**Comment by BookOwl** [comment]
Yes, we did in page 2 of our scratch forum

**Comment by an-OK-squirrel** [comment]
Ohhhh sorry

**Comment by an-OK-squirrel** [comment]
But this is a more official way of having it
