### ISSUE TITLE
Read me 

### ISSUE THREAD

**Issue by BookOwl** [ElementalCode/elemental#47]
What do you mean I do "weird things" @PullJosh (or whoever wrote it) ?!?

**Comment by BookOwl** [comment]
Aha! It was @Firedrake979 who wrote it!

**Comment by matthewr6** [comment]
It was me.
Put in what you do! (besides weird things that is xD)

**Comment by BookOwl** [comment]
I meant @Firedrake969 ( I have trouble remembering random digits at the end of strings for some reason...)

**Comment by BookOwl** [comment]
Ok, I will close this.

**Comment by BookOwl** [comment]
Added my job
