### ISSUE TITLE
Images not appearing on gh-pages

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#48]
If you look at the [gh-pages demo](http://elementalcode.github.io/Elemental/), the images (search icon & tiled background) aren't showing up. Why is that? (Code for: Someone fix it for me.)

**Comment by quat1024** [comment]
Fixed, thanks

**Comment by PullJosh** [comment]
Ah, that was my fault. Though I'm not sure why it was working locally... :/

**Comment by PullJosh** [comment]
Also, it's great that you removed those comments. But they're gonna come back next time I generate the CSS from SCSS. :P

**Comment by matthewr6** [comment]
lol

**Comment by quat1024** [comment]
Haha that's an scss quirk, I didn't manually do that :P

**Comment by PullJosh** [comment]
Oh, good. :P
