### ISSUE TITLE
Blocks corresponding to tags?

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#5]
HTML5 lets you create some ~~pretty~~really cool stuff (just check out Riot.js), but we probably shouldn't let people create custom tags (which you can do in "normal" HTML5).
- html
- head
- body
- meta (?)
- div
- span
- img
- link
- a
- script
- button
- input
- form

Please edit this post as well as posting a response (unless you delete something - just make it in a strikethrough)

**Comment by matthewr6** [comment]
We'll probably have to group types of HTML blocks, even (eg form-related, structure-related)

**Comment by PullJosh** [comment]
Of course! Each language will have an entirely different set of blocks that can be used. The palette selector (all the little buttons that say - in scratch - "Control", "motion", etc.) will change the ones shown to you depending on your language. Also, we might have to make it scrollable.

See [my mockup](https://cloud.githubusercontent.com/assets/5458180/8761638/18d2bdce-2d29-11e5-92ef-adc6955c1055.png) and feel free to discuss it [here](1).

**Comment by towerofnix** [comment]
@PullJosh +9001

**Comment by matthewr6** [comment]
@PullJosh I meant even further - HTML blocks would have things like "form elements" including inputs, selectboxes, textareas, and buttons.
Just to be cleaner

**Comment by PullJosh** [comment]
That's exactly what I just said. :P

**Comment by matthewr6** [comment]
Oh xD
We should probably list them here or in a `md` file so we can keep organized

**Comment by glacialcascade** [comment]
+∞

We should also allow [this](http://scratchblocks.github.io/#page%20%5Bstyle.css%20v%5D%20%3A%3Aevents%20hat%0A%5Bp%20v%5D%20%20font-face%3A%20%28font%20%5BArial%20v%5D%20%3A%3Aoperators%29%3B%20%3A%3Apen).

**Comment by matthewr6** [comment]
We'd want the font-face to be a dropdown with all other font properties (font-family, line-height, etc) in it too, probably

**Comment by glacialcascade** [comment]
[Done](http://scratchblocks.github.io/#page%20%5Bstyle.css%20v%5D%20%3A%3Aevents%20hat%0A%5Bp%20v%5D%20%20%5Bfont-face%20v%5D%3A%20%28font%20%5BArial%20v%5D%20%3A%3Aoperators%29%3B%20%3A%3Apen).

**Comment by quat1024** [comment]
Regarding that^, [how about laying them out a little more like CSS is?](http://scratchblocks.github.io/#%5Bp%20v%5D%20%3A%3Apen%20hat%0A%3A%3Apen%20cstart%0A%5Bfont-face%20v%5D%20%3A%20%5BComic%20Sans%20MS%20v%5D%20%3A%3A%20sound%0A%5Btext-transform%20v%5D%20%3A%20%5Blowercase%20v%5D%20%3A%3A%20sound%0A%3A%3A%20cend%20cap)

(Imagine the hat block and cblock are kinda merged together)

**Comment by matthewr6** [comment]
http://elementalcode.herokuapp.com/
http://elementalcode.herokuapp.com/
http://elementalcode.herokuapp.com/
:D :D :D

**Comment by quat1024** [comment]
^ ^ ^ ^ ^ FANTASTIC SITE needs no more changes we can ship b o y z

**Comment by matthewr6** [comment]
Awesome, let's!

**Comment by glacialcascade** [comment]
YAY COMIC SANS btw i like the hat-merge-with-c-thing

**Comment by quat1024** [comment]
Hmmmm but if we do that we can't do SCSS nesting

Maybe just a cblock with no hat idk

**Comment by PullJosh** [comment]
Do [what @quat1024 said](https://github.com/ElementalCode/Elemental/issues/5#issuecomment-122618000).

**Comment by ev3commander** [comment]
ElementalCode.github.io

**Comment by PullJosh** [comment]
Why are you spamming that url? I'm going to have to delete all your comments... :/

**Comment by matthewr6** [comment]
@quat1024 
I meant use SCSS for our own development, not for Elemental :P

**Comment by PullJosh** [comment]
The inception is getting to my head. :P

**Comment by matthewr6** [comment]
xD

**Comment by quat1024** [comment]
Lmao

I just realized, we could make Elemental _in Elemental_

**Comment by matthewr6** [comment]
let's not

**Comment by glacialcascade** [comment]
@quat1024 

Don't do it. Seriously.

**Comment by PullJosh** [comment]
Codepen is being redesigned using Codepen. ;)
(Actually true.)

**Comment by matthewr6** [comment]
what

**Comment by PullJosh** [comment]
https://twitter.com/katiekovalcin/status/583692270446206976/photo/1

**Comment by matthewr6** [comment]
MIGRATIONS WORK
YAY
YOU MIGHT HAVE NO IDEA WHAT I MEAN
OH WELL
HAPPY

**Comment by PullJosh** [comment]
COOL!

I HAVE NO IDEA WHAT YOU MEAN

**Comment by matthewr6** [comment]
Think we'll need a user system?  I can make one fairly quickly, I think.
btw I'm using dev branch for my own stuff, staging for dev stuff that works, and production for the real thing

**Comment by PullJosh** [comment]
It's certainly not necessary, but if you want to do it, you're welcome to.

**Comment by matthewr6** [comment]
Ok, seeing if I can set up a way to save projects.

**Comment by PullJosh** [comment]
Sounds cool! :D

**Comment by matthewr6** [comment]
better than phpMyAdmin, but man Django admin is ugly...
http://prntscr.com/7uhay4
and I am NOT creating a custom admin again :P 
we could use Grappelli...
