### ISSUE TITLE
note to self again

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#51]
give mods and admins privileges for all below them

**Comment by PullJosh** [comment]
Introducing: Windows Sticky Notes - A new and inventive way to save your ramblings without annoying all the people ever! Here's a picture of sticky notes in action (taken from my desktop, without changing anything for the picture):
![image](https://cloud.githubusercontent.com/assets/5458180/8894850/d30d4c94-3392-11e5-8754-b0a58d0b5b1d.png)

**Comment by PullJosh** [comment]
Ooh, and if you really want to, you can use my fancy [Chrome extension](https://chrome.google.com/webstore/detail/simply-do/hipnehepikeibdofmddlciccfkijjphf?hl=en)!
<sup>#shameless</sup>

**Comment by an-OK-squirrel** [comment]
OMG, I never heard of this new sorcery! Are you saying you can...
MAKE REMINDERS?

**Comment by matthewr6** [comment]
woah that's amazing
we should use something like Pivotal Tracking

**Comment by matthewr6** [comment]
Done

**Comment by BookOwl** [comment]
OK

**Comment by towerofnix** [comment]
And if you're on a Mac there's this app called Stickies!
