### ISSUE TITLE
Site admins and mods

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#52]
who deleted my far-future tag...

anyways

Post here if you want to be a mod/admin when the site is built out more, create an account on the site, and tell me the account's name.  I shall deem whether or not you are worth to be an admin or mod.

**Comment by BookOwl** [comment]
Can tell the rest of us exactly what the admins/mods would do?

**Comment by matthewr6** [comment]
I can tell, probably.
Basically moderating stuff - account/project modification/deletion/addition

**Comment by PullJosh** [comment]
Hopefully I can be admin... I started the project, and people [seem](https://github.com/ElementalCode/Elemental/issues/45#issuecomment-124859319) to [think](https://github.com/ElementalCode/Elemental/issues/45#issuecomment-124861167) I'm a decent mod. :P

**Comment by matthewr6** [comment]
No, just because.  :P

**Comment by matthewr6** [comment]
@PullJosh Also, it'd be a wee bit helpful to actually have an account :P (unless you're "aaa" or "a"?)

**Comment by PullJosh** [comment]
I don't. Just in the future. :P

**Comment by alyssarosenzweig** [comment]
@Firedrake969 I'm "aaa" and "a" simultaneously, trapped in a quantum entanglement, in between the two nicknames, but _**never**_, _**ever**_, "aa".

**Comment by matthewr6** [comment]
Oh, so it's you?

**Comment by alyssarosenzweig** [comment]
@Firedrake969 Indeed it is.

**Comment by matthewr6** [comment]
I'm sorry, but if you wish to be an admin, your name must be "aa".

**Comment by TheInitializer** [comment]
If I'm going to work on the backend I should be an admin :P

**Comment by matthewr6** [comment]
true
can't do it now tho

**Comment by an-OK-squirrel** [comment]
Can I be admin? :P

**Comment by matthewr6** [comment]
sure, just give me your account name
btw @TheInitializer you might want to make a new account since you can now use - and _ in your name

**Comment by an-OK-squirrel** [comment]
I think I was supersquirrel.

**Comment by matthewr6** [comment]
btw I can always change your username

**Comment by an-OK-squirrel** [comment]
I'll make a new one :p

**Comment by an-OK-squirrel** [comment]
I forgot my pass, so delete the account

**Comment by matthewr6** [comment]
no your pass is now "password" without caps

**Comment by an-OK-squirrel** [comment]
wat

...

**Comment by an-OK-squirrel** [comment]
I wanted a dash in the account name anyways

**Comment by matthewr6** [comment]
change it [here](http://elementalcode.herokuapp.com/accounts/settings)

**Comment by matthewr6** [comment]
I'll change your username, just post what you want it to be

**Comment by an-OK-squirrel** [comment]
no

**Comment by an-OK-squirrel** [comment]
I'm making a new account.

**Comment by an-OK-squirrel** [comment]
Actually, I'm generating a password in python

**Comment by matthewr6** [comment]
fine k but don't forget it again

**Comment by an-OK-squirrel** [comment]
I'm writing it down xD

**Comment by matthewr6** [comment]
ok :P

**Comment by an-OK-squirrel** [comment]
it's like 40 chars long :p

**Comment by matthewr6** [comment]
Ok

**Comment by an-OK-squirrel** [comment]
:p

**Comment by an-OK-squirrel** [comment]
Darn!

**Comment by an-OK-squirrel** [comment]
There's already a super-squirrel account

**Comment by an-OK-squirrel** [comment]
It worked, nvm

**Comment by matthewr6** [comment]
welcome the newest admin to the team

**Comment by an-OK-squirrel** [comment]
:P

**Comment by matthewr6** [comment]
http://elementalcode.herokuapp.com/admin

**Comment by an-OK-squirrel** [comment]
you mean....
I have to type in my obscenely long password

AGAIN

**Comment by matthewr6** [comment]
yes

**Comment by matthewr6** [comment]
hey want something to do?

**Comment by matthewr6** [comment]
https://github.com/ElementalCode/Elemental/pull/75

**Comment by an-OK-squirrel** [comment]
kk

**Comment by an-OK-squirrel** [comment]
DARNIT

I typed it in wrong again

**Comment by matthewr6** [comment]
press #75's button please

**Comment by an-OK-squirrel** [comment]
It's not working :p

**Comment by an-OK-squirrel** [comment]
I know I typed it in right :p

**Comment by matthewr6** [comment]
facepalm
want me to change pass?

**Comment by an-OK-squirrel** [comment]
Sure!

i hate myself :p

**Comment by an-OK-squirrel** [comment]
WAIT NO

**Comment by matthewr6** [comment]
ok haven't done it yet

**Comment by an-OK-squirrel** [comment]
Actually, yes

**Comment by matthewr6** [comment]
ok it's now password
go to /accounts/settings to change it

**Comment by an-OK-squirrel** [comment]
Kthx

**Comment by an-OK-squirrel** [comment]
what the heck?

Still can't admin :P

**Comment by an-OK-squirrel** [comment]
or log in at all :p

**Comment by matthewr6** [comment]
...

**Comment by an-OK-squirrel** [comment]
I think it's a problem with server, making test acc

**Comment by matthewr6** [comment]
I logged in as you...
http://prntscr.com/85t80p

**Comment by an-OK-squirrel** [comment]
WHAT THE HECK

**Comment by matthewr6** [comment]
try again?

**Comment by an-OK-squirrel** [comment]
I'm on a test accc

**Comment by an-OK-squirrel** [comment]
Hm...

**Comment by an-OK-squirrel** [comment]
change testguy's pass

**Comment by matthewr6** [comment]
go to /logout and then log in to /admin with super-squirrel and password (which is password)

**Comment by matthewr6** [comment]
I have to go for now

**Comment by an-OK-squirrel** [comment]
okay

**Comment by an-OK-squirrel** [comment]
THanks

**Comment by TheInitializer** [comment]
darnit guys, I'm turning off email notifications

**Comment by TheInitializer** [comment]
made an account - admin pls

**Comment by an-OK-squirrel** [comment]
you should have before

**Comment by matthewr6** [comment]
@TheInitializer done
who is kaj

**Comment by TheInitializer** [comment]
Not me :P

**Comment by TheInitializer** [comment]
Can we use Django-suit for the admin theme :P

**Comment by matthewr6** [comment]
I prefer flat :L
also let's make kaj a ghost account for people to wonder about xD

**Comment by TheInitializer** [comment]
We can make Django-suit flat... :P It has so much more functionality

**Comment by matthewr6** [comment]
I like developing my own things though :P

**Comment by TheInitializer** [comment]
And WHAT HAVE YOU DONE TO THE USERS TABLE
IT DOESN"T HAVE ME IN IT (no pun intended)

OR YOU
IT JUST HAS FIREDRAKE969

IT ALSO DOESNT HAVE ANOKSQUIRREL

**Comment by an-OK-squirrel** [comment]
I am super-squirrel

**Comment by TheInitializer** [comment]
IT ALSO DOESN"T HAVE SUPERSQUIRREL

**Comment by an-OK-squirrel** [comment]
Kaj is me, and it was a ghost account for people to wonder about :p

**Comment by an-OK-squirrel** [comment]
But i'm logged in....

**Comment by TheInitializer** [comment]
http://i.imgur.com/KKMXaZB.png

**Comment by an-OK-squirrel** [comment]
I saw that.

WHAT THE HECK

**Comment by TheInitializer** [comment]
IKR

WHAT HAVE YOU DONE FIREDRAKE

**Comment by an-OK-squirrel** [comment]
xD
What do you want to do with kaj?

**Comment by an-OK-squirrel** [comment]
![asddf](https://cloud.githubusercontent.com/assets/12722625/9318247/850111da-4507-11e5-97f5-3af88694bbbb.png)

**Comment by TheInitializer** [comment]
Delete it probably

**Comment by PullJosh** [comment]
I suppose at some point I should make an account. :P

**Comment by TheInitializer** [comment]
Lol firedrake, where are the accounts stored if not in the db?

**Comment by an-OK-squirrel** [comment]
PJ, make one and I'll admin you

**Comment by TheInitializer** [comment]
If you show up, that is

**Comment by TheInitializer** [comment]
Might be some sort of backend cache, try clearing that fd

**Comment by an-OK-squirrel** [comment]
xD

**Comment by PullJosh** [comment]
@an-OK-squirrel Did I make it?

**Comment by TheInitializer** [comment]
we exist in the pulldown menus though... http://i.imgur.com/6E2B7xd.png

**Comment by an-OK-squirrel** [comment]
Make one!

**Comment by an-OK-squirrel** [comment]
What's your username?

**Comment by matthewr6** [comment]
wait what's going on

**Comment by an-OK-squirrel** [comment]
I dunno, just pretending I know what I'm talking about.

**Comment by matthewr6** [comment]
http://prntscr.com/85ttn7
you can't see admins if you're a mod btw

**Comment by an-OK-squirrel** [comment]
Oh.

**Comment by TheInitializer** [comment]
??

**Comment by PullJosh** [comment]
I _should_ be PullJosh.

**Comment by an-OK-squirrel** [comment]
But i'm an admin. :P

**Comment by TheInitializer** [comment]
Same. Otherwise I would be able to see myself :p

**Comment by an-OK-squirrel** [comment]
:p

**Comment by TheInitializer** [comment]
Or can you not see mods if you're a mod :P

**Comment by an-OK-squirrel** [comment]
What.

Anyways.... MAKE ME AN ADMIN OR KAJ WILL ATTACK

**Comment by matthewr6** [comment]
Works as expected for me... :/  You can't see anyone at your same perm level

**Comment by PullJosh** [comment]
Did I sign up or do I not know how to fill out a form?

**Comment by an-OK-squirrel** [comment]
What the heck why not

**Comment by matthewr6** [comment]
don't want you demoting other admins

**Comment by an-OK-squirrel** [comment]
meh

**Comment by an-OK-squirrel** [comment]
how did you know

**Comment by matthewr6** [comment]
haha

**Comment by an-OK-squirrel** [comment]
Can you make us visible but not editable?

**Comment by TheInitializer** [comment]
Yeah that's how it should work

**Comment by PullJosh** [comment]
^ this

**Comment by an-OK-squirrel** [comment]
> ^ this

**Comment by matthewr6** [comment]
NO
yeah sure but not today - probably tomorrow

**Comment by an-OK-squirrel** [comment]
DARNIT

I edited kaj and I can't see him

**Comment by TheInitializer** [comment]
> > ^this

**Comment by matthewr6** [comment]
On second thought why would you need to see another mod/admin's stuff (email, password, that's all) at all?

**Comment by PullJosh** [comment]
# **_HOLD YOUR HORSES**_

**_If anyone can see people's passwords, you're doing it wrong.**_

**Comment by TheInitializer** [comment]
No, Django hashes them and doesn't store the raw passwords

**Comment by PullJosh** [comment]
Good.

But then I'm a bit confused by this:

> On second thought why would you need to see another mod/admin's stuff (email, **_password**_, that's all) at all?

**Comment by TheInitializer** [comment]
because firedrake's a Django n00b

**Comment by PullJosh** [comment]
But he can't possibly screw things up bad enough to store raw passwords, right?

**Comment by TheInitializer** [comment]
Not unless he's really stupid

**Comment by PullJosh** [comment]
Would you take a minute just to check?

96.3% he didn't do it the wrong way, but it's definitely a big enough deal to be worth a look.

**Comment by TheInitializer** [comment]
Ok, looking in the dev branch

**Comment by PullJosh** [comment]
Thanks. :)

**Comment by matthewr6** [comment]
Lol I meant hashed passwords but I was lazy
Yes they are hashed

**Comment by PullJosh** [comment]
Okay, good. :3

**Comment by PullJosh** [comment]
Once you're done, we should get some ATers to try and break it.

**Comment by TheInitializer** [comment]
It uses the default built-in Django system
Yay we're safe

**Comment by an-OK-squirrel** [comment]
xD yes

**Comment by matthewr6** [comment]
It's not like opensprites which uses ugly php

**Comment by TheInitializer** [comment]
And Django automatically protects against everything so I don't think it could be easily broken

**Comment by TheInitializer** [comment]
@Firedrake969 ikr

**Comment by PullJosh** [comment]
BTW, did my account show up? I entered a username & pass and clicked the <sup><sub>(look im a)</sub></sup> button, but nothing actually appeared to happen. :P

**Comment by an-OK-squirrel** [comment]
Oh yeah, random question..


how do I monitor network traffic from my kindle? delete this cuz it's unrelated

**Comment by matthewr6** [comment]
Also about my question - why would you need to see emails and stuff of other mods/admins?  (Unless it's an admin seeing a mod)

**Comment by PullJosh** [comment]
You wouldn't. But you should at least know which other users are still on the same level as you (even if all you see is usernames)

**Comment by TheInitializer** [comment]
just to acknowledge that they exist?

**Comment by an-OK-squirrel** [comment]
yep

**Comment by TheInitializer** [comment]
and pulljosh, you don't seem to exist yet. try again :P

**Comment by PullJosh** [comment]
I _hate_ it when I don't exist.

**Comment by an-OK-squirrel** [comment]
>

Oh yeah, random question..

how do I monitor network traffic from my kindle? delete this cuz it's unrelated

**Comment by TheInitializer** [comment]
you already posted that

**Comment by PullJosh** [comment]
@TheInitializer I tried again, but it seemed to not work again. :/

**Comment by TheInitializer** [comment]
Hm. For me it redirected to the home page and it said "hi"

**Comment by an-OK-squirrel** [comment]
I know, and wanted attention xD

**Comment by PullJosh** [comment]
@TheInitializer For me it refreshed the page.

**Comment by an-OK-squirrel** [comment]
Then you typed the wrong password, or the acc already exists

**Comment by PullJosh** [comment]
I thought that was the accnt creation.

How do I make an account?

**Comment by an-OK-squirrel** [comment]
You go to /register

**Comment by PullJosh** [comment]
oh

**Comment by TheInitializer** [comment]
lol

**Comment by an-OK-squirrel** [comment]
xD

**Comment by PullJosh** [comment]
Worked now.

**Comment by TheInitializer** [comment]
yay

**Comment by PullJosh** [comment]
A link to the register page should probably be added to the home page. :3

**Comment by an-OK-squirrel** [comment]
xD

**Comment by TheInitializer** [comment]
adminified you pj

**Comment by PullJosh** [comment]
Yay! :D

**Comment by an-OK-squirrel** [comment]
xD

**Comment by an-OK-squirrel** [comment]
FD, deadmin Kaj

**Comment by TheInitializer** [comment]
he's an admin? lol

**Comment by PullJosh** [comment]
> Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.

whateveritis.com/admin told me that

**Comment by an-OK-squirrel** [comment]
Yeah

**Comment by an-OK-squirrel** [comment]
Well then, type in the right password

**Comment by an-OK-squirrel** [comment]
Just make a new account with something else

**Comment by an-OK-squirrel** [comment]
OK, pass is PJ user is PJ

**Comment by PullJosh** [comment]
PJ PJ didn't work either.

**Comment by an-OK-squirrel** [comment]
WAT

**Comment by PullJosh** [comment]
http://elementalcode.herokuapp.com/adminlogin/?next=/admin is the right page, isn't it?

**Comment by an-OK-squirrel** [comment]
Yeah

**Comment by PullJosh** [comment]
:/

**Comment by an-OK-squirrel** [comment]
you have to log in normally first

**Comment by an-OK-squirrel** [comment]
Make a new account

**Comment by PullJosh** [comment]
To do that first I'll have to log out.

**Comment by PullJosh** [comment]
Ah, guessed the logout url.

**Comment by PullJosh** [comment]
Still didn't work. :/

**Comment by an-OK-squirrel** [comment]
WHOA MINDBLOWN

**Comment by an-OK-squirrel** [comment]
Well, make anew account, and I'll admin it

**Comment by PullJosh** [comment]
If you want, I can make a video showing what I'm doing.

**Comment by an-OK-squirrel** [comment]
just make one and I'll admin it

but yes, do that

**Comment by PullJosh** [comment]
Making a 3rd account probably isn't the solution.

And if there's a problem, we want to adress it (rather than avoid it).

**Comment by an-OK-squirrel** [comment]
Make the video

**Comment by PullJosh** [comment]
Video: https://drive.google.com/file/d/0Bxcb7WUSJfCIWlh0Z2R1WHU5bDg/view?usp=sharing

**Comment by an-OK-squirrel** [comment]
processing ....

**Comment by PullJosh** [comment]
Can't you just download it anyway?

**Comment by an-OK-squirrel** [comment]
You seem to be doing it right...

**Comment by matthewr6** [comment]
_sigh_
I will fix things again when I get to a computer

**Comment by matthewr6** [comment]
@PullJosh login under PullJosh w/password of password

**Comment by PullJosh** [comment]
@Firedrake969 It worked! :D

**Comment by matthewr6** [comment]
Ok change your password please

**Comment by PullJosh** [comment]
Changed. (Will change to an even more secure password once the site goes "live", so to speak. For now I've got a simple one that I don't use anywhere else just in case.)

**Comment by matthewr6** [comment]
Ok

**Comment by an-OK-squirrel** [comment]
@PullJosh are you saying that normally you use the same pass more than once? 

_facepalm_

**Comment by PullJosh** [comment]
@an-OK-squirrel I have 3 passwords that I use.

1 common one I use for sites that aren't very important and 2 others for individual sites. None of them are guessable, they would have to be cracked.

But yeah, I tend to assume people are nice. It'll probably come back to bite me some day, but I'd rather assume that than the opposite.

**Comment by an-OK-squirrel** [comment]
facepalm

you're **a programmer**

**Comment by matthewr6** [comment]
Offtopic guys

**Comment by an-OK-squirrel** [comment]
Fine, but I'm going to hack you someday pj....

haha sorry

**Comment by matthewr6** [comment]
Omg h4x I can change his password and log in as him

**Comment by PullJosh** [comment]
Whose? Mine?

**Comment by matthewr6** [comment]
All of you

**Comment by PullJosh** [comment]
That's probably not a good thing.

**Comment by matthewr6** [comment]
ssshhhh :P 
That's why admins and mods have to be trustworthy.:

**Comment by an-OK-squirrel** [comment]
thanks for trusting me...

don't worry--I won't do anything until the site gets popular :3

**Comment by alyssarosenzweig** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by an-OK-squirrel** [comment]
aaaaaaa

**Comment by matthewr6** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by towerofnix** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by TheInitializer** [comment]
a<b>

**Comment by quat1024** [comment]
:a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a: :a:

**Comment by an-OK-squirrel** [comment]
:a:

**Comment by an-OK-squirrel** [comment]
</offtopic on github ahhh>

**Comment by quat1024** [comment]
aaaaaaaaaaaaaa

**Comment by an-OK-squirrel** [comment]
&lt;/offtopic&gt;

**Comment by quat1024** [comment]
Still trying to figure out how you made a blank comment :P

**Comment by quat1024** [comment]


**Comment by an-OK-squirrel** [comment]
xD wanna know?

**Comment by quat1024** [comment]
DID IT :sunglasses:

**Comment by an-OK-squirrel** [comment]
:) where?

**Comment by quat1024** [comment]
Refresh the page, it's in an edit.

**Comment by an-OK-squirrel** [comment]
I see it!

**Comment by an-OK-squirrel** [comment]
well, actually, to be more precise, I don't

**Comment by quat1024** [comment]
:stuck_out_tongue:

Apparently our blank comments are different, if I use Inspect Element on yours there's a `<p>` tag, and mine uses a `<blockquote>` tag instead. Huh

**Comment by an-OK-squirrel** [comment]
Mine I wrote a `</offtopic on github ahhh>`

**Comment by quat1024** [comment]
</offtopic>

edit: It works lel

**Comment by an-OK-squirrel** [comment]
haha

**Comment by TheInitializer** [comment]


**Comment by TheInitializer** [comment]
lol we're totally mature enough to be mods

**Comment by PullJosh** [comment]
I don't think that every one of us should be a mod/admin. :package:

**Comment by matthewr6** [comment]
> I don't think that every one of us should be a mod/admin. :package:

**Comment by PullJosh** [comment]
Probably makes me sound like a narcasist (is that the word?), but I'm pretty sure I should be a mod.

Whether I should be an admin or not is debatable.

**Comment by matthewr6** [comment]
narcissist*
and for obvious reasons I have to be a superuser (above admin status)

**Comment by TheInitializer** [comment]
Yeahlol
superuser*

**Comment by matthewr6** [comment]
what?
I wrote that :P

**Comment by PullJosh** [comment]
I'd say do @Firedrake969 as superuser, me as mod (maybe admin?), and @quat1024 as mod if he wants to.

**Comment by quat1024** [comment]
~~CAN I BE SUPERYOUZUR??~~

Not sure if I wanna be a mod, I'll probably forget to do "mod stuff" after like a week heh... PJ should totes be a mod though

**Comment by PullJosh** [comment]
Okay. Totally up to you. :)

**Comment by PullJosh** [comment]
@Firedrake969 What is the diference between mods and admins?

**Comment by matthewr6** [comment]
Admins can create/delete (please don't)/edit, mods can only edit

**Comment by PullJosh** [comment]
Ah, I see... Admin would probably make the most sense for me then.

**Comment by an-OK-squirrel** [comment]
I'm an admin because I will help with that

**Comment by PullJosh** [comment]
Hmm... Are you sure you need to be admin?

I feel like having too many admins/mods is a bad idea.

**Comment by an-OK-squirrel** [comment]
derp

**Comment by PullJosh** [comment]
Just the fact that you used "derp" is probably a bad sign for admin privileges. :P

**Comment by an-OK-squirrel** [comment]
I know. it doesn't really matter if I'm admin

owait I posted that

Rule 1: don't post stuff on github at six in the morning
