### ISSUE TITLE
TDD

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#53]
Not sure how feasible it is in this type of thing, but it'd be nice to have written tests (or if not, at least some QA testers to make sure things don't break)

I personally am trying to write as many tests as possible for the backend (eg account settings and user registration)

**Comment by towerofnix** [comment]
Not something I can really give an opinion on since I'm not working on the backend lol.

**Comment by matthewr6** [comment]
I'm talking about the frontend, but I've never done unit tests with JS (not even with Karma, though I've tried)

**Comment by alyssarosenzweig** [comment]
@Firedrake969 I haven't done any in JS, but it should be pretty easy to do with a half decent testing framework, no?

**Comment by matthewr6** [comment]
Yeah, but I've never really done any either and I'm not sure what there would be to test (um, simulate clicks and drags for blocks to connect? lol)

**Comment by alyssarosenzweig** [comment]
@Firedrake969 Yeahh..... dunno.

I've seen some pretty elaborate tests like that done, though.

**Comment by matthewr6** [comment]
sounds fun lol
