### ISSUE TITLE
What to expose in the API?

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#54]
^

**Comment by robinp7720** [comment]
Just one question: Will we be keeping the backend seperate or will we be keeping them separate with using only the api to talk with the backend? You said we would be keeping them seperate and using the api but I'm not sure if I heard correctly.

We should use a unique api-key for each user. Your doing backend, so you'll think of something like that :p

Anyways, we should expose saving and loading projects for obvious reasons. (To be able to share projects :p)

As project description, as far as I know, you want to save that within the project anyways so no need to have an api call for that.

An auth api is optional. If we want to integrate the editor directly into the backend or not.

**Comment by matthewr6** [comment]
We are not keeping them separate - we will be using the editor in the actual app, but also have an editor not connected to the backend in any way.  No need to have an API key - not sure if you know Django, but the username can act as the API key very easily (and there's no real point hiding the user's projects from other people if they're shared).

I'm mainly talking about GET requests (project data, user data, etc), because I plan to have POST requests be different.

I probably should summon @TheInitializer

**Comment by robinp7720** [comment]
@Firedrake969  You are over complicated the editor. SO we have to write two versions now! YEA, double the amount of work :p

**Comment by robinp7720** [comment]
ALso I need to show you this: https://github.com/ElementalCode/Elemental/issues/38

**Comment by matthewr6** [comment]
We are not writing two versions.  I just copy and paste everything over.
We have already discussed that and solved it.  Please don't bring up dead, irrelevant issues.  Thanks.
