### ISSUE TITLE
Site Design

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#57]
**Current demo:** http://codepen.io/PullJosh/pen/dogjOX

I talked a bit about this on the UI issue, #1, but I figured it really deserved its own topic.

The game plan, in case anyone is confused, is to have the site work a bit like scratch. There's a homepage that explains what elemental is and how it's helpful, and a link to the editor (the "UI", as I've been refering to it in the past.) That editor can be used by anyone, but projects can only be shared if you're signed up on the site.

I've made the UI, or at least a good portion of it. Now I'm beginning work on the site's homepage. I'll be using codepen so that the link at the top of this issue will _always_ point to the latest version. Feel free to check it out, and let me know what you think. :)

**Comment by matthewr6** [comment]
An explore button and/or a gallery (studio? xD) of sample projects would be nice.  Looks great so far!

**Comment by PullJosh** [comment]
Okay! :)

**Comment by PullJosh** [comment]
Do you think the six boxes towards the bottom of the page look okay? I feel like they don't really fit with the rest of the design. :/

**Comment by matthewr6** [comment]
I like them but they seem to be cut off at the bottom and the text under "what makes elemental great" is really hard to see

**Comment by PullJosh** [comment]
Yeah, padding at the bottom is going to happen once I make the site longer.

As for text color, that can be changed pretty easily. :)

**Comment by an-OK-squirrel** [comment]
I'm always amazed at your web design skillz.

**Comment by PullJosh** [comment]
I'm always amazed at how amazed people are by my web design skillz.

Then again, I'm also always amazed by basic backend stuff. xD

**Comment by an-OK-squirrel** [comment]
xD

**Comment by PullJosh** [comment]
@Firedrake969 Is the text dark enough now, or should I make it even more visible?

**Comment by BookOwl** [comment]
I was going to do this, but you can probably do a better job than me anyway.

**Comment by BookOwl** [comment]
I like the site

**Comment by matthewr6** [comment]
Same

**Comment by towerofnix** [comment]
It looks awwwwesome!

**Comment by PullJosh** [comment]
Kudos to Scratch for not loading again.

I'm calling it: they'll be down for an hour.

**Comment by PullJosh** [comment]
Hey! They're back! :P

**Comment by BookOwl** [comment]
Scratch seems to crash a lot these days...

**Comment by PullJosh** [comment]
There are a lot of people to deal with.

**Comment by an-OK-squirrel** [comment]
> Scratch seems to crash a lot these days...

**Comment by an-OK-squirrel** [comment]
So, we should make the Elemental site with Elemental and be like "Hey, you can make this with Elemental!"

**Comment by towerofnix** [comment]
Hahaha. Good luck :)

**Comment by an-OK-squirrel** [comment]
if it's hard to do, what's the point of Elemental?

**Comment by TheInitializer** [comment]
Looks beautiful :3

**Comment by an-OK-squirrel** [comment]
Hey @PullJosh, how do sites like http://quoplus.com/ work? Sorry for being unrelated but I had an idea for the site :D

**Comment by matthewr6** [comment]
Ew fancy scrolling
Probably image filters and some nifty CSS background-attachment rules

**Comment by an-OK-squirrel** [comment]
Mainly the part where you scroll through the colors.

**Comment by matthewr6** [comment]
Filters combined with background-attachment is the only thing I can think of ATM

**Comment by an-OK-squirrel** [comment]
Now I have to figure it out for something :D

**Comment by PullJosh** [comment]
I **_really**_ hate those types of sites.

It's like taking a perfectly user-friendly site and turning their scrollbar into a noodle (noodlebars are, conterary to popular belief, not user friendly.)

**Comment by PullJosh** [comment]
But if you really want to know how they work...

Some nifty CSS that probably won't work on old browsers & a bunch of jQuery plugins, probably.

**Comment by matthewr6** [comment]
@PullJosh my sentiments exactly

**Comment by an-OK-squirrel** [comment]
Basically I was going to try to make the part where you scroll through the headphone colors, except with text.

> Some nifty CSS that probably won't work on old browsers & a bunch of jQuery plugins, probably.

doesn't tell me anything :P

**Comment by PullJosh** [comment]
It tells you enough that you should know not to do it.

**Comment by matthewr6** [comment]
^
btw, check out the draggy-snappy branch.  how does it look so far?

**Comment by an-OK-squirrel** [comment]
Me? will look

**Comment by matthewr6** [comment]
It's pretty nice, you think?  :D

**Comment by an-OK-squirrel** [comment]
Haven't looked xD

**Comment by matthewr6** [comment]
please do :P

**Comment by an-OK-squirrel** [comment]
Doing it atm,,,,,

**Comment by matthewr6** [comment]
k

**Comment by an-OK-squirrel** [comment]
,,,,,

**Comment by matthewr6** [comment]
'''''

**Comment by an-OK-squirrel** [comment]
IT'S FREAKIN AMAZING

**Comment by an-OK-squirrel** [comment]
Man, I feel terrible.

**Comment by an-OK-squirrel** [comment]
I haven't contributed at all :p

**Comment by matthewr6** [comment]
lol thanks (and thanks @Airhogs777 / NN)
you can do our testing for us if you want :P

**Comment by an-OK-squirrel** [comment]
I wanna contrib

**Comment by matthewr6** [comment]
QA testing?
also find out how to parse that HTML stuff into json that
https://github.com/Jxck/html2json
 likes

**Comment by an-OK-squirrel** [comment]
QA testing?

**Comment by an-OK-squirrel** [comment]
i'll work on it someday

**Comment by matthewr6** [comment]
Quality assurance - make sure things don't randomly go **_BOOM**_

**Comment by an-OK-squirrel** [comment]
**_BOOM**_

**Comment by an-OK-squirrel** [comment]
Yeah OK i'll qa test if you want

**Comment by matthewr6** [comment]
I GOT THAT BOOM BOOM POW

yeah that and block HTML structure to JSON ( https://github.com/Jxck/html2json ) if you want a challenge

**Comment by an-OK-squirrel** [comment]
I'm trying gosh

**Comment by an-OK-squirrel** [comment]
I have an idea, but it'll take a while.

**Comment by Firedrake969** [comment]
k

**Comment by an-OK-squirrel** [comment]
I gotta figure out them syntaxes first

**Comment by matthewr6** [comment]
Ok

**Comment by an-OK-squirrel** [comment]
I find it stupid that the syntax has a text attrib and a child attrib.

**Comment by an-OK-squirrel** [comment]
Which makes EVERYTHING more confusing

**Comment by mrjacobbloom** [comment]
hey guise don't forget to add zebra to draggy-snappy 'cause I can't git http://jsfiddle.net/Airhogs777/3udf3e77/

**Comment by an-OK-squirrel** [comment]
Kk m8

**Comment by matthewr6** [comment]
k I'll do it

**Comment by an-OK-squirrel** [comment]
oh I was gonna

**Comment by matthewr6** [comment]
Srry done

**Comment by an-OK-squirrel** [comment]
nuuuuuuuuuu

**Comment by matthewr6** [comment]
@Airhogs777 ok I did it

**Comment by an-OK-squirrel** [comment]
Thx

**Comment by an-OK-squirrel** [comment]
Almost done with the team page!

**Comment by an-OK-squirrel** [comment]
so fire don't steal my job :package:

**Comment by matthewr6** [comment]
Why the package?  :P

**Comment by an-OK-squirrel** [comment]
it was supposed to be a :p

**Comment by an-OK-squirrel** [comment]
Done!

**Comment by Firedrake969** [comment]
push

**Comment by PullJosh** [comment]
Just finished the team section of the page. How does it look? http://codepen.io/PullJosh/pen/dogjOX

**Comment by quat1024** [comment]
Well, I rate 4/10 because there's no capital Q in quat1024 pls

**Comment by PullJosh** [comment]
@quat1024 Fixed. It _does_ look better that way.

**Comment by PullJosh** [comment]
With the lowercase q, I mean.

That's the better way.

**Comment by an-OK-squirrel** [comment]
Good! Makes my page look bad :p

**Comment by PullJosh** [comment]
Nice logo. :P

**Comment by matthewr6** [comment]
Hey I've done a lot of the editor too :P

**Comment by PullJosh** [comment]
@Firedrake969 If you can figure out how to say all that in two lines of text (within 160px with the font we're using), I'd be happy to change it. :P

**Comment by matthewr6** [comment]
One word:  "everything" :P 
Seriously, though, "backend and editor" basically sums up what I do

**Comment by PullJosh** [comment]
"everything" only takes one line. :P
"Back-end and Elemental Editor" works great.

**Comment by matthewr6** [comment]
ok

**Comment by matthewr6** [comment]
wait would you have put "everything" if it took up two lines lol

**Comment by an-OK-squirrel** [comment]
oh yeah, and thanks for the avatar m80

**Comment by PullJosh** [comment]
@Firedrake969 Yeah. :P

**Comment by an-OK-squirrel** [comment]
sorry but...
![1](http://imgs.xkcd.com/comics/git_commit.png)

**Comment by matthewr6** [comment]
check out my first like 100 commits to `dev`

**Comment by an-OK-squirrel** [comment]
lol yes

**Comment by Cats-United** [comment]
> it was supposed to be a :p
> - an-OK-squirrel 

Try typing in `:stuck_out_tongue:` .

**Comment by an-OK-squirrel** [comment]
i don't want to :stuck_out_tongue: .

**Comment by TheInitializer** [comment]
@xkcd thingy 
same lol :P

**Comment by PullJosh** [comment]
Is everyone okay with their job descriptions? (Particularly @an-OK-squirrel and @Airhogs777)

**Comment by mrjacobbloom** [comment]
I'd prefer my Scratch icon but otherwise yesh

**Comment by an-OK-squirrel** [comment]
I like mine xD
Of course, if I actually ever do anything I'll update it.

**Comment by infinitytec** [comment]
Where am I?

**Comment by an-OK-squirrel** [comment]
you aren't in there :p

**Comment by PullJosh** [comment]
@Airhogs777 I'll change it. ;)

@infinitytec What have you contributed?

**Comment by PullJosh** [comment]
@Airhogs777 Do you also want your Scratch username as well?

**Comment by an-OK-squirrel** [comment]
to be brutally honest, I shouldn't be on the list. I haven't done anything D:

**Comment by PullJosh** [comment]
No, but you've contributed a lot of ideas and been active in the discussions.

Also, the design looks **way** better with an even number of people. :P

**Comment by matthewr6** [comment]
What @PullJosh is saying is that you're there because dead squirrels look pretty.
k.
also @quat1024's logo looks amazing xD

**Comment by quat1024** [comment]
Yeah my logo looks super out of place when it's next to everyone else's :stuck_out_tongue_winking_eye:

**Comment by mrjacobbloom** [comment]
@PullJosh yesh please

**Comment by an-OK-squirrel** [comment]
also, @PullJosh what did you think about about/sites?

**Comment by an-OK-squirrel** [comment]
i mean about/team

**Comment by PullJosh** [comment]
@an-OK-squirrel I think I'm going to cry.

**Comment by an-OK-squirrel** [comment]
It's that bad?

**Comment by PullJosh** [comment]
Yes. Yes it is.

**Comment by an-OK-squirrel** [comment]
Not the one infinitytec made...

**Comment by an-OK-squirrel** [comment]
Can you briefly explain what's wrong with it? :p

**Comment by PullJosh** [comment]
I could have the wrong one.

I just downloaded the zip from `homepage

**Comment by an-OK-squirrel** [comment]
Ah. I think it's about/team/index.html

**Comment by an-OK-squirrel** [comment]
It has our logos in a circle that when you click on it it describes said person

**Comment by PullJosh** [comment]
I had the wrong one.

**Comment by an-OK-squirrel** [comment]
Okay. Firedrake said it was ok, so it shouldn't be that bad xD

**Comment by PullJosh** [comment]
Alright... found the right one. It's not quite as bad.

I don't even want to puke.

**Comment by PullJosh** [comment]
It seems rather unecessary though. What function does it provide for users?

**Comment by an-OK-squirrel** [comment]
A more detailed bio

**Comment by PullJosh** [comment]
Why do they care?

**Comment by an-OK-squirrel** [comment]
I dunno, why not?

**Comment by an-OK-squirrel** [comment]
Why is there a team section on the front page?

**Comment by PullJosh** [comment]
Good question. Maybe we should remove it.

**Comment by an-OK-squirrel** [comment]
But.. my child...

**Comment by an-OK-squirrel** [comment]
it's like the only thing I've done :p

**Comment by PullJosh** [comment]
The reason I added the little icons about us was essentially just proof that we all contributed. When I create a project, one of my major goals is to build up a bit of a portfolio. If I ever want to do freelance design (or other things), it would help greatly to have a list of projects I've already worked on (which is exactly why http://joshuapullen.com/ looks the way it does.) Having my name (as well as all of yours) on the page works as proof to show that it really was a project I worked on. (Same goes for everyone else, if others want to show off what they've done as well.)

The point of having an about the team section was never to tell Elemental users who we are. It's to show what we contributed to the project, in case potential (future) clients would ever want to take a look at what we've done. That's why I included a short description of what we did for the project, and nothing more.

**Comment by an-OK-squirrel** [comment]
Hm, okay.
 except that site is blank

**Comment by PullJosh** [comment]
That's because it's not done yet. :3

Because right now I'm working on the org logo and siggys.

**Comment by an-OK-squirrel** [comment]
Yeah.

I also want to freelance, with the problem that I've never done anything ever

**Comment by PullJosh** [comment]
Which is exactly why we have a tiny little bio.

**Comment by an-OK-squirrel** [comment]
makes sense i guess

Now what do i do? :p

**Comment by TheInitializer** [comment]
@an-OK-squirrel don't feel too bad, I haven't made one commit
:P

**Comment by an-OK-squirrel** [comment]
Seriously?

thanks

**Comment by towerofnix** [comment]
IT'S SO PRETTEH

Also I'm a smart person who knows things? :package:

**Comment by quat1024** [comment]
tell me what you think of this so far !!! http://quat1024.github.io/ElementalForkasdasdsad/

need to add a "gallery" template, oh and another c2a at the bottom of the page. (but I really like the features area :3 obvs we're not going to use _that_ screenshot of the editor but w/e).

oh and we need a better hero image haha. i'm just using some trendy hipster stock photo (from a placeholder image website). what should we use?

**Comment by PullJosh** [comment]
I have mixed feelings...

1) Hero Image (stock photo): Sucks. But you already said that.
2) Header text: <3 <3 <3 <3 <3 <3 <3 Soooo much better that way
3) Call to action hover: Hmm... interesting, but takes too long. Try removing the width change and only adding the... bottom thing. Whatever that's called.
4) Tooltip screenshot: <3 it. I've got an idea to improve it that's hard to put into words... I'll make a high-tech mockup later.
5) Gallery: -1/10 needs more comic sans
6) Footer: Don't like the margins added above and below when you hover over links. Not sure if that was intentional or not.
_Edit:_
7) Not a big fan of the sign up button change. Animating the original would be fine, but the new one has too much going on.
_Another edit:_
8) I like having "log in" transition to green. Keep that.

**Comment by PullJosh** [comment]
Going to fork with an updated version.

**Comment by matthewr6** [comment]
**_BRANCH**_

**Comment by matthewr6** [comment]
This is why we branch @quat1024

**Comment by PullJosh** [comment]
I'm actually just going to use codepen because github is a pain.

**Comment by matthewr6** [comment]
lol

**Comment by PullJosh** [comment]
.__.

**Comment by PullJosh** [comment]
@quat1024 Why did you switch the cta button to use flexbox? Unless you have a good reason, I'm going to remove it. It makes the code uglier (don't transform translate -50% unless you have to plz) and requires hard-coding values (min-width) in order to make things not fall apart on small screens. Hard-coding values makes everything fragile (tweaking the text in the button could break everything).

But if you have a good reason for it then that's fine.

**Comment by PullJosh** [comment]
[Here's my modification.](http://codepen.io/PullJosh/full/JdQMgq/)

**Comment by PullJosh** [comment]
^ I keep working on it, so if anything's broken, just wait a few minutes and refresh.

**Comment by matthewr6** [comment]
I think the footer should be the full width

**Comment by PullJosh** [comment]
Really? It would totally break the pattern used on the rest of the site...
<sub>(Also, @quat1024, I wasn't aware you had totally reworked my layout styles for no reason. :3)</sub>

**Comment by matthewr6** [comment]
Not really...  we don't have much of a site yet.
Also, I'm extremely averse to having a dark color for a background of a webpage.  If only for the FP, fine, but please not for the user and project pages.

Remember, this is _not_ a SPA or a fancy single-page portfolio page.  It's a site of _multiple_ webpages - meaning we want a theme that looks nice, but is usable.

**Comment by PullJosh** [comment]
Hmm... I didn't think about that. It looks great on the front page, but could look bad when users are signed in... :/

Maybe something similar to how codepen does it? They manage to make a dark background look great.

**Comment by matthewr6** [comment]
Agreed.

What I would personally do is have a brief intro to Elemental on the front page, with separate pages for About (in detail), Team, Mission, etc.  Not everything in one page - we don't want people to scroll miles just to find certain things.
Once they're signed in, we drop it and have a completely different home page with their projects, a link to the editor (differently styled of course), and possibly a gallery.

**Comment by matthewr6** [comment]
separate post so I'm not too long:
what i would do is make mockups/wireframes (in some image editor or something, not HTML and CSS) of all the pages (or at least most - home page not logged in, home page logged in, user page, project page) _before_ starting on the actual HTML and CSS of the pages.
Also, it'd be nice if login and register were different pages, but not necessary.

**Comment by PullJosh** [comment]
I have a really hard time with mockups. I can never really come up with any ideas without trying things out using code. I honestly find it easier to make a button with CSS than to draw it.

However, I'm perfectly fine with letting others make mockups and converting them to code later. I just won't be able to hop on the mockup train.

As for login and register: Why wouldn't they be?

**Comment by matthewr6** [comment]
Just because it's easier that way in Django :P  It's fine tho.
At least make all the pages before you start making any single one alone look really nice or else we'll have a lot of nice pages that have no relation whatsoever to each other.  Without mockups, it gets really easy to start making one really nice page and then realize once you're done other pages need a totally different design and everything messes up :/

I'll see if I can make a really basic mockup later

**Comment by Firedrake969** [comment]
http://prntscr.com/872j35
footer:
http://prntscr.com/872jbv

**Comment by matthewr6** [comment]
basic mockup (no login):
http://oi57.tinypic.com/2jewmx5.jpg

**Comment by PullJosh** [comment]
@Firedrake969 So basically exactly what we have right now.

Also, [this](http://codepen.io/PullJosh/full/JdQMgq/) is coming along quite nicely. Unfortuantely, the changes that @quat1024 made to the layout of the site\* seem to have caused a few weird chrome glitches where text doesn't show up until you hover over it (see login/sign up and footer).

*too much flexbox bro; most of the code you wrote did absolutely nothing except make the layout fragile

**Comment by matthewr6** [comment]
Undo it.  If it doesn't work and doesn't accomplish anything, there's no reason to keep it.  I didn't see anything that changed (just things that broke).

**Comment by matthewr6** [comment]
also logged in view:
http://oi59.tinypic.com/33ud85e.jpg

**Comment by matthewr6** [comment]
User page I would imagine being pretty sparse - either the not logged in or logged in header (and footer), the user's username/status (user, creator, mod/admin), and all of their shared projects (codepen-style)

But I really don't think we should have the team page in the home page.

**Comment by PullJosh** [comment]
@Firedrake969 I've spent the past 2 hours trying to undo it all.

... I should probably just leave now. I've reached a point where I've struggled through too much ... no. I'm not even going to describe it. I'm just going to leave now and not go on crazy rants and things.

I'll attempt to communicate tomorrow. If I try now, it will end poorly.

**Comment by matthewr6** [comment]
I mean undo it as in use the last saved thing that you can find that worked 100%.
anyways I'll make a branch for the site mockups - now in site-mockups

**Comment by quat1024** [comment]
Your layout styles were so messy, lol. Most of the classes affected everything on the page in non-descriptive ways (e.g. `centered` did actually center, but also set a max-width and padding, so I couldn't change one area without changing all of them). Also my code uses way less html tags lol. It's still somewhat of a mess but I'll clean it up soon ...

See, I like semantics. The goal at the end is to have all the classes describe exactly what the div _is_, and nothing more - no .centered, no .lightBack, etc. Makes sifting through the HTML a lot easier. It's a "hero",  not a "centered dark-background box with a background image" - ".hero" vs ".centered .darkBack .fullWidth .heroBackgroundImage", if that makes sense. ¯\_(ツ)_/¯  ofc i'm not done with that yet but _stay tuuuuuned~_

Reason for flexbox = flexbox is nice. Does all my layout for me and is pretty reliable when I change the wondow size. Have you ever tried vertically-centering something in CSS, or making a non-fixed-width evenley-spaced two-column layout, without javascript or flexbox? It's almost impossible.

The min-width isn't needed, btw, it just prevents the button from crushing when you reduce the size of the browser window. Of course it's there for a reason duhhh. Works just fine without it, until "Elemental" and "Now" decide they're going to be on 2 separate lines and it looks disgusting.

**Comment by matthewr6** [comment]
Don't write CSS for one specific page, write it for the whole site.
And PLEASE stop using the home page to display the team.  It's too cluttered already.

**Comment by quat1024** [comment]
What's wrong with having more than one CSS file? The relevant parts can later be split off into main.css, home.css, community.css, team.css, whatever :3 Sounds easier to maintain, as well. I'm getting lost in the CSS files super often because they're getting a bit... long

Re: team on the homepage: I think we can make it work, just not a really big flashy thing. Something shorter, smaller pics, smaller font... Hmm. Maybe when I finish my homework I'll get something down

**Comment by matthewr6** [comment]
Ew, no.  Just comment the sections of your CSS code.
tip... you don't have to listen but it'd be a good idea...
**stop working on the home page, and make a mockup of a user page and project page.  spending all our time on the home page distracts from the main focus (editor) and equally important focuses/foci (user and project pages)**

**Comment by quat1024** [comment]
> Just comment the sections of your CSS code.

= Larger filesizes, and longer rendering time because the browser has to sort through all the unused rules in order to find the relevant ones ???

**Comment by matthewr6** [comment]
vs a bunch of messy unorganized CSS files ( based on what I've seen so far... :/ )?  fine whatever but I will be combining them into one in the end anyways via sass

**Comment by an-OK-squirrel** [comment]
Hm.......

**Comment by matthewr6** [comment]
ok i can't write css for this it's way too disorganized :/  if I started I'd do a complete rewrite to clean everything up... :/

STOP working on the home page and start working on the user page.  We're getting so caught up in making one page look "nice" (and only for a cover page, which as it stands really doesn't fit the rest of the site's purpose/function) that we've dropped everything else.
the page is pretty, not useful.  functionality is before all else.

**Comment by an-OK-squirrel** [comment]
i'm going that hurr durr

**Comment by matthewr6** [comment]
working on the user pages? cool

**Comment by an-OK-squirrel** [comment]
It's not gonna be pretty, but apparently that's ok

**Comment by matthewr6** [comment]
just do bare bones, no colors (besides black/white) or anything.  just size, position, and responsiveness.  I can take care of the rest.

**Comment by an-OK-squirrel** [comment]
RESPONSIVENESSOHNONONONONO

**Comment by an-OK-squirrel** [comment]
I'll do that kek

**Comment by matthewr6** [comment]
ok thanks

**Comment by an-OK-squirrel** [comment]
so no colors, or any of that stuff???

ok

**Comment by matthewr6** [comment]
yeah it'll just distract you

**Comment by an-OK-squirrel** [comment]
also, making my own css file for users

it makes readable code

**Comment by matthewr6** [comment]
thank you so much for readability, at least

**Comment by an-OK-squirrel** [comment]
users.css sound good?

**Comment by matthewr6** [comment]
sure

**Comment by an-OK-squirrel** [comment]
as I said, it's going to suck

owait I didn't say that :package:

**Comment by towerofnix** [comment]
So black/white sounds nice - but I prefer monochrome, e.g. a color and white.

I actually read about it [here](http://uxmovement.com/wireframes/why-the-best-wireframe-style-is-no-style/) lol.

**Comment by infinitytec** [comment]
What should I work on (when I stop being lazy)?

**Comment by matthewr6** [comment]
user pages
home page when not logged in
home page when logged in
about page
ToS/Privacy Policy pages (mostly text)
the footer/header (also for logged in vs not logged in)
project pages

**Comment by Cats-United** [comment]
> ToS/Privacy Policy pages

Sounds like fun :P

**Comment by infinitytec** [comment]
(blah blah blah washed-out images)

**Comment by an-OK-squirrel** [comment]
use ms paint plz

Seriously, I can't see anything. use a pen

**Comment by matthewr6** [comment]
^

**Comment by infinitytec** [comment]
Opening Photoshop...

**Comment by an-OK-squirrel** [comment]
:/

**Comment by infinitytec** [comment]
How 'bout now?
![el1](https://cloud.githubusercontent.com/assets/13670462/9563822/28a1775a-4e57-11e5-8b33-0bda4cf7eee8.jpg)
![el2](https://cloud.githubusercontent.com/assets/13670462/9563825/45364986-4e57-11e5-9571-3df28afdcc70.jpg)

**Comment by an-OK-squirrel** [comment]
too messy

**Comment by infinitytec** [comment]
Just quick sketches to give me an idea for what to work with.

**Comment by an-OK-squirrel** [comment]
Well then, try it out!

**Comment by an-OK-squirrel** [comment]
Wait a second, I have a problem.

**Comment by an-OK-squirrel** [comment]
If everybody designs a different page, they are all going to look different.

We need a pre-defined margin settings and stuff.

**Comment by matthewr6** [comment]
Just a Scratch-sized preview, maybe?  480x360 (or vice versa can't remember)

**Comment by infinitytec** [comment]
Sounds right.
Agreed. We need some specs.

**Comment by towerofnix** [comment]
I like "showcased creations" more than "featured projects". :package:

**Comment by PullJosh** [comment]
+1

**Comment by quat1024** [comment]
front page should have a feature list prolly, if I look at that page, not knowing anything about elemental, just seeing stuff people made with it doesn't help me :)

**Comment by PullJosh** [comment]
Yes, but make sure that when you explain things...

Oh, never mind. I'm probably the only one who reads books about SEO and writing marketing copy anyways. I'll just fix the things that are bad. :package:

**Comment by Cats-United** [comment]
What would you consider "bad?" :package: 
Also, why's everyone using :package: these days?

**Comment by rumanti** [comment]
I am sure that everyone often post :package: by accident when they tries to type :P. Now we're posting it _intentionally_ as a joke. 

_I think._

**Comment by an-OK-squirrel** [comment]
Yes, we are. If you want, try https://gist.github.com/an-OK-squirrel/3ffc5da63f3fa94b6291 for a better :package: expirience.

**Comment by rumanti** [comment]
@an-OK-squirrel 
Lol, but great idea.
_</offtopic>_

**Comment by quat1024** [comment]
:package: is the new :stuck_out_tongue: :)

If you're wondering why, it's because typing "colon - P - enter" on Scratch makes the obligatory Advanced-Topics :stuck_out_tongue: face, but typing it in GitHub Issues autocompletes to `:package:` because of how the emoji format is on gh.

On github you can type it with `:stuck_out_tongue:`

**Comment by Cats-United** [comment]
I prefer typing :P rather than :stuck_out_tongue: :package: 
EDIT: @an-OK-squirrel ![](http://i.cubeupload.com/3VERUI.png)

**Comment by PullJosh** [comment]
@Cats-United "Bad" would be listing the features and what they do. Good would be listing ways in which the product or service helps the user (which is often linked to a specific feature... As a developer, it's easy to assume that users will instantly see how a specific feature helps them. They won't.)
