### ISSUE TITLE
How to categorize element blocks?

### ISSUE THREAD

**Issue by mrjacobbloom** [ElementalCode/elemental#58]
I'm thinking similar categories to https://developer.mozilla.org/en-US/docs/Web/HTML/Element just so we don't have one big palate with all the tags

**Comment by towerofnix** [comment]
Indeed, I agree with the above.

**Comment by PullJosh** [comment]
Looks good! Though we might want to combine a few categories (such as the first two listed). :)

**Comment by an-OK-squirrel** [comment]
Agreed!

**Comment by TheInitializer** [comment]
I like it :+1:
