### ISSUE TITLE
xyz.getSource or getSource(xyz)?

### ISSUE THREAD

**Issue by towerofnix** [ElementalCode/elemental#6]
Are we going to be using prototyping for the internal code or are we going to use functions on objects?

E.g. I could have something like this..

```
Workspace
  data
```

as my basic workspace class. Now, to get the source of it, would I have a method of Workspace, like so:

```
Workspace
  data
  getSource()
```

or would I have a function inside of `window`, like so:

```
getSource(a Workspace)
```

?

This will be handy to know when we're coding, we should absolutely always stick to one of the two ways.

**Comment by BookOwl** [comment]
I prefer xyz.getSource rather than getSource(xyz)
However, we should probably use some type of class library for implementing the objects, rather than messing with prototype. I think that we should roll our own, since then we can make sure that it has what we need and nothing that we don't. I could create it.

**Comment by matthewr6** [comment]
Definitely prototyping via a class/object/whatever they're called in JS (:P).

**Comment by towerofnix** [comment]
Haha lol kk.

**Comment by BookOwl** [comment]
working on a class library...

**Comment by matthewr6** [comment]
Well, we don't even know what properties we'll need yet, so what do you mean?

@liam4 too used to Python right now... classes, dicts, tuples, and arrays vs JS's weird yet awesome handling

**Comment by towerofnix** [comment]
Class library?

So not like so?

``` js
var Workspace = function(data) {
    this.data = data || {};
}

Workspace.prototype.getSource = function() {
    return "lol haha not implemented funny";
}
```

How else?

**Comment by matthewr6** [comment]
Yeah, how can you make that if we don't know any of our properties we're using yet?  xD

**Comment by BookOwl** [comment]
It makes it easier to do <pre>var Workspace = function(data) {
    this.data = data || {};
}
Workspace.prototype.getSource = function() {
    return "lol haha not implemented funny";
}</pre>
You instead do 

<pre>
var Workspace = CLASS.define(
   //Constructor
   function(data) {
    this.data = data || {}},
   //Instance Properties
   {
      getSource:function() {
         return "lol haha not implemented funny";
   }
   },
   //Static Properties (null == None)
   null)
var workspace = new Workspace();
source = workspace.getSource();
</pre>

**Comment by matthewr6** [comment]
I think we should do the first one, since it's the normal way to do JS objects (for now, at least).

But in any case, my question hasn't been answered...

**Comment by BookOwl** [comment]
What question?

**Comment by matthewr6** [comment]
How can you make that if we don't know any of our properties we're using yet?
Also, there's no point in starting stuff if we're still flushing out designs.

**Comment by BookOwl** [comment]
This will make it easier to create the design

**Comment by matthewr6** [comment]
Also, "messing with prototype" is only a bad idea (and only even sometimes at that) when you're playing with JS built-ins, like Array and String prototypes.

**Comment by glacialcascade** [comment]
``` javascript
testSpace.getSource();
```

**Comment by matthewr6** [comment]
``` javascript
function Workspace() {
    this.propOne = 1;
    this.propTwo = 2;
    this.function = functionHere;
}
var MyWorkspace = new Workspace();
var source = MyWorkspace.function();
```

**Comment by towerofnix** [comment]
Make sure you look at [this](http://stackoverflow.com/questions/310870/use-of-prototype-vs-this-in-javascript) if you're going to go about doing it that way.

I always use prototyping! :P

**Comment by matthewr6** [comment]
Fair enough, though I do like serialized props.

**Comment by matthewr6** [comment]
tbh, I don't think any sort of class library is useful, because "messing with prototype" isn't necessarily bad and JS's default ways are already pretty good.

**Comment by BookOwl** [comment]
<a href=https://github.com/BookOwl/class.js/tree/v1.0.0>I finished the class library</a>

**Comment by matthewr6** [comment]
So it's basically using prototyping without using prototyping... :/

**Comment by BookOwl** [comment]
Yes... That was the whole point!

**Comment by matthewr6** [comment]
I'd rather we stick with things that do the exact same thing but are native and just as easy to do natively (eg no jquery just for element selectors unless it's complicated element selection)

**Comment by BookOwl** [comment]
Ok.
