### ISSUE TITLE
Priorities

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#60]
1.  [x] Block dragging
2. [x] Basic block dragging
3. [x] Block stacks
4. [x] Grab elements from palette
5. [x] More blocks! (eg span, p, etc) _(can always add more later)_
6.  [x] Block parsing to JSON **(working on)**
7. [x] Multiple files **(working on)**
8. [x] CSS implementation
9.  [x] Saving stuff and we should be good from here on out

**Comment by quat1024** [comment]
> Block parsing to JSON

I thought we weren't doing this?

**Comment by matthewr6** [comment]
Turning the blocks into JSON? Yeah we are
either way, it's not a priority (which is why I made this issue... :P)

**Comment by BookOwl** [comment]
And I'm doing it.

**Comment by matthewr6** [comment]
yes but first someone needs to do the block snapping stuff

**Comment by BookOwl** [comment]
Well, I don't know how to do THAT. :P

**Comment by an-OK-squirrel** [comment]
I should try, but I'm not smart enough :p

**Comment by matthewr6** [comment]
Updated, we still need block wrapping and getting stuff from the palette

**Comment by an-OK-squirrel** [comment]
Ok

**Comment by matthewr6** [comment]
also check out the latest version, it's pretty awesome with scrolling and whatnot

**Comment by matthewr6** [comment]
@PullJosh How is it?  A few CSS-related bugs, I think, but everything else seems good

**Comment by PullJosh** [comment]
Of `block-editor` you mean?

**Comment by matthewr6** [comment]
yeah

**Comment by PullJosh** [comment]
Looks awesome! Only a few issues:

1) Hat block color weirdness (probably has to do with zebra?)
2) Doesn't show scrollbars when blocks are outside (or partially outside) their area. Probably a result of me being lazy (adding overflow:hidden instead of figuring out why stuff is outside of where it should be).

**Comment by matthewr6** [comment]
Yeah, I've messed around with both of those and have no idea about either of them.  I'll play with the first if you'll take care of the second.

**Comment by PullJosh** [comment]
I'll give it a shot, but I can't promise results. :P

**Comment by matthewr6** [comment]
Ok
I don't think the hat thing has to do with zebra coloring

**Comment by matthewr6** [comment]
weird thing is, if I remove the z-index on the ::after, it works (but covers text)...

**Comment by PullJosh** [comment]
O_O

**Comment by matthewr6** [comment]
Ok it works but now backgroundeither cuts off hat block or breaks all mouse events

**Comment by matthewr6** [comment]
@PullJosh ready for me to take a look?

**Comment by TheInitializer** [comment]
draggy-snappy looks pretty cool so far :P

**Comment by matthewr6** [comment]
That's outdated - the real one is block-editor

**Comment by TheInitializer** [comment]
Wow, that's even better :P I like how you can't drag the !DOCTYPE html...

**Comment by matthewr6** [comment]
Never tried having two !DOCTYPE html tags in one HTML file... xD

**Comment by PullJosh** [comment]
I never tried having one. :3
(Who needs it? Things - most of them, anyway - still work fine.)

**Comment by TheInitializer** [comment]
lol

I don't really like the roundedness of the stacked blocks; perhaps they could become non-rounded on the two left corners when they're stacked?

**Comment by PullJosh** [comment]
Hmm... I think I've got to veto that one.

Making them _less_ round could be an option, but not removing roundness entirely.

**Comment by matthewr6** [comment]
I'm fine either way, I think

**Comment by TheInitializer** [comment]
http://i.imgur.com/MmETS0O.png
IMO that looks so much better.

**Comment by PullJosh** [comment]
@TheInitializer Oooh, yeah. I didn't fully understand what you meant. I thought you were saying _all_ of the left borders would be sharp - not just the ones that are in between other blocks ("open" borders, ones with nothing above or below them, are still rounded.)

Looks great!

**Comment by TheInitializer** [comment]
thanks :P

**Comment by matthewr6** [comment]
How's everything going, guys?
@PullJosh I have a task request for you if you want

**Comment by PullJosh** [comment]
K

**Comment by an-OK-squirrel** [comment]
going pretty well!

**Comment by matthewr6** [comment]
@PullJosh Could you work on the block pane (ie [this](http://prntscr.com/814luv) but with blocks there)?

**Comment by PullJosh** [comment]
Sure! Should I do the search as well?

**Comment by matthewr6** [comment]
Yeah, go ahead.  NO SETINTERVALS THOUGH.  I'd suggest you fire the search function every time you press a key on the searchbox

**Comment by PullJosh** [comment]
Yeah, yeah. I know. :P

**Comment by matthewr6** [comment]
haha

**Comment by PullJosh** [comment]
Instead, I'll use setTimeout! :D

**Comment by matthewr6** [comment]
...
_facepalm_

**Comment by matthewr6** [comment]
also make sure you work in the block-editor branch please

**Comment by PullJosh** [comment]
No? Not that?

How about requstAnimationFrame?

**Comment by matthewr6** [comment]
no just no

**Comment by PullJosh** [comment]
Okay, and I'll use the proper branch. :3

**Comment by matthewr6** [comment]
cool thanks
also, like OpenSprites, we have automatic deployment :D

**Comment by PullJosh** [comment]
I have no idea what that is!

But it sounds exciting. :D

**Comment by matthewr6** [comment]
no need for me to do annoying stuff

**Comment by PullJosh** [comment]
Neat!

**Comment by matthewr6** [comment]
basically master branch gets pushed to heroku automatically so we just can focus on code :D
I could make a staging site if needed, I think

**Comment by PullJosh** [comment]
Oh, that's cool! :D

**Comment by matthewr6** [comment]
Also runs unit tests automatically

**Comment by matthewr6** [comment]
@PullJosh Block selection pane pls
@an-OK-squirrel How's JSON parsing stuff doing

**Comment by PullJosh** [comment]
Sorry, I'm lazy. I've been working on it, but not much.

**Comment by matthewr6** [comment]
Once you and @an-OK-squirrel finish those things, we can start project saving/previewing and cool stuff like that

also added a command to `circle.yml` so that I can change the database setup really easily without doing much :D

**Comment by PullJosh** [comment]
Thanks for the encouragement. :P

**Comment by matthewr6** [comment]
lol
seriously though - also, keep js files separate for each purpose (ie blocks, editor, parsing, etc) please.  I guess I could try the block parsing...

**Comment by PullJosh** [comment]
Any chance you could write some fancy JS that allows blocks with a specific class to duplicate rather than just move? (Basically, don't delete the blocks up above.)

**Comment by matthewr6** [comment]
I could, yeah...  That's what I plan to do with the palettes

**Comment by an-OK-squirrel** [comment]
ooh, sounds awesome! I wanna try. :P

**Comment by an-OK-squirrel** [comment]
whoops accidentally pressedclose and comment

**Comment by matthewr6** [comment]
l'ol

**Comment by rumanti** [comment]
What "CSS things" ?

**Comment by matthewr6** [comment]
Block based css
