### ISSUE TITLE
Problem with save format

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#61]
how will we deal with loose blocks or stacks of blocks?

**Comment by PullJosh** [comment]
Treat them as their own script, but make scripts not run/compile if they don't have a hat block?

**Comment by matthewr6** [comment]
Yes
Also, one hat block per HTML page/file, right?

**Comment by PullJosh** [comment]
Yep. Were we going to make those lock into place so they couldn't be moved, or is that me just making things up?

**Comment by PullJosh** [comment]
The hat blocks, I mean.

**Comment by matthewr6** [comment]
Yeah - same for CSS or no?

**Comment by PullJosh** [comment]
Hmm... I'd say so.

iirc, some people were considering using hats as the element selectors. Personally, I don't love this approach, as it doesn't really match typed CSS. Instead, there should be a hat block that just says "CSS file" on it or something (again, locked into place).

**Comment by matthewr6** [comment]
Same

**Comment by an-OK-squirrel** [comment]
Okay then

**Comment by mrjacobbloom** [comment]
another reason that we might not want CSS selectors to be hats is media queries. The best way to visualize media queries I can think of if selectors are hats is as a kind of area that the stacks can be dragged into
