### ISSUE TITLE
Somebody's kind of sour...

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#62]
:P

**Comment by towerofnix** [comment]
# DUN DUN DUN!!!!

**Comment by matthewr6** [comment]
???

**Comment by towerofnix** [comment]
Dun dun dun, as in, cinematic music.

**Comment by matthewr6** [comment]
ik

**Comment by PullJosh** [comment]
You mean the center portion of my pet kamquat?

**Comment by towerofnix** [comment]
Yeah, definitely what I mean. _Definitely._

**Comment by towerofnix** [comment]
Just kidding. :)

**Comment by towerofnix** [comment]
Or is it major!?

**Comment by PullJosh** [comment]
liam4 is never sarcastic. _never._

**Comment by TheInitializer** [comment]
um...what?

**Comment by an-OK-squirrel** [comment]
robinp made his own creating thing, "web blox"

**Comment by PullJosh** [comment]
https://scratch.mit.edu/discuss/topic/138276/

**Comment by matthewr6** [comment]
lol
his idea of vengeance or whatever is extremely amusing for some reason
he acts so competitive...

**Comment by an-OK-squirrel** [comment]
When he's not

**Comment by an-OK-squirrel** [comment]
If I don't want limits I use a text editor

**Comment by matthewr6** [comment]
lol yeah

**Comment by an-OK-squirrel** [comment]
See my latest post on the topic

**Comment by matthewr6** [comment]
k

**Comment by matthewr6** [comment]
xD

**Comment by an-OK-squirrel** [comment]
A's' 'I' 's'a'i'd',' 'H'A'I'L' 'T'E'X'T' 'E'D'I'T'O'R'S'

**Comment by matthewr6** [comment]
Added the missing punctuation for you
