### ISSUE TITLE
Compressing JSON server-side

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#63]
I'm thinking of gzipping and/or base64 encoding the JSON files just for the sake of compressed-ness.

**Comment by an-OK-squirrel** [comment]
meh

**Comment by an-OK-squirrel** [comment]
OK!

**Comment by TheInitializer** [comment]
ok, but please decompress it when it's downloaded.

**Comment by matthewr6** [comment]
yeah python can do that really easily

**Comment by alyssarosenzweig** [comment]
Errr.... base64 _inflates_ the file, not compresses it  .-.

**Comment by matthewr6** [comment]
Probably a combo then because gzipping creates really weird unicode symbols

**Comment by alyssarosenzweig** [comment]
@Firedrake969 yes, but that's the point.

**Comment by matthewr6** [comment]
Base64 encoding with gzipping does decrease size, at least.

**Comment by matthewr6** [comment]
closing for now
