### ISSUE TITLE
using classes for block types

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#64]
I'm supposed to do compiling blocks to html2json but I need a good way of figuring out which way is which.
I think using classes on the dom elements is the best idea.

**Comment by matthewr6** [comment]
We already are

**Comment by mrjacobbloom** [comment]
> We already are

**Comment by matthewr6** [comment]
> > We already are

**Comment by PullJosh** [comment]
> > > We already are?

**Comment by matthewr6** [comment]
> > > > We already are.

**Comment by mrjacobbloom** [comment]
> > > > > Wait, are we already?

**Comment by matthewr6** [comment]
> > > > > > YES.

**Comment by PullJosh** [comment]
We already are.

**Comment by an-OK-squirrel** [comment]
I mean like html tags xD

**Comment by matthewr6** [comment]
o

**Comment by BookOwl** [comment]
"I'm supposed to do compiling blocks to html2json"
I thought that I was doing this?

**Comment by an-OK-squirrel** [comment]
i thought I was.

**Comment by matthewr6** [comment]
There's a reason we're all working together and using GitHub...
And it's not because we each work on our own parts and separate from one another

**Comment by an-OK-squirrel** [comment]
mind=blown

**Comment by BookOwl** [comment]
So, who's doing it?

**Comment by an-OK-squirrel** [comment]
both of us!

**Comment by BookOwl** [comment]
@an-OK-squirrel which part do you want to work on?

**Comment by an-OK-squirrel** [comment]
@BookOwl WE can't do either until we decide if we're using classes for this or not.

**Comment by an-OK-squirrel** [comment]
If we do, I think it would be best to use a prefix beforehand to avoid confusion with other classes.

**Comment by an-OK-squirrel** [comment]
as in elemental-tag-div

**Comment by matthewr6** [comment]
sounds good, whoever wants to can do it/sort it out

**Comment by an-OK-squirrel** [comment]
I'll sort it out and do a thing

**Comment by an-OK-squirrel** [comment]
~~Hey, can we use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith ? It's not supported in safari and opera and most mobile yet.~~

**Comment by an-OK-squirrel** [comment]
oh wait

``` js
 if (!String.prototype.startsWith) {
  String.prototype.startsWith = function(searchString, position) {
    position = position || 0;
    return this.indexOf(searchString, position) === position;
  };
}
```

**Comment by matthewr6** [comment]
Cool

**Comment by an-OK-squirrel** [comment]
thanks mdn

**Comment by matthewr6** [comment]
@BookOwl @an-OK-squirrel I've already done a lot of it... :P
