### ISSUE TITLE
C-block wrapping

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#66]
Could someone work on it with me?  Can't seem to contact @Airhogs777 (he's the one that started working on it).  Code is in `c-block-wrapping` branch.

**Comment by an-OK-squirrel** [comment]
I don't see why we need this, it seemed to work fine as it is...

**Comment by matthewr6** [comment]
True - do we even want this?  @PullJosh @quat1024

**Comment by an-OK-squirrel** [comment]
It would be confusing, because you could put a c-block inside and outside of another. Completely pointless, you could just drag the other block inside :p

**Comment by matthewr6** [comment]
Yeah I don't think we need it any more

**Comment by PullJosh** [comment]
Fair enough. Having it available would be an improvement, but not by enough to warrent spending hours on it.
