### ISSUE TITLE
Write your bio in homepage

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#69]
do it :P

**Comment by matthewr6** [comment]
k did it

**Comment by an-OK-squirrel** [comment]
Darn, the issue icon got thinner.

**Comment by matthewr6** [comment]
yeah

**Comment by an-OK-squirrel** [comment]
i cry everytiem

**Comment by TheInitializer** [comment]
#69 :P

**Comment by TheInitializer** [comment]
Done ;)

**Comment by infinitytec** [comment]
Done!

**Comment by PullJosh** [comment]
Where? :3

**Comment by an-OK-squirrel** [comment]
Oh yeah, and you have to push your commits derp

**Comment by TheInitializer** [comment]
@PullJosh in the homepage branch

**Comment by quat1024** [comment]
I'll doo this sooooon

**Comment by quat1024** [comment]
OK - why is the homepage two seperate pages? I thought that was kinda odd. Normally when people do front-pages like that it's just a really tall page with everything on it.

I'll make a branch.

**Comment by matthewr6** [comment]
it's badly named.  should be "site-design"

**Comment by quat1024** [comment]
Why? The branch contains the homepage so it's called `homepage`. Seems
reasonable enough to me

**Comment by quat1024** [comment]
In my branch I'm going to rip out everything except the first page and redesign it so it doesn't use JavaScript (nobody's going to sit there and click through all the bios) edit: oh and add more flexbox (because I have a flexbox problem)

I was thinking something like this? http://puu.sh/jGt9p.png ms paint skillz 2strong

**Comment by PullJosh** [comment]
@quat1024 You've got it all correct. The goal was a single-page design (at least until they sign in).

My only concern is the link you added. I would really like to have no bios whatsoever, just what I already made (of course, this is just my opinion, feel free to argue with it.) I reccomend you read this: https://github.com/ElementalCode/Elemental/issues/57#issuecomment-131949843

**Comment by matthewr6** [comment]
What about user pages and stuff?

**Comment by PullJosh** [comment]
> The goal was a single-page design **(at least until they sign in)**.

I was only talking about the main landing page. When the user is logged out, they can view the homepage and editor. When they are logged in, they get access to a lot more pages. :)

**Comment by matthewr6** [comment]
Ok, so if they're not logged in, they only get the editor and home page?

**Comment by PullJosh** [comment]
@Firedrake969 Yep!

**Comment by an-OK-squirrel** [comment]
I hate the single page idea. Sometimes when I sign up for something I want more (say, an FAQ and stuff)

**Comment by PullJosh** [comment]
Take a look at my website, http://joshuapullen.com/ It has all the information you need on a single page (aside from the blog, of course).

Would you be okay with it if we did something like that? Or does that make you queasy?

**Comment by quat1024** [comment]
Something like that would be fab. (Probably could be a little busier than that, though, with less whitespace, idk. Pretend I've never heard of elemental before, and am looking at the site for the first time - I don't want to scroll 5 miles just to learn what is it in the first place :stuck_out_tongue: )

Ok, let me get my mspaint out again: http://puu.sh/jHp3P.png

OH and we should have a link to the community section somewhere. You shouldn't have to log in just to _view_ projects, that's pretty dumb. Imagine if you couldn't view any Scratch projects without a scratch account. Nobody would want to join :stuck_out_tongue:

**Comment by matthewr6** [comment]
The only thing you should need to log in for is sharing projects.

**Comment by PullJosh** [comment]
Looks great! :D

**Comment by PullJosh** [comment]
Except for the comic sans.

**Comment by PullJosh** [comment]
Sorry for triple post...

I'll try and make a nice-looking footer.

**Comment by PullJosh** [comment]
As always, I'm not sure what I think about [what I made](http://codepen.io/PullJosh/pen/dogjOX).

I feel like it's tolerable, but isn't great. And to make it any better, it would require totally starting over. Do you guys agree (if so, I'm willing to start over - I just want to see what you guys think first.)

**Comment by matthewr6** [comment]
what would it look like when the user is signed in?

**Comment by PullJosh** [comment]
I was thinking the same. What about you?

**Comment by PullJosh** [comment]
:OOOO I NEED TO INCLUDE THE LITTLE GREEN DOTTED LINE USED IN THE FORUM SIGGY. I MUST

**Comment by matthewr6** [comment]
yes

**Comment by PullJosh** [comment]
yes

**Comment by quat1024** [comment]
yes

**Comment by quat1024** [comment]
That footer = :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration: i'm going to copypaste that into my fork (after homework :stuck_out_tongue: )

**Comment by PullJosh** [comment]
Not sure how to deal with link hovers when the dashes get involved. What do you think it should look like?

**Comment by PullJosh** [comment]
Wait... Homework?

**Comment by matthewr6** [comment]
School.

also the gray area should only be in this part
http://prntscr.com/86nyeh

**Comment by PullJosh** [comment]
SCHOOL!?

Also, [did that](http://codepen.io/PullJosh/pen/dogjOX).

**Comment by matthewr6** [comment]
gj

**Comment by PullJosh** [comment]
@quat1024 Is the footer still :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:  :heart_decoration:?

**Comment by quat1024** [comment]
I have a good idea for the dashes - but you'll have to wait to see it because I'm hiding in my room doing "homework" :sunglasses:

**Comment by quat1024** [comment]
Yeah it's pretty :fire:

**Comment by quat1024** [comment]
Done! http://codepen.io/quat/pen/rVELaO

Ripped out the rest of the page/CSS for simplicity, and changed the `<li>`s and `<ul>`s to `<div>`s because... well, `<ul>`s are for lists :P also made it a lot simpler for me

**Comment by an-OK-squirrel** [comment]
looks great!

**Comment by towerofnix** [comment]
Pretty cool!

**Comment by PullJosh** [comment]
Hmm... I like it! However, I think it should be slightly "inside" (away from the edge) if you know what I mean.

I've added my modified version to [the original pen](http://codepen.io/PullJosh/pen/dogjOX). Let me know what you think!
<sup>And don't strip out the rest of the page next time... Makes my life harder. Thanks. :)</sup>

**Comment by TheInitializer** [comment]
[ftfy](http://codepen.io/anon/pen/LVKOGy?editors=110)

**Comment by PullJosh** [comment]
No.

**Comment by TheInitializer** [comment]
But the animations don't work in your version

**Comment by matthewr6** [comment]
yes they do what are you talking about

**Comment by quat1024** [comment]
@TheInitializer - that's odd, it works for me in chrome. what browser are you using? (also I don't like how the footer takes up 100% of the width of the page D:)

@PullJosh - :heart: niiiice ~~I get sick of scrolling down the page every time I change it though D:~~

**Comment by PullJosh** [comment]
@TheInitializer

> I don't like how the footer takes up 100% of the width of the page

@quat1024
That's fine. :P

**Comment by PullJosh** [comment]
Oh... @TheInitializer... If you're on Firefox with the codepen settings as such that the preview appears under the code, try changing it to one of the other two settings (by clicking the buttons in the bottom right). It might solve the issue. ;)
<sub>(Appears to be a codepen issue, not something that's our fault.)</sub>

**Comment by quat1024** [comment]
Or try the [full-page pen](http://codepen.io/PullJosh/full/dogjOX/)

**Comment by TheInitializer** [comment]
It works in Firefox, just not in Edge. Odd.
(I randomly switch between the two just cause)

**Comment by an-OK-squirrel** [comment]
hmmmm

**Comment by infinitytec** [comment]
Edge is IE for people who like looking at pretty things.

**Comment by matthewr6** [comment]
Edge is much better.

**Comment by TheInitializer** [comment]
> Edge is much better.

**Comment by matthewr6** [comment]
> > Edge is much better.

**Comment by TheInitializer** [comment]
> > > Edge is much better.

**Comment by an-OK-squirrel** [comment]
> > > > > > > > > > > > > > >  Edge is much better.

**Comment by towerofnix** [comment]
`<small>`safari is much better`</small>`

**Comment by an-OK-squirrel** [comment]
<small> firefox is tons better </wrkl;akfoaskfa>

**Comment by PullJosh** [comment]
IE is butter
<sub><sup>You can break it without even trying.</sup></sub>

**Comment by quat1024** [comment]
Netscape Navigator is much better.

**Comment by an-OK-squirrel** [comment]
I think mosaic is a little bit better than that though.

# `</offtopic>`

**Comment by TheInitializer** [comment]
# `<offtopic>`

no libwww's even better

# `</offtopic>`
