### ISSUE TITLE
Use GH Browser?

### ISSUE THREAD

**Issue by towerofnix** [ElementalCode/elemental#7]
Normally I just edit through the GitHub browser. :P

I was _going_ to mention there'd be a problem with uploading images because you can't(?) upload files through the browser, but hey, if we need to upload demo media we can do that later! :P

What's your opinion on using the GitHub code editor in the browser?

**Comment by PullJosh** [comment]
That's generally what I use, unless I need images or something like you mentioned. If you can learn it, I'm sure git is better, but I'm not motivated enough. :P

**Comment by towerofnix** [comment]
Yay :P

Any particular things I should get started on?

Also Gitter might be a nice thing to get.

**Comment by PullJosh** [comment]
You should probably check out [this](https://github.com/nathan/visual) and make sure it will work for our needs. Also, figure out how to use it. :P

**Comment by matthewr6** [comment]
I use Git w/Sublime, but idc how anyone codes as long as they test and know what it does before pushing.

**Comment by quat1024** [comment]
Yeah same. Plsplspls don't commit anything to the master branch without seeing what it does first.

Windows.github.com has a graphical interface if you wanna use that

**Comment by matthewr6** [comment]
Or mac.github.com for OS X.

please don't commit anything without at least a little testing, and definitely don't merge your own pull request into master without at least one person looking through it

**Comment by PullJosh** [comment]
Sounds good!

**Comment by glacialcascade** [comment]
I use Github for Windows so I can upload everything from images, sounds, to JS files, Java files, folders, and .sb2 files.

**Comment by PullJosh** [comment]
I use that, but only for images and stuff.

**Comment by matthewr6** [comment]
git ftw

**Comment by PullJosh** [comment]
Not really that important.
