### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by infinitytec** [ElementalCode/elemental#70]
Any plan for this?
Maybe Advanced Mode could just be a separate translation?

**Comment by PullJosh** [comment]
You mean real-language translations, right? (Not programming language ones)

If so, I'd say that's something to leave for later. I doubt many non-english speakers will use the tool anyway.

**Comment by infinitytec** [comment]
Figured as much.

**Comment by an-OK-squirrel** [comment]
plus, isn't html english anyways? :P

**Comment by PullJosh** [comment]
Yeah, but we could convert the blocks to something else if we needed to.

But then that'd make it even harder to transition from Elemental to HTML. Yeah... no translations.

**Comment by towerofnix** [comment]
But maybe translations for the docs if we make any?

**Comment by an-OK-squirrel** [comment]
Yeah, sure
