### ISSUE TITLE
Why numbered palettes?

### ISSUE THREAD

**Issue by towerofnix** [ElementalCode/elemental#71]
Why used numbered palettes (for example, `1` means formatting, or whatever) when we could use labelled palettes (so `"formatting"` means formatting)?

I assume we're currently using numbered pallets because [this](https://github.com/ElementalCode/Elemental/blob/palette-dragging/resources/js/blockFilter.js#L54).

Just my opinion. Feel free to share your own.

**Comment by PullJosh** [comment]
The numbers are just for our purposes (they will never display in the Elemental editor).

You can see which palettes correspond to which number by checking the position in [this array](https://github.com/ElementalCode/Elemental/blob/palette-dragging/resources/js/blockFilter.js#L5-L8).
