### ISSUE TITLE
Block class standards

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#73]
For blocks, I've been doing things like `e-div`, `e-img`, etc. and attributes are just the attribute names.

**Comment by an-OK-squirrel** [comment]
Seems good.

**Comment by matthewr6** [comment]
https://github.com/ElementalCode/Elemental/blob/block-editor/resources/js/block2json.js#L109 to https://github.com/ElementalCode/Elemental/blob/block-editor/resources/js/block2json.js#L112

**Comment by an-OK-squirrel** [comment]
Use the tags and attrib names. Super easy.

**Comment by matthewr6** [comment]
Just wanted everyone to see this
