### ISSUE TITLE
Blocks show behind palette

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#74]
![cparkaokraadaffafdsa](https://cloud.githubusercontent.com/assets/12722625/9312581/1a3f80ee-44e3-11e5-9f1d-f660a8c552bf.png)

That's confusing :p

**Comment by matthewr6** [comment]
Just don't do it then :P  I might be able to fix that, but after I fix some other stuff

**Comment by an-OK-squirrel** [comment]
I'll fix it

**Comment by an-OK-squirrel** [comment]
Whoops, how do I compile sass again :p

**Comment by an-OK-squirrel** [comment]
MAN THIS SHOULD BE WORKING
it's not :p

**Comment by an-OK-squirrel** [comment]
:p

**Comment by matthewr6** [comment]
_facepalm_
are you using the CLI or a GUI?

**Comment by an-OK-squirrel** [comment]
what?

**Comment by an-OK-squirrel** [comment]
I remembered how to compile sass.
Now my code won't work :p

**Comment by matthewr6** [comment]
keep having deja vu when I open up Sublime lol

**Comment by an-OK-squirrel** [comment]
xD

**Comment by matthewr6** [comment]
it doesn't have anything to do with sass anyways I think

**Comment by an-OK-squirrel** [comment]
Yeah.

**Comment by an-OK-squirrel** [comment]
thanks

**Comment by matthewr6** [comment]
np
