### ISSUE TITLE
Login is ugly ugly ugly

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#77]

**Comment by PullJosh** [comment]
Once I finish the making the forum signature (#50), I'll design those pages to match the theme.

Firedrake can then work the design into the backend. :)

**Comment by PullJosh** [comment]
Let's keep this open for now. It's still very much in progress, and will act as a nice reminder for me. :)

**Comment by matthewr6** [comment]
haha

**Comment by an-OK-squirrel** [comment]
Yes! just got a laptop! :D 

Anyways, sounds good!

**Comment by PullJosh** [comment]
We can close for now... getting the editor working is the top priority.
