### ISSUE TITLE
General page structure

### ISSUE THREAD

**Issue by quat1024** [ElementalCode/elemental#8]
What's the overall structure of an HTML file you create with this going to look like?

One idea --> 
http://scratchblocks.github.io/#html%20%3A%3A%20hat%20events%0Adoctype%20%5Bhtml%204%20v%5D%20%3A%3A%20control%0Ahead%20%3A%3A%20cstart%20control%0A.%20.%20.%0Abody%20%3A%3A%20celse%0A.%20.%20.%0A%3A%3Acend%20cap

**Comment by matthewr6** [comment]
We should force HTML5, because HTML5 is awesome.

But I like that.

**Comment by BookOwl** [comment]
"We should force HTML5, because HTML5 is awesome.

But I like that."
+1

**Comment by quat1024** [comment]
Do you like that one (sans doctype, maybe), or this one better?

http://scratchblocks.github.io/#page%20%5Bindex.html%20v%5D%20%3A%3A%20events%20hat%0Ahtml%20%3A%3A%20cstart%20events%0Ahead%20%3A%3A%20cstart%20control%0A.%20.%20.%0A%3A%3Acend%0Abody%20%3A%3Acstart%20control%0A.%20.%20.%0A%3A%3Acend%0A%3A%3Acend%20cap

I like the first one.

**Comment by PullJosh** [comment]
First one.

**Comment by BookOwl** [comment]
First one

**Comment by matthewr6** [comment]
What they said.

**Comment by glacialcascade** [comment]
Me like http://scratchblocks.github.io/#page%20%5Bindex.html%20v%5D%20%3A%3A%20hat%20events%0Adoctype%20%5Bhtml%205%20v%5D%20%3A%3A%20control%0Ahtml%20%3A%3Acstart%20pen%0Ahead%20%3A%3A%20cstart%20control%0A.%20.%20.%0Abody%20%3A%3A%20celse%0A.%20.%20.%0A%3A%3Acend%20cap%0A%3A%3Acend%20cap

**Comment by matthewr6** [comment]
https://github.com/ElementalCode/Elemental/issues/1#issuecomment-122609687

**Comment by quat1024** [comment]
General consensus seems to be the head/body E-shaped block so I'll close this

**Comment by an-OK-squirrel** [comment]
Yep!
