### ISSUE TITLE
Trash vs. drag to palette (or both?)

### ISSUE THREAD

**Issue by towerofnix** [ElementalCode/elemental#80]
So basically I was wondering if we should have a trash can positioned somewhere in the block editor to drag blocks into. At the moment I couldn't figure out how to get rid of blocks! :P

It would probably work more or less the same way Stencyl's does.

Though personally I would prefer having both the trash can icon to delete, as well as dragging blocks into the block palette.

State your opinion!

**Comment by towerofnix** [comment]
(LLK/Scratch style milestones maybe? :P)

**Comment by matthewr6** [comment]
You can't get rid of the blocks yet :P

**Comment by quat1024** [comment]
Drag blocks anywhere outside of the block area to delete sounds good. Like, drag them onto the webpage, or back to the block palette, or w/e

ed: So i'm not sure if a trash can icon is really needed. But it might be cute idk.

**Comment by matthewr6** [comment]
i should be able to do that

**Comment by PullJosh** [comment]
If we're only doing one, it should be to drag them out of the block area.

But doing both would be fine to. (My only objection is that we shouldn't do trash exclusively.)

**Comment by matthewr6** [comment]
I don't want to do both just because it's more effort for me :P

**Comment by PullJosh** [comment]
+1 for enthusiasm

**Comment by matthewr6** [comment]
<sub><sup>well i'm making everything else also</sup></sub>

**Comment by PullJosh** [comment]
Yeah, but I just made a crappy footer.

Take that.

**Comment by matthewr6** [comment]
ggnore

**Comment by towerofnix** [comment]
haha.

**Comment by an-OK-squirrel** [comment]
I'm gonna do this and it's gonna SUCK!

:package:

**Comment by towerofnix** [comment]
woot

**Comment by rumanti** [comment]
I vote both for child-friendly and practical, simple usability :yum:

**Comment by TheInitializer** [comment]
Both.
- Trash can to be intuitive
- Palette for people who are used to scratch

**Comment by towerofnix** [comment]
@TheInitializer ^^^

**Comment by PullJosh** [comment]
^^^

**Comment by towerofnix** [comment]
How's the code going @an-OK-squirrel? :P

**Comment by an-OK-squirrel** [comment]
too tired to code

don't ask

**Comment by PullJosh** [comment]
*Firedrake takes over*

**Comment by matthewr6** [comment]
haha I might not because school

**Comment by PullJosh** [comment]
WHY IS EVERYONE IN SCHOOL ALREADY

NOBODY WILL ANSWER ME O_O

**Comment by matthewr6** [comment]
dragging to palette works
PJ, please make a trash can icon so I can drag things to it

**Comment by PullJosh** [comment]
Okay! Svg or png?

**Comment by TheInitializer** [comment]
SVG

**Comment by matthewr6** [comment]
whatever you want

**Comment by PullJosh** [comment]
If we took this image:
![image](https://i.gyazo.com/2c2e0ac2269fe823fd03e53828b62e53.png)
and then replaced the black with white and overlayed it in the bottom right of the editor, would that look good?

**Comment by PullJosh** [comment]
(But obviously smaller)

**Comment by matthewr6** [comment]
put it in - you made the UI, so you try it :P  also I might go at any minute and I hate leaving unfinished work

**Comment by PullJosh** [comment]
You mean put it in the actual editor?

**Comment by matthewr6** [comment]
block-editor branch yes

**Comment by PullJosh** [comment]
k

**Comment by matthewr6** [comment]
done

**Comment by TheInitializer** [comment]
btw don't forget to make a beautiful animation to go with it!

**Comment by matthewr6** [comment]
functionality first.  we have higher priorities (eg multiple files, css)
