### ISSUE TITLE
File pane location

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#85]
Top priority right now.  Not the home page.
Both its position and the actual implementation (though not file selection and creation yet :P)

**Comment by PullJosh** [comment]
Very good point.

**Comment by PullJosh** [comment]
Very good point.

**Comment by Firedrake969** [comment]
Very repetitive.

**Comment by Firedrake969** [comment]
Very repetitive.

**Comment by PullJosh** [comment]
All the glitch.

**Comment by PullJosh** [comment]
All the glitch.

**Comment by Firedrake969** [comment]
very funny

**Comment by Firedrake969** [comment]
very funny

**Comment by PullJosh** [comment]
Does everyone agree that [this](https://cloud.githubusercontent.com/assets/5458180/8761638/18d2bdce-2d29-11e5-92ef-adc6955c1055.png) is a good way of doing the file pane? (Tabs at the bottom for already-opened files,  home link opens [something like this](https://cloud.githubusercontent.com/assets/5458180/8759819/b7828d8a-2ccc-11e5-837c-9ecb8fd82ad3.png).)

**Comment by an-OK-squirrel** [comment]
Seem good!

**Comment by towerofnix** [comment]
Looks pretty nice to me! Obviously redesigned to look good for Elemental but yeah, the general design of it looks awesome.

**Comment by matthewr6** [comment]
On second thought, it might just be easier to have a file pane the same way Scratch has sprite panes.  I'm going to go ahead and try it out (also since I'll probably end up implementing the JS for it :P)

**Comment by PullJosh** [comment]
You do that. :P

**Comment by matthewr6** [comment]
can we please just make this a thing with a single HTML, CSS, and JS file (like Codepen)?  It'll make life a lot easier :P (i'll probably start out making that work first anyways)

hmm first we'd need a way to render the blocks from JSON

**Comment by an-OK-squirrel** [comment]
hmmmmm

okay?

**Comment by PullJosh** [comment]
@Firedrake969 That would be okay, but people still need to be able to upload resources such as images.

**Comment by matthewr6** [comment]
I thought we decided to have them use an outside image host.

**Comment by matthewr6** [comment]
https://github.com/ElementalCode/Elemental/issues/29#issuecomment-123830038

**Comment by PullJosh** [comment]
Ah, didn't see that.

**Comment by matthewr6** [comment]
Just need deletion now.
