### ISSUE TITLE
I feel guilty..

### ISSUE THREAD

**Issue by rumanti** [ElementalCode/elemental#86]
I haven't made a single commit, major or minor :/ All I've done is advertise Elemental on my signature, which is nothing. I don't know what I should or need to do. 

Site design is already filled by PullJosh and infinitytec, UI by PullJosh, .. And I don't have any good experience with the back-end (just a couple of PHP commands, that's all I can speak of).

Now what can I do? :confused:

**Comment by Cats-United** [comment]
I would join, but I was busy.

**Comment by an-OK-squirrel** [comment]
meh.

i'm having text editor trouble :p

**Comment by PullJosh** [comment]
Advertising is a really helpful thing to do!

However, posting a bit of code is fun as well. ;) Why don't you figure out which blocks need to be added to the editor (HTML only at the minute) and start to add them. See [blockFilter.js](https://github.com/ElementalCode/Elemental/blob/block-editor/resources/js/blockFilter.js). Comment at [line 42](https://github.com/ElementalCode/Elemental/blob/block-editor/resources/js/blockFilter.js#L42) explains how to add blocks, which you can then do down below. If you want to add any palettes (block categories), you'll have to modify the array at [line 5](https://github.com/ElementalCode/Elemental/blob/block-editor/resources/js/blockFilter.js#L5). The position of the palette name in the array determines what number it corresponds to (palette 0 is text, 1 is media, and so on). You'll also have to change the palette name in the HTML.

**Comment by PullJosh** [comment]
Also, be sure to [refer to this](https://github.com/ElementalCode/Elemental/issues/58) if you're going to add palettes.

**Comment by an-OK-squirrel** [comment]
I got sublime soo I'm back in business </cool>

**Comment by TheInitializer** [comment]
> And I don't have any good experience with the back-end (just a couple of PHP commands, that's all I can speak of).

We're not using php though, we're using python and django :D

**Comment by rumanti** [comment]
@PullJosh That's really helpful, thanks!
@TheInitializer Okay. :D

**Comment by matthewr6** [comment]
because PHP is ugly

not sorry at all

**Comment by Cats-United** [comment]
@Firedrake969 - I have to use PHP all the time. :P

**Comment by matthewr6** [comment]
Disgusting :P

**Comment by Cats-United** [comment]
It's because Gwiddle doesn't use Python. Some of the syntax is fine to me, others not, such as variables. _Money can't buy variables_

@Rumanti - I can make my own money by making 100000000 variables in PHP.

**Comment by rumanti** [comment]
Regarding PHP, it looks nice and powerful to me, but I don't use it much so I can't judge :P 

@Cats-United What's wrong with the "$" symbol? Do you need money like I am?

**Comment by PullJosh** [comment]
http://blog.codinghorror.com/the-php-singularity/

**Comment by rumanti** [comment]
Oh :)

**Comment by matthewr6** [comment]
hahahahahaha
http://prntscr.com/87xv6d

**Comment by PullJosh** [comment]
Wordpress functions starting with a:
![image](https://cloud.githubusercontent.com/assets/5458180/9428587/2b593666-4981-11e5-8ea4-9480a80ed1dd.png)

**Comment by PullJosh** [comment]
^ As per this: http://blog.codinghorror.com/php-sucks-but-it-doesnt-matter/

**Comment by matthewr6** [comment]
And https://semitwist.com/articles/article/view/facebook-is-not-written-in-php
(warning, profanity)
