### ISSUE TITLE
Light or dark?

### ISSUE THREAD

**Issue by an-OK-squirrel** [ElementalCode/elemental#87]
I remember one site had a thing where you could set your user page to dark or light.

Something like that?

**Comment by matthewr6** [comment]
I think light is better but I think PJ disagrees.

**Comment by towerofnix** [comment]
So like _Snap!_?

Have a setting I think. Default based on voting lol

**Comment by an-OK-squirrel** [comment]
Yeah. I'm doing light for the userpage but we can changify that

**Comment by PullJosh** [comment]
@Firedrake969 I'm okay with light, but it would mean we have to redesign the entire site.

If people think it's worth doing, be my guest.

**Comment by matthewr6** [comment]
I guess dark would work if we did something like codepen...

**Comment by an-OK-squirrel** [comment]
hmmmmm

**Comment by quat1024** [comment]
Develop dark first, then maybe add light if we wanna.

**Comment by rumanti** [comment]
I honestly prefer a dark theme, because 1) it will look cool 2) the colors will be very eye-catching 3) focused 4) doesn't sting the eyes. 

But it's always nice to have an option!

**Comment by PullJosh** [comment]
Sounds like we'll do dark (at least to start).

**Comment by an-OK-squirrel** [comment]
Okay den
