### ISSUE TITLE
Are we going to add the new HTML5 tags like <header>, <nav>, <footer>, etc?

### ISSUE THREAD

**Issue by rumanti** [ElementalCode/elemental#88]
^
Those new tags added in HTML5 tell browsers which section is which, if the browsers support them- and as far as I know (and tested), they wouldn't cause riot in earlier browsers. I think using those tags is a good practice, as they really improve accessibility. They _might_ also help organize code.

What do you think?

**Comment by PullJosh** [comment]
Personally, I would include them. :)

**Comment by rumanti** [comment]
I'll get to work on it. Discussions might take place once I make the pull request ;)

**Comment by PullJosh** [comment]
Okay! :)

**Comment by PullJosh** [comment]
I'll close for now, but feel free to re-open this if you want to discuss anything. :)

**Comment by matthewr6** [comment]
Do a pull from and to into GH-pages, please.  I'm working with the filesystem on block-editor

**Comment by rumanti** [comment]
@Firedrake969 OK.
