### ISSUE TITLE
ElementalCode.github.io

### ISSUE THREAD

**Issue by glacialcascade** [ElementalCode/elemental#9]
Should I create it now?

**Comment by glacialcascade** [comment]
Also, how do we decide on the css/stuff (for the website)? And should we have a homepage, a coding page, a helppage, etc.?

**Comment by matthewr6** [comment]
Is this where we'll host the site?

**Comment by glacialcascade** [comment]
I guess

**Comment by matthewr6** [comment]
might be better to use heroku or something, but I've never used heroku so I'll check it out

as long as we don't have a cron job/celery/something of the like we should be good

**Comment by glacialcascade** [comment]
?

**Comment by matthewr6** [comment]
? about heroku, or cron/celery?

**Comment by PullJosh** [comment]
I _really_ want to be the one to design the site.

I get all OCD if I don't do it.
(You guy can do code structure and stuff, but I call dibs on site design.)

**Comment by matthewr6** [comment]
I want to use Heroku really really badly.

**Comment by PullJosh** [comment]
I'll use Heroku if you'll let me do the design. xD

**Comment by glacialcascade** [comment]
you do site design (so css / heroku) if you want

**Comment by matthewr6** [comment]
Sure, want me to make the account?

**Comment by PullJosh** [comment]
Yeah! That'd be great. I'll start (and probably finish) design tomorrow. For now, though, I've got to go. :)

**Comment by matthewr6** [comment]
Ok
It'll be a personal account, is that OK?  Or should I make a group account but under a fake name?
(we'll have to get someone's email address for it though)

**Comment by PullJosh** [comment]
Personal is fine. If you want to make a group one, you can though. You can use my email.

**Comment by matthewr6** [comment]
so many assignments
and school hasn't even started

**Comment by PullJosh** [comment]
xD

**Comment by PullJosh** [comment]
So much for leaving. :3

**Comment by glacialcascade** [comment]
leaving what

**Comment by PullJosh** [comment]
https://github.com/ElementalCode/Elemental/issues/9#issuecomment-122610110

**Comment by quat1024** [comment]
Ok coming from someone who doesn't know much about heroku - Why Heroku?

**Comment by matthewr6** [comment]
Don't know...
It seemed easier than AWS and DigitalOcean, so I went with it.

**Comment by matthewr6** [comment]
btw, app is live now on http://elementalcode.heroku.com

**Comment by quat1024** [comment]
Why not something like Github Pages though - does it not do everything we need?

**Comment by matthewr6** [comment]
Some backend stuff that we might need, like generating the zip file.
Also, I need practice deploying stuff.

**Comment by quat1024** [comment]
I mean there's https://stuk.github.io/jszip/ . But practicing is a perfectly valid reason hehe

**Comment by matthewr6** [comment]
Also, Django's templating engine is amazing for modular HTML.
If only for cleanliness, it's still nice.
Also, if we want to be able to upload files, we'll probably need a backend.

**Comment by PullJosh** [comment]
All of those things we _probably_ won't need, but when you add them all together, there's a good chance we'll need at least one of those features.

Also, learning.

**Comment by matthewr6** [comment]
Yeah - if for no other reason, this is going to be a good experience (and probably complicated :P)

**Comment by glacialcascade** [comment]
We need github.io not heroku >:D

**Comment by PullJosh** [comment]
The more that I'm thinking about this, the less it makes sense to do the explanation site now. It can wait. After all, what am I going to put on it? We don't have anything to show yet!

**Comment by ev3commander** [comment]
ElementalCode.github.io

**Comment by quat1024** [comment]
Why do we have 2 websites now :/

**Comment by PullJosh** [comment]
Should I remove @ev3commander from the org? All he has done is spam that URL. :/

**Comment by ev3commander** [comment]
github is backup

**Comment by glacialcascade** [comment]
github is the backup

**Comment by PullJosh** [comment]
**Always talk to others before making executive decisions.**
^ Borderline all caps worthy

**Comment by an-OK-squirrel** [comment]
![always](https://cloud.githubusercontent.com/assets/12722625/8787549/726b2998-2efa-11e5-80ee-0b69fddd22d3.png)
ALWAYS

**Comment by an-OK-squirrel** [comment]
No offense ev3, but I think we should remove him. :/

**Comment by matthewr6** [comment]
No preference yet.

**Comment by an-OK-squirrel** [comment]
OK.

**Comment by TheInitializer** [comment]
Can we use openshift instead of heroku? Heroku doesn't work on windows

**Comment by matthewr6** [comment]
Heroku works on Windows (though I'm struggling to run the Django app locally, but that's not Heroku)

**Comment by TheInitializer** [comment]
yeah, heroku requires this app that only works on linux (and kinda works on mac) in order to test the site locally.

**Comment by matthewr6** [comment]
If you mean foreman, foreman works on Windows for me.  It's just the requirements that break things for me

**Comment by TheInitializer** [comment]
WHAT HOW U MAKE IT WORKKKKKKK

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by matthewr6** [comment]
No idea, but it just worked when I downloaded it :P 
Maybe because I have Ruby installed?

**Comment by TheInitializer** [comment]
I have ruby too…

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by PullJosh** [comment]
Nice avast sig thing. :P

**Comment by TheInitializer** [comment]
@PullJosh my email thing adds that in for me and I can't remove it :P

**Comment by PullJosh** [comment]
You can't? Huh. Weird.

**Comment by matthewr6** [comment]
Will report back when I get home, @TheInitializer 
Docker and Docker-compose >>>>> everything else

**Comment by BookOwl** [comment]
Well, at least I know his comment is safe! :P (or is it?)

**Comment by PullJosh** [comment]
This thread seems a bit dead.
Going to close to keep things nice and tidy. Feel free to reopen if discussion here needs to continue.

**Comment by matthewr6** [comment]
yeah

**Comment by an-OK-squirrel** [comment]
Okay!
