### ISSUE TITLE
Scrolling Problem

### ISSUE THREAD

**Issue by Angelflower0** [ElementalCode/elemental#92]
When I put the big link, whenever I tried scrolling back, it wouldn't show the sprite area. Screenshot- http://prntscr.com/885ao3

**Comment by matthewr6** [comment]
Can't seem to reproduce - anyone else?

**Comment by PullJosh** [comment]
I got it as well... very strange.

**Comment by PullJosh** [comment]
For people who want it: http://megaurl.it/

**Comment by matthewr6** [comment]
Fixed.

**Comment by PullJosh** [comment]
Only appears to happen when link is above the body...

But it seems I'm too late.

**Comment by matthewr6** [comment]
Firedrake969, fixing bugs faster than you can describe them.  xD
/modesty

**Comment by PullJosh** [comment]
Oh, and the resizing thing is working now.

**Comment by matthewr6** [comment]
Yeah I forgot to commit them

**Comment by PullJosh** [comment]
Good job.

**Comment by matthewr6** [comment]
Thanks :P
