### ISSUE TITLE
Indirect body movement

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#93]
"Indirect body movement" reminds me of ragdoll physics, but no...

The body element can't move. However, if you put a moveable element above it and then drag the one you can drag, the body moves and you can't get it back.

**Comment by matthewr6** [comment]
That's what Angelflower0 found out just now too :P 
Fixing

**Comment by PullJosh** [comment]
Synchronised bug catching... should be a sport.

**Comment by PullJosh** [comment]
Did you close because it's fixed?

**Comment by matthewr6** [comment]
Yes and a duplicate issue

**Comment by PullJosh** [comment]
Oh :3
