### ISSUE TITLE
Excess space on page

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#95]
Go to Elemental editor, click on mousewheel and move mouse down (will cause page to scroll down).

Likely due to file manager.

**Comment by matthewr6** [comment]
~~Easily fixable~~
weird flexbox css things make this act really weirdly.  wontfix for now, since it's really minor anyways

**Comment by an-OK-squirrel** [comment]
Randomness but....

For the user page, do you want any styling at all? Or just layout?

**Comment by an-OK-squirrel** [comment]
@Firedrake969

**Comment by AwesomeMinecrafter94** [comment]
Uh, what's this. Why am I getting random emails. Please unsubscribe me
immediately now

On Mon, Aug 24, 2015, 5:12 PM an-OK-squirrel notifications@github.com
wrote:

> @Firedrake969 https://github.com/Firedrake969
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ElementalCode/Elemental/issues/95#issuecomment-134381595
> .
> 
> ## 

Minecraft is Awesome 94% of the time!

**Comment by AwesomeMinecrafter94** [comment]
Oh, wait never mind

On Mon, Aug 24, 2015, 5:18 PM Joshua Rieth awesomeminecrafter94@gmail.com
wrote:

> Uh, what's this. Why am I getting random emails. Please unsubscribe me
> immediately now
> 
> On Mon, Aug 24, 2015, 5:12 PM an-OK-squirrel notifications@github.com
> wrote:
> 
> > @Firedrake969 https://github.com/Firedrake969
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ElementalCode/Elemental/issues/95#issuecomment-134381595
> > .
> > 
> > ## 
> 
> Minecraft is Awesome 94% of the time!
> 
> ## 

Minecraft is Awesome 94% of the time!

**Comment by an-OK-squirrel** [comment]
You do it on your account settings. That's not us.

**Comment by an-OK-squirrel** [comment]
You auto-get notifications

**Comment by matthewr6** [comment]
Uh who is this guy
we can't unsubscribe you btw
