### ISSUE TITLE
Block drag position relative to page scroll

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#96]
When you scroll down and try to drag a block in, this happens:
![GIFS GIFS EVERYWHERE](https://i.gyazo.com/88d82a07beeaa005bed81a7310b29a38.gif)

The distance between the mouse and the block is the same as the amount that you scrolled down.

**Comment by towerofnix** [comment]
Major because pages have a lot of content and scrolling is important. :P

**Comment by matthewr6** [comment]
Probably easily fixable, just use it based on parent's scroll pos

**Comment by PullJosh** [comment]
Uh oh... appears to happen when top area is scrolled as well.

**Comment by matthewr6** [comment]
Oh ok

**Comment by matthewr6** [comment]
Fixed

**Comment by PullJosh** [comment]
Dude... You're a bug-fixing machine.

5 cents a piece and you'd be rich!

**Comment by matthewr6** [comment]
Haha

**Comment by towerofnix** [comment]
heh
