### ISSUE TITLE
Can't edit inputs in Safari (9)

### ISSUE THREAD

**Issue by towerofnix** [ElementalCode/elemental#97]
(but the problem will apply to Safari 8 as well I think..)

Anyways I can't edit inputs.

'nuff said.

(Also, if I try to drag while on an input, it does nothing.)

**Comment by rumanti** [comment]
I can edit inputs, but the placeholder text (e.g. this is an important heading) wouldn't go, and has no effect on the iframe. And I am using the latest Mozilla Firefox.

**Comment by matthewr6** [comment]
Works for me on Chrome and Edge.  Don't have Firefox or Safari to test on.

**Comment by matthewr6** [comment]
Might have to do w/ z-index...  Because contenteditable normally should work in the major browsers

**Comment by matthewr6** [comment]
Can some other people confirm this for Firefox?  (not too worried about Safari... you should only use FF or Chrome for web development anyways :P)

**Comment by an-OK-squirrel** [comment]
will confirm....

**Comment by an-OK-squirrel** [comment]
Can edit inputs on FF

**Comment by matthewr6** [comment]
cool thanks
tbch idc much abt non-FF/Chrome because those are the only two that have good consoles anyways
(wow my abbreviations there... to be completely honest, I don't care, about)

Thoughts on that?

**Comment by an-OK-squirrel** [comment]
dunno :p

**Comment by matthewr6** [comment]
how are user page mockups coming along?

**Comment by an-OK-squirrel** [comment]
I have a question:

You just want me to create a layout, right? no style or anything?

**Comment by matthewr6** [comment]
layout first yes

**Comment by an-OK-squirrel** [comment]
k

**Comment by an-OK-squirrel** [comment]
I was thinking wikipedia style. If you're on mobile everything collapses

**Comment by matthewr6** [comment]
cool

**Comment by an-OK-squirrel** [comment]
Now to see how wikipedia does it :p

**Comment by towerofnix** [comment]
On one hand, yes, I should only use FF and Chrome for development. On the other hand, no, not everybody uses Chrome and FF - some people use Safari.. :P

**Comment by matthewr6** [comment]
But they shouldn't for development :P

**Comment by towerofnix** [comment]
Bump. Any ideas? Maybe there's an element over the input?

**Comment by matthewr6** [comment]
We're focusing on Firefox and Chrome for now

**Comment by towerofnix** [comment]
:(
