### ISSUE TITLE
Trash icon doesn't open when dragging block

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#98]
The trash can icon will "open" when you hover over it. However, it won't open if you're dragging a block.

This is exactly the opposite of what we want to have happen.

**Comment by an-OK-squirrel** [comment]
Yes it does....

**Comment by an-OK-squirrel** [comment]
Browser?

**Comment by matthewr6** [comment]
Not for me, and chrome.  Shouldn't be too hard.

**Comment by PullJosh** [comment]
Chrome here as well...

**Comment by rumanti** [comment]
It works for me on Firefox. (Again, latest version)

**Comment by matthewr6** [comment]
fixed a while ago
