### ISSUE TITLE
Block layout is ugly

### ISSUE THREAD

**Issue by PullJosh** [ElementalCode/elemental#99]
I'm probably the one to blame for this, but... The arrangement of the blocks in the upper area is horrific.

Maybe instead of flexbox we should try something like CSS columns?

**Comment by matthewr6** [comment]
Do whatever as long as it doesn't interfere with the functionality

**Comment by PullJosh** [comment]
Okay. Going to make a branch called editor-fixes with a variety of small tweaks and improvements. :)

**Comment by matthewr6** [comment]
Ok cool

**Comment by PullJosh** [comment]
Fixed with #100.
